* vocabulary
consistency
faceted
adoption
workload
scale
flexible
ingestion
emerging
downtime
immune
express
robust
diagnostic /ˌdaɪəgˈnɒstɪk; 诊断的，诊断  diagnose vt. 诊断；断定。vi. 诊断；判断
uptime
sophisticated \So*phis"ti*cate\ [sə'fɪstɪkeɪtɪd] adj. 复杂的；富有经验的。 v. 使变得世故；使迷惑；篡改
utilization  /ˌjuːtəlaɪˈzeɪʃn;  
incorporate  /ɪnˈkɔːpəreɪt; ɪn`kɔrpəret/ 包含，合并
-----
grid
renaldotap
identity
hobby
mess
aido
penny
grab
cart
intriguing
odds
pull up
pastry
initiate
reimburse
rub
stun
tone
idiot
casino
rein
rediation
extrame
explore
roofie
zipped
intentions
cap
scrumptious
jokes
polite
tacky
lipstick
consistency
passum
grip
clown
zinger
robbery
sealed
cockpit
weird
blow
sake
ass
blew
porn
beast
bodyguard
bidder
scooter
betour
stick
capri
clip
slip
dement
outfit
glove
creature
bid
spotted
diversion
huge
indispose
glove
rage
arrest
upset
slutty
torture
basement
jelly
eventually
reminisce
traitor
sorrow
fake
undercover
asshole
hang tight
bound
untie
restraint
lick
apeal
dare
entire
pathetic
pronounce
handsome
nuke
radiation
strafe
crawl
slippery
trapeze
split
copter
disguise
certain
infiltrate

-----
lasso
acquire
seminar
restore
chimes
ghostmasters
conversition
chess
ocean
mozart
piss
insulate
autistic
remark
crack
wetware
fluid
chaotic
intersection
indication
gaze
bet
concentration
engage
intellect
drip
flirt
crush
specialist
simulate
blackout
induction
overload
spin
competition
unwind
tore
uptime
quote
due
defend
crack
simulate
vodka
bastard
hook
moral

-----dracula-----
refuge
seek
negotiate
tribute
pluck
complaint
fierce
march
sustance
spare
strike
resist
sundown
rear
blade
sentries
inflate
sword
silver
repent
forsaken
pathetic
impaler
devil
goat
dispense
legacy

-----supremacy-----
deputy
pant
gasket
lip
ex-con
boogeyman
nigger
patience
dude
trapped
mess
discipline
disobey
goddam
ass
freak
comprede
overhear
downright
groupie
racist
rite
desert
uncross
metal
slice
chop
violate
least
record
grab
whitest
soil
idiot
redeo
windy
flexible
courage
loyalty
roadblock
hustle
dumb
joker
mood
flinch
dignity
mad
hostage
dick
bolt
down
ignorant
blame
grubby
sneaky
clasp
