* 接入脚本信息维护
** 系统
*** 增，改，查 接入的系统
**** 增加系统
前缀
系统名称
连接参数
并行度
定时
schema
用户名
密码

所有参数均为必填项。
**** 查询系统状态
前缀
系统名称
schema
定时

选填。
**** 修改系统状态 
前缀
系统名称
连接参数
并行度
定时
schema
用户名
密码
上线
下线
下线原因（如果下线为选中，则必须写下线原因）

备注：
系统上/下线是把 t_shell_list 中该系统下所有的表上/下线。
上线， 下线为 2 选 1; 如果设为上线，上线时间不可以大于当前时间， 并且不小于上次的上线时间; 如果选择下线则必须填写下线时间和下线原因，否则下线时间和下线原因为空，其余的均为必填项。
**** 删除系统状态
前缀，系统名称，schema。（或者 id）


*** 处理过程
**** 上线新的系统：
用来配置接入系统的参数。

上线系统需要把信息插入到两个表中， 一个是 t_sys，一个是 t_sys_mapping。
t_sys 中插入的数据： 前缀， 系统名称， 连接参数, 并行度， 定时，schema， 用户名，密码，创建时间（插入数据时的时间）， 是否上线设为 1(1：上线，0：不上线）， 上线时间（插入数据时的时间）， 是否下线设为 0（1：下线，0：不下线）， 下线时间是空, 下线原因是空。
t_sys_mapping 中插入的数据： 系统名称， 前缀，schema。

数据插入成功返回 ture,跳转到成功窗口；失败返回 false，跳转到失败窗口，打印失败原因。

**** 查询系统
1）. 用于查询系统的配置参数。
2）. 用于修改系统，删除系统的前置， 查询出来的数据会附带一个"修改"或者"删除"按钮， 用于跳转到相应的页面。

根据选填的条件从数据库中查询符合条件的列表，列表返回数据的字段为： 前置， 系统名称， 连接参数， 并行度， 定时，schema, 用户名， 密码，创建时间， 上线/下线， 上线时间， 下线时间（没有下线则为空），下线原因，列表后边有相应的操作选项， "修改"和"删除"。

点击"修改"选项会跳入到修改系统状态页面。
点击"删除"选项会跳入到删除系统状态页面。

**** 修改系统
用来修改系统的配置参数。

首先需要先查询系统，查询系统的返回数据是目前数据库中的参数信息，然后修改需要修改的参数（前缀， 系统名称， 连接参数， 并行度， 定时，schema, 用户名， 密码，创建时间（不可修改）， 上线/下线， 上线时间， 下线时间（没有下线则为空），下线原因（如果选择下线则必须填写下线原因，否则下线原因为空）)，然后在"保存"或者"取消"修改两个选项中选择一个，如果选择保持则保存更新 t_sys，t_sys_mapping 两张表中的数据，选择取消则返回到关闭修改窗口。

t_sys 中更新的数据： 前缀， 系统名称， 连接参数, 并行度， 定时，schema， 用户名，密码，创建时间（不可修改）， 上线（1：上线，0：不上线）， 上线时间， 下线（1：下线，0：不下线），下线时间，下线原因。
t_sys_mapping 中更新的数据： 系统名称， 前缀，schema。

更新成功返回 ture,跳转到成功窗口；失败返回 false，跳转到失败窗口，打印失败原因。
**** 删除系统（待定， 要不要）
删除已经上线的系统。

首先需要先查询系统，然后返回查询的系统列表，查看是否要删除的系统，如果是则点击删除按钮，删除 t_sys 和 t_sys_mapping 表中相应的记录。

成功返回 ture,跳转到成功窗口；失败返回 false，跳转到失败窗口，打印失败原因。

*** 输出
增加系统：数据插入成功返回 ture,跳转到成功窗口；失败返回 false，跳转到失败窗口。
查询：返回数据列表。
修改：保存数据时更新成功返回 ture,跳转到成功窗口；失败返回 false，跳转到失败窗口，打印失败原因。
删除：成功返回 ture,跳转到成功窗口；失败返回 false，跳转到失败窗口，打印失败原因。
** 表
*** 增，删，改，查表的接入方式
**** 增加表配置
用来配置接入系统的参数。

     1. 输入
        表名， 前缀，是否分区， 优先级，schema, 原表分区字段， 分区字段类型， 分区字段模式，hive 中分区字段名称， 从第几天前接入， 接入几天数据， 大字段， 重试次数。
     2. 处理过程
        将数据的数据插入 t_shell_list 表中， 如果不是分区接入， 则原表分区字段，分区字段类型，分区字段模式，hive 中分区字段名称都为空，默认是接入一天前的数据， 并且接入一天的数据，上线日期为数据插入时的时间。
        
        插入成功返回 ture,跳转到成功窗口；失败返回 false，跳转到失败窗口，打印失败原因。
     3. 输出
        插入成功返回 ture,跳转到成功窗口；失败返回 false，跳转到失败窗口，打印失败原因。
**** 查询表配置
1）. 用于查询表的配置参数。
2）. 用于修改表，删除表的前置， 查询出来的数据会附带一个"修改"或者"删除"按钮， 用于跳转到相应的页面。
     1. 输入
        前缀，系统，表名
     2. 处理过程
        根据传入的参数返回一个列表。列表包含表 t_shell_list 表中所有字段。列表后边有相应的操作选项--"修改"和"删除"。

        点击"修改"选项会跳入到修改表状态页面。
        点击"删除"选项会跳入到删除表状态页面。
**** 修改表配置
用来修改表的配置参数。

表名， 前缀，是否分区， 优先级，是否上线，schema, 原表分区字段， 分区字段类型， 分区字段模式，hive 中分区字段名称， 从第几天前接入， 接入几天数据， 大字段， 重试次数，下线时间（没有下线则为空）， 下线原因（没有下线则为空）。


需要首先查询表的配置， 返回的表配置数据是目前数据库中的参数信息，然后点击"修改"按钮进入修改表配置页面，修改需要修改的参数（如果表下线，下线日期和下线原因必须填写）， 然后点击"取消"或者"保存"中的一个按钮， 如果点击"保存"， 则更新 t_shell_list 中相应的信息， 如果点击"取消", 则退出页面。 

更新成功返回 ture,跳转到成功窗口；失败返回 false，跳转到失败窗口，打印失败原因。
**** 删除表配置（待定， 要不要）



* 计算脚本信息维护
** 
为脚本调度中心提供基础信息支持。

高

脚本所在的服务器，目录，输入脚本名称(以;分割），输出脚本名称，调度周期，上线时间，是否下线（1：下线，0：没有下线，默认是 0），下线时间， 下线原因。

*** 增加脚本
脚本所在的服务器，目录，输入脚本名称(以;分割），输出脚本名称，调度周期

将填写的表单插入到表中， 其中上线时间为插入时的时间，之后不可更改，是否下线默认为否， 下线时间跟下线原因为空。

插入成功返回 ture,跳转到成功窗口；失败返回 false，跳转到失败窗口，打印失败原因。
*** 查询脚本
1）. 用于查询脚本的配置参数。
2）. 用于修改脚本，删除脚本的前置， 查询出来的数据会附带一个"修改"或者"删除"按钮， 用于跳转到相应的页面。

输入： 脚本名称

根据传入的脚本名称返回一个列表。列表为表中符合此次查询记录的所有字段。列表后边有相应的操作选项--"修改"和"删除"。

  点击"修改"选项会跳入到修改脚本状态页面。
  点击"删除"选项会跳入到删除脚本状态页面。


*** 修改脚本
用来修改脚本的配置参数。

首先根据输入的脚本名称查询脚本的配置， 返回的列表数据为数据库中的参数信息，然后点击"修改"按钮进入修改脚本配置页面，修改需要修改的参数（如果是下线，则下线时间及下线原因必须填写）， 然后点击"取消"或者"保存"中的一个按钮， 如果点击"保存"， 则更新表中相应的信息， 如果点击"取消", 则退出页面。 

更新成功返回 ture,跳转到成功窗口；失败返回 false，跳转到失败窗口，打印失败原因。
*** 删除脚本
删除已经上线的脚本。

首先根据输入的脚本名称查询脚本的配置，返回的列表数据为数据库中的参数信息，查看是否要删除的脚本，如果是点击"删除"按钮，删除表中相应的记录。

成功返回 ture,跳转到成功窗口；失败返回 false，跳转到失败窗口，打印失败原因。
* 
为脚本调度中心提供基础信息支持。
包含有哪些接入脚本、优先级、开始接入时间、使用哪台备库等信息。
是否重试
1）功能描述


2）优先级
高

3）输入

4）处理过程


5）输出

6）验收准则

7）用户界面
