注意应用， 考虑主力是怎么想的
* 技术分析理论
** 道琼斯理论，道氏理论(Dow theory) 
道氏理论有三个核心思想，即三重运动原理、相互验证原则和投机原理。
*** 三重运动原理
相互验证原则，通过相关性来验证结论的正确性，通过认识市场以及再认识市场，不断重复理论与实践的循环来验证市场与我们的预测之间的关系。

在三重运动原理中，道氏将市场的走势分为三种运动，即基本运动、次级运动以及日常波动。市场的基本运动是可以被预测的，预测次级运动很容易被欺骗，而日常运动是随机漫步的，是不可预测的，因此，市场的主体趋势是可以被预测的，而每一个价格的波动时间和位置又是测不准确的。必然当中有偶然，偶然中又有必然，这是一种辩证的思想方法。

短期趋势,持续数天至数个星期;中期趋势,持续数个星期至数个月;长期趋势,持续数个月至数年。任何市场中,这三种趋势必然同时存在,彼此的方向可能相反。

股价第一级的波动，即主级正向波，是最为重要的价格波动形式，是投资者获取战略性利润的基础，这也正是我们通常所说的牛市或熊市。第二级波动，即是次级逆向波，是最具虚假性的欺骗性波动，是市场得以存在的基础，也是绝大部分投资者亏损失败的陷阱，也正是我们通常所说的调整或反弹。第三级波动，即是日间杂波，是最无意义的价格波动，是诱惑投资者不断参与的诱饵，也正是我们通常所说盘中即时股价走势。该种日间杂波走势目前无法寻找到不变的规律，今后也永远无法寻找到。从本质上看，它具有最大的随意性、不确定性和可人为操纵性。
*** 相互验证原则
对于两个有较强相关性的品种或指数，当它们之间的走势一致的时候，其中一个品种或指数的走势可以得到另一个品种或指数的验证，这意味着趋势还将继续;当它们之间的走势背离的时候，则其中一个品种或指数的走势不能得到另一个品种或指数的验证，这意味着趋势难以继续。利用计算机建立模式，当我们得到相关系数ρ1 达到 70%以上，且相关系数ρ2 在 50%以上时，我们就可以认为两个变量存在着较强的相关性。

道氏所指的相互验证原理并非是现象间简单的验证，它既是指不同相关制约要素间的相互验证关系，也是指不同要素、不同指标间的相互验证。对此投资者应该进行准确的理解。两者的制约因素不同，但是又有较强的相关性，这是相互验证原则成立的必要条件。相互验证原则是十分重要的，它贯穿于市场分析的始终。

更重要的是，在相关市场所组成的群类中，各个市场倾向于同步，因此我们必须探索一下与研究对象同属一个群类的其他市场的行为。如果我们分析的是某金属市场，那么也应当看看其他金属市场的情况如何。对其他市场的研究经常为我们的分析对象提供一些线索。

　　我们还可以考察我们的分析是否与商品市场的大方向一致。如果商品市场在总体上处于下降趋势中，对于任何个别市场的看涨分析，我们都需要把它的分量打些折扣。因此，我们必须明确，商品的总体环境到底是牛市还是熊市。
*** 投机原理
投机原理，所谓投机也就是我们的预期是否能够在市场中得到贴现，可以说市场中已经包含了我们对于市场的预期，我们的预期是市场中不可分割的组成部分，因此投机也是市场的成分之一。

在投机的定义中表明，投机的本质特征是主体(投资者)伪愿望能在客体(市场)中得到反应。如果市场所反应的是广大投资者的愿望，这才是我们真正意义上的市场投机行为；但如果投机行为反应的仅仅是政府或政策的愿望，这将可能反而给市场带来过度投机;而如果投机行为反应的是战争发动者的愿望，一定将会带来极限投机。因此，我们有必要分清市场投机行为与过度投机行为和极限投机行为的区别。
*** 道氏理论的五个“定理”
**** 定理一：道氏的三种走势(短期,中期,长期趋势)
股票指数与任何市场都有三种趋势:短期趋势,持续数天至数个星期;中期趋势,持续数个星期至数个月;长期趋势,持续数个月至数年。任何市场中,这三种趋势必然同时存在,彼此的方向可能相反。

　　长期趋势最为重要,也最容易被辨认,归类与了解。它是投资者主要的考量,对于投机者较为次要。中期与短期趋势都属于长期趋势之中,唯有明白他们在长期趋势中的位置,才可以充分了解他们,并从中获利。

　　中期趋势对于投资者较为次要,但却是投机者的主要考虑因素。它与长期趋势的方向可能相同,也可能相反。如果中期趋势严重背离长期趋势,则被视为是次级的折返走势或修正(correction)。次级折返走势必须谨慎评估,不可将其误认为是长期趋势的改变。

　　短期趋势最难预测,唯有交易者才会随时考虑它。投机者与投资者仅有在少数情况下,才会关心短期趋势:在短期趋势中寻找适当的买进或卖出时机,以追求最大的获利,或尽可能减少损失。
**** 定理二：主要走势（空头或多头市场）
主要走势(Primary Movements):主要走势代表整体的基本趋势,通常称为多头或空头市场,持续时间可能在一年以内,乃至于数年之久。正确判断主要走势的方向,是投机行为成功与否的最重要因素。没有任何已知的方法可以预测主要走势的持续期限。
**** 定理三：主要的空头市场（包含三个主要的阶段）
空头市场会历经三个主要的阶段: 第一阶段,市场参与者不再期待股票可以维持过度膨胀的价格;第二阶段的卖压是反映经济状况与企业盈余的衰退; 第三阶段是来自于健全股票的失望性卖压,不论价值如何,许多人急于求现至少一部分的股票。这项定义有几个层面需要理清。"重要的反弹"(次级的修正走势)是空头市场的特色,但不论是"工业指数",或 "运输指数",都绝对不会穿越多头市场的顶部,两项指数也不会同时穿越前一个中期走势的高点。"不利的经济因素" 是指(几乎毫无例外)政府行为的结果:干预性的立法,非常严肃的税务与贸易政策,不负责任的货币或(与)财政政策以及重要战争。

个人也曾经根据"道氏理论"将 1896 年至目前的市场指数加以归类,在此列举空头市场的某些特质:

　　1. 由前一个多头市场的高点起算,空头市场跌幅的平均数(median)为 29.4%,其中 75%的跌幅介于 20.4%至 47.1%之间。

　　2. 空头市场持续期限的平均数是 1.1 年,其中 75%的期间介于 0.8 年至 2.8 年之间。

　　3. 空头市场开始时,随后通常会以偏低的成交量"试探"前一个多头市场的高点,接着出现大量急跌的走势。所谓"试探"是指价格接近而绝对不会穿越前一个高点。"试探"期限,成交量偏低显示信心减退,很容易演变为"不再期待股票可以维持过度膨胀的价格"。

　　4. 经过一段相当程度的下跌之后,突然会出现急速上涨的次级折返走势,接着便形成小幅盘整而成交量缩小的走势, 但最后仍将下滑至新的低点。

　　5. 空头市场的确认日(confirmation date),是指两种市场指数都向下突破多头市场最近一个修正低点的日期。两种指数突破的时间可能有落差,并不是不正常的现象。

　　6. 空头市场的中期反弹,通常都呈现颠倒的"V-型",其中低价的成交量偏高,而高价的成交量偏低。有关空头市场的情况,雷亚的另一项观察非常值得重视:
**** 定理四：主要的多头市场(也有三个主要的阶段)
多头市场有三个阶段:第一阶段,人们对于未来的景气恢复信心;第二阶段,股票对于已知的公司盈余改善产生反应; 第三阶段,投机热潮转炽而股价明显膨涨--这阶段的股价上涨是基于期待与希望。

　　这项定义也需要理清。多头市场的特色是所有主要指数都持续联袂走高,拉回走势不会跌破前一个次级折返走势的低点,然后再继续上涨而创新高价。在次级的折返走势中,指数不会同时跌破先前的重要低点。主要多头市场的重要特质如下:

　　1. 由前一个空头市场的低点起算,主要多头市场的价格涨幅平均为 77.5%。

　　2. 主要多头市场的期间长度平均数为两年又四个月(2.33 年)。历史上的所有的多头市场中,75%的期间长度超过 657 天(1.8 年), 67%介于 1.8 年与 4.1 年之间。

　　3. 多头市场的开始,以及空头市场最后一波的次级折返走势,两者之间几乎无法区别,唯有等待时间确认。

　　4. 多头市场中的次级折返走势,跌势通常较先前与随后的涨势剧烈。另外,折返走势开始的成交量通常相当大,但低点的成交量则偏低。

　　5. 多头市场的确认日,是两种指数都向上突破空头市场前一个修正走势的高点,并持续向上挺升的日子。
**** 定理五：次级折返走势
次级折返走势(Second Reactions)：就此处的讨论来说,次级折返走势是多头市场中重要的下跌走势,或空头市场中重要的上涨走势,持续的时间通常在三个星期至数个月;此期间内折返的幅度为前一次级折返走势结束之后主要走势幅度的 33%至 66%。次级折返走势经常被误以为是主要走势的改变,因为多头市场的初期走势,显然可能仅是空头市场的次级折返走势,相反的情况则会发生在多头市场出现顶部后。
** 艾略特波浪理论(Elliott Wave Principle)
　波浪是指股票价格的波动,都与大自然的潮汐,波浪一样,一浪跟着一浪,周而复始,具有相当程度的规律性,以一种"可识别的模式"前进和反转,这些模式在形态上不断重复(不一定在时间和幅度上重复)。
*** 波浪理论的出发点
- 人类社会永远进步向前;
- 人类群体的行为是可以预测的
- 股市反映的就是人类的群体行为
*** 波浪理论的基础
五升三降是波浪理论的基础

艾略特指出股市呈一定的基本韵律和型态，五个上升波和三个下降波构成了八个波的完整循环。三个下降波作为前五个上升波之调整（Correction），图 2 表示五个代表上升方向的推进波（Impulse Waves）和三个调整波（Corrective Waves）。

波动原理有三个重要概念：波的型态、波幅比率、持续时间。其中最重要的是型态。波有两个基本型态：推进波 5－3-5-3-5 和调整波 5－3－5。

波浪形成的基本概念可总结如下：

　　1）一个运动之后必有相反运动发生；

　　2）主趋势上的推进波与主趋势方向相同，通常可分为更低一级的五个波；调整波与主趋势方向相反，或上升或下降．通常可分为更低一级的三个波。

　　3）八个波浪运动（五个上升，三个下降）构成一个循环，自然又形成上级波动的两个分支。

　　4）市场形态并不随时间改变。波浪时而伸展时而压缩，但其基本形态不变。

　　在实践中,每一个波浪并不是相等的，它可以压缩，可以延长，可以简单，可以复杂。总之，一切以型态为准。下面，提供几个较为典型的例子（如图 4）。
*** 波浪理论的四个基本特点
  （1）股价指数的上升和下跌将会交替进行；

　　（2）推动浪和调整浪是价格波动两个最基本型态，而推动浪（即与大市走向一致的波浪）可以再分割成五个小浪，一般用第１浪、第２浪、第３浪、第４浪、第５浪来表示，调整浪也可以划分成三个小浪，通常用Ａ浪、Ｂ浪、Ｃ浪表示。

　　（3）在上述八个波浪（五上三落）完毕之后，一个循环即告完成，走势将进入下一个八波浪循环；

　　（4）时间的长短不会改变波浪的形态，因为市场仍会依照其基本型态发展。波浪可以拉长，也可以缩细，但其基本型态永恒不变。

　　总之，波浪理论可以用一句话来概括：即"八浪循环"

如何区分三浪和五浪结构?
　　看这一浪与它的上一层次浪的运行趋势是否相同,如相同,则为五浪,不同则为三浪.
*** 艾略特波段理论内容的几个基本的要点：

　　①一个完整的循环包括八个波浪，五上三落。

　　②波浪可合并为高一级的浪，亦可以再分割为低一级的小浪。

　　③.跟随主流行走的波浪可以分割为低一级的五个小浪。

　　④1、3、5 三个波浪中，第 3 浪不可以是最短的一个波浪。

　　⑤假如三个推动论中的任何一个浪成为延伸浪，其余两个波浪的运行时间及幅度会趋一致。

　　⑥.调整浪通常以三个浪的形态运行。

　　⑦黄金分割率理论奇异数字组合是波浪理论的数据基础。

　　⑧经常遇见的回吐比率为 0.382、0.5 及 0.618。

　　⑨第四浪的底不可以低于第一浪的顶。

　　⑩艾略特波段理论包括三部分：型态、比率及时间，其重要性以排行先后为序。⑾艾略特波段理论主要反映群众心理。越多人参与的市场，其准确性越高。
** 江恩法则
[[wiki.mbalib.com/wiki/江恩十二条买卖规则][江恩十二条买卖规则]]
江恩认为，进行交易必须根据一套既定的交易规则去操作，而不能随意地买卖，盲目地猜测市场的发展情况。随着时间的转变，市场的条件也会跟随转变，投资者必须学会跟随市场的转变而转变，而不能认死理。

　江恩在十二条规则之上，建立了整个买卖的系统。基本上，所使的方法是纯粹技术性为主，而买卖方法是以跟随市势买卖为主，与他的预测预备完全不同。

　　1. 决定市场的走势；

　　2. 在单底、双底或三底水平入市买入；

　　3. 根据市场波动的百分比买卖；

　　4. 根据三星期上升或下跌买卖；

　　5. 市场分段波动；

　　6. 利用 5 或 7 点波动买卖；

　　7. 成交量；

　　8. 时间因素；

　　9. 当出现高低点或新高时买入；

　　10. 决定于大势趋势的转向；

　　11. 最安全的买卖点；

　　12. 快速市场的价位波动。


江恩二十一条买卖法则
   1、每次入市买、卖，损失不应超过资金的十分之一。

　　2、永远都设立止损位，减少买卖出错时可能造成的损失。

　　3、永不过量买卖。

　　4、永不让所持仓位转盈为亏。

　　5、永不逆市而为。市场趋势不明显时，宁可在场外观望。

　　6、有怀疑，即平仓离场。入市时要坚决，犹豫不决时不要入市。

　　7、只在活跃的市场买卖。买卖清淡时不宜操作。

　　8、永不设定目标价位出入市，避免限价出入市，而只服从市场走势。

　　9、如无适当理由、不将所持仓平盘，可用止赚位保障所得利润。

　　10、在市场连战皆捷后，可将部分利润提取，以备急时之需。

　　11、买股票切忌只望分红收息。(赚市场差价第一)

　　12、买卖遭损失时，切忌赌徒式加码，以谋求摊低成本。

　　13、不要因为不耐烦而入市，也不要因为不耐烦而平仓。

　　14、肯输不肯赢，切戒。赔多赚少的买卖不要做

　　15、入市时落下的止损位，不宜胡乱取消。

　　16、做多错多，入市要等候机会，不宜买卖太密。

　　17、做多做空自如，不应只做单边。

　　18、不要因为价位太低而吸纳，也不要因为价位太高而沽空。

　　19、永不对冲。

　　20、尽量避免在不适当时搞金字塔加码。

　　21、如无适当理由，避免胡乱更改所持股票的买卖策略。
* 主要分析方法
* 主要分析指标
