* Tecknology Index Analysis
** macd macd 跟收盘价有关系. *中长线指标*
   是多个收盘价的加权平均, 然后在多个收盘价平均之后相减, 再求加权平均.
  1、计算移动平均值（EMA）
  2、计算离差值（DIF）
  3、计算 DIF 的 9 日 EMA
#+BEGIN_SRC 
  以 EMA1 的参数为 12 日，EMA2 的参数为 26 日，DIF 的参数为 9 日为例来看看 MACD 的计算过程
  1、计算移动平均值（EMA）
  12 日 EMA 的算式为
  EMA（12）=前一日 EMA（12）×11/13＋今日收盘价×2/13
  26 日 EMA 的算式为
  EMA（26）=前一日 EMA（26）×25/27＋今日收盘价×2/27
  2、计算离差值（DIF）
  DIF=今日 EMA（12）－今日 EMA（26）
  3、计算 DIF 的 9 日 EMA
  根据离差值计算其 9 日的 EMA，即离差平均值，是所求的 MACD 值。为了不与指标原名相混淆，此值又名 DEA 或 DEM。
  今日 DEA（MACD）=前一日 DEA×8/10＋今日 DIF×2/10
  计算出的 DIF 和 DEA 的数值均为正值或负值。
#+END_SRC
** KDJ kdj 跟收盘价, 最低价, 最高价有关系. *中短期*
    1. n 日 RSV=（Cn－Ln）÷（Hn－Ln）×100
    2. 当日 K 值=2/3×前一日 K 值＋1/3×当日 RSV
    3. 当日 D 值=2/3×前一日 D 值＋1/3×当日 K 值
    4. J 指标的计算公式为：J=3D—2K
   #+BEGIN_SRC 
    首先要计算周期（n 日、n 周等）的 RSV 值，即未成熟随机指标值，然后再计算 K 值、D 值、J 值等。以日 KDJ 数值的计算为例，其计算公式为:
    1. n 日 RSV=（Cn－Ln）÷（Hn－Ln）×100
      式中，Cn 为第 n 日收盘价；Ln 为 n 日内的最低价；Hn 为 n 日内的最高价。RSV 值始终在 1—100 间波动。

    其次，计算 K 值与 D 值：
    2. 当日 K 值=2/3×前一日 K 值＋1/3×当日 RSV
    3. 当日 D 值=2/3×前一日 D 值＋1/3×当日 K 值
    若无前一日 K 值与 D 值，则可分别用 50 来代替。

    以 9 日为周期的 KD 线为例。首先须计算出最近 9 日的 RSV 值，即未成熟随机值，计算公式为
    9 日 RSV=（C－L9）÷（H9－L9）×100
    式中，C 为第 9 日的收盘价；L9 为 9 日内的最低价；H9 为 9 日内的最高价。
    K 值=2/3×前一日 K 值＋1/3×当日 RSV
    D 值=2/3×前一日 K 值＋1/3×当日 RSV
    若无前一日 K 值与 D 值，则可以分别用 50 代替。

    需要说明的是，式中的平滑因子 1/3 和 2/3 是可以人为选定的,不过目前已经约定俗成，固定为 1/3 和 2/3。在大多数股市分析软件中，平滑因子已经被设定为 1/3 和 2/3，不需要作改动。另外，一般在介绍 KD 时，往往还附带一个 J 指标。
    4. J 指标的计算公式为：J=3D—2K
    实际上，J 的实质是反映 K 值和 D 值的乖离程度，从而领先 KD 值找出头部或底部。J 值范围可超过 100。
#+END_SRC
** RSI RSI 跟收盘价有关 *中短线指标*
   先计算连续两天的收盘价差值, 然后差值为正值的总和与差值为负值的总和相比, 求相对强弱.

#+BEGIN_SRC 
  相对强弱指标 RSI 的计算公式有两种
  其一：
  假设 A 为 N 日内收盘价的正数之和，B 为 N 日内收盘价的负数之和乘以（—1）
  这样，A 和 B 均为正，将 A、B 代入 RSI 计算公式，则
  RSI（N）=A÷（A＋B）×100

  其二：(有加权)
  RS（相对强度）=N 日内收盘价涨数和之均值÷N 日内收盘价跌数和之均值
  RSI（相对强弱指标）=100－100÷（1+RS）
  这两个公式虽然有些不同，但计算的结果一样。

  以 14 日 RSI 指标为例，从当起算，倒推包括当日在内的 15 个收盘价， * 以每一日的收盘价减去上一日的收盘价 *，得到 14 个数值，这些数值有正有负。这样，RSI 指标的计算公式具体如下：
  A=14 个数字中正数之和
  B=14 个数字中负数之和乘以（—1）
  RSI（14）=A÷（A＋B）×100
  式中：A 为 14 日中股价向上波动的大小
  B 为 14 日中股价向下波动的大小
  A＋B 为股价总的波动大小
#+END_SRC
** VR VR 跟成交量和股价上涨下跌有关 *中长期*
   VR 指标是用上涨时期的量除以下跌时期的量, 所以 VR 有一个相对强弱的概念.
   是否也需要涨停和跌停时的量.
#+BEGIN_SRC 
（1）N 日以来股价上涨的那一日的成交量都称为 UV，将 N 日内的 UV 总和相加称为 UVS。

（2）N 日以来股价下跌的那一日的成交量都称为 DV，将 N 日内的 DV 总和相加称为 DVS。

（3）N 日以来股价平盘的那一日的成交量都称为 PV，将 N 日内的 PV 总和相加称为 PVS。

（4）最后 N 日的 VR 就可以计算出来

VR（N）=（UVS＋1/2PVS）÷（DVS＋1/2PVS）
#+END_SRC
** DMI DMI 跟最高价,最低价,收盘价 中长期
#+BEGIN_SRC
1. 计算当日动向值
  上升动向： +DM=今天最高—昨天最高价之差  （差值≤0，则记成 0）   
  下降动向： —DM=昨天最低—今天最低价之差  （差值≤0，则记成 0）  
  无动向：  1). +DM， -DM 同时为 0. 2). 上升动向值正好等于下降动向值.

  +DM7=7 天的+DM1 值总合  —DM7=7 天的—DM1 值总合

2. 计算真实波幅（TR）
  TR 代表真实波幅，是当日价格较前一日价格的最大变动值。

  A、当日的最高价减去当日的最低价的价差。
  B、当日的最高价减去前一日的收盘价的价差。
  C、当日的最低价减去前一日的收盘价的价差。
  TR 是 A、B、C 中的数值最大者

  TR7=7 天的 TR1 总合

3. 计算方向线 DI 
  方向线 DI 是衡量股价上涨或下跌的指标，分为“上升指标”和“下降指标”。在有的股市分析软件上，+DI 代表上升方向线，﹣DI 代表下降方向线。其计算方法如下：

  +DI=（DM÷TR）×100

  ﹣DI=（﹣DM÷TR）×100

  要使方向线具有参考价值，则必须运用平滑移动平均的原理对其进行累积运算。以 12 日作为计算周期为例，先将 12 日内的+DM、﹣DM 及 TR 平均化，所得数值分别为+DM12，﹣DM12 和 TR12，具体如下：

  +DI（12）=（+DM12÷TR12）×100

  ﹣DI（12）=（﹣DM12÷TR12）×100

  随后计算第 13 天的+DI12、﹣DI12 或 TR12 时，只要利用平滑移动平均公式运算即可。
  例如：
  当日的 TR12=11/12÷前一日 TR12＋当日 TR
  上升或下跌方向线的数值永远介于 0 与 100 之间。

4. 计算动向平均数 ADX
  依据 DI 值可以计算出 DX 指标值。其计算方法是将+DI 和—DI 间的差的绝对值除以总和的百分比得到动向指数 DX。由于 DX 的波动幅度比较大，一般以一定的周期的平滑计算，得到平均动向指标 ADX。具体过程如下：

  DX=(DI DIF÷DI SUM) ×100

  其中，DI DIF 为上升指标和下降指标的价差的绝对值

  DI SUM 为上升指标和下降指标的总和

  ADX 就是 DX 的一定周期 n 的移动平均值。
5. 计算评估数值 ADXR
  在 DMI 指标中还可以添加 ADXR 指标，以便更有利于行情的研判。

  ADXR 的计算公式为：

  ADXR=（当日的 ADX＋前一日的 ADX）÷2
#+END_SRC
** CR CR 跟最高价,最低价,中间价有关 中长期
#+BEGIN_SRC
  以日 CR 指标为例，其计算公式为：
  CR（N 日）=P1÷P2×100
  式中，P1=∑（H－YM），表示 N 日以来多方力量的总和
  P2=∑（YM－L），表示 N 日以来空方力量的总和
  H 表示今日的最高价，L 表示今日的最低价
  YM 表示昨日（上一个交易日）的中间价

  目前比较常用地中间价计算方法有四种：

  1、M=（2C+H+L）÷4
  2、M=（C+H+L+O）÷4
  3、M=（C+H+L）÷3
  4、M=（H+L）÷2
#+END_SRC
** DMA DMA 跟股价的平均值有关 中短期
#+BEGIN_SRC
DMA 指标的计算方法比较简单，其计算过程如下：
DMA=短期平均值—长期平均值
AMA=短期平均值
以求 10 日、50 日为基准周期的 DMA 指标为例，其计算过程具体如下：
DMA（10）=10 日平均值—50 日平均值
AMA（10）=10 日平均值
#+END_SRC
** OBV OBV 跟收盘价和成交量有关 短期
#+BEGIN_SRC
今日 OBV=昨天 OBV+sgn×今天的成交量  
其中 sgn 是符号的意思，sgn 可能是+1，也可能是-1，这由下式决定。
Sgn=+1 今收盘价≥昨收盘价  Sgn=—1 今收盘价<昨收盘价.   
成交量指的是成交股票的手数，不是成交金额。
#+END_SRC
** AR,BR AR 跟当日最高价, 最低价和当日收盘价有关;BR 跟当日最高价,最低价和昨日收盘价有关 中长期
#+BEGIN_SRC
AR 指标的计算方法:
N 日 AR=N 日内（H－O）之和除以 N 日内（O－L）之和.
其中，H 为当日最高价，L 为当日最低价，O 为当日收盘价，N 为设定的时间参数，一般原始参数日设定为 26 日

BR 指标的计算方法:
N 日 BR=N 日内（H－CY）之和除以 N 日内（CY－L）之和.
其中，H 为当日最高价，L 为当日最低价，CY 为前一交易日的收盘价，N 为设定的时间参数，一般原始参数日设定为 26 日。
#+END_SRC
** TRIX TRIX 跟收盘价有关 长期
#+BEGIN_SRC
1、计算 N 天的收盘价的指数平均 AX

AX=（I 日）收盘价×2÷（N＋1）＋（I－1）日 AX（N－1）÷（N＋1）

2、计算 N 天的 AX 的指数平均 BX

BX=（I 日）AX×2÷（N＋1）＋（I－1）日 BX（N－1）÷（N＋1）

3、计算 N 天的 BX 的指数平均 TRIX

TRIX=（I 日）BX×2÷（N＋1）＋（I－1）日 TAIX（N－1）÷（N＋1）

4、计算 TRIX 的 m 日移动平均 TRMA

TRMA=＜（I－M）日的 TRIX 累加＞÷M
#+END_SRC
** CCI CCI 跟最高价,最低价,收盘价有关 
#+BEGIN_SRC 
以日 CCI 计算为例，其计算方法有两种。

第一种计算过程如下：
CCI（N 日）=（TP－MA）÷MD÷0.015
其中，TP=（最高价+最低价+收盘价）÷3
MA=最近 N 日收盘价的累计之和÷N
MD=最近 N 日（MA－收盘价）的累计之和÷N
0.015 为计算系数，N 为计算周期

第二种计算方法表述为
中价与中价的 N 日内移动平均的差除以 N 日内中价的平均绝对偏差
其中，中价等于最高价、最低价和收盘价之和除以 3
平均绝对偏差为统计函数
#+END_SRC
** BOLL BOLL 跟收盘价有关 中长期
#+BEGIN_SRC
1、日 BOLL 指标的计算公式
中轨线=N 日的移动平均线
上轨线=中轨线＋两倍的标准差
下轨线=中轨线－两倍的标准差

2、日 BOLL 指标的计算过程
（1）计算 MA
MA=N 日内的收盘价之和÷N
（2）计算标准差 MD
MD=平方根 N 日的（C－MA）的两次方之和除以 N
（3）计算 MB、UP、DN 线
MB=（N－1）日的 MA
UP=MB＋2×MD
DN=MB－2×MD
#+END_SRC
** W%R 跟最高价,最低价,收盘价有关 短期
#+BEGIN_SRC
  W%R=（Hn—C）÷（Hn—Ln）×100
  其中：C 为计算日的收盘价，Ln 为 N 周期内的最低价，Hn 为 N 周期内的最高价，公式中的 N 为选定的计算时间参数，一般为 4 或 14。

  以计算周期为 14 日为例，其计算过程如下：
  W%R（14 日）=（H14—C）÷（H14—L14）×100
  其中，C 为第 14 天的收盘价，H14 为 14 日内的最高价，L14 为 14 日内的最低价。
#+END_SRC
** MTM MTM 跟收盘价有关 中短期技
#+BEGIN_SRC
  1、第一种计算方法
  以日 MTM 指标为例，其计算过程如下：
  MTM（N 日）=C－CN
  式中，C=当日的收盘价
  CN=N 日前的收盘价
  N 为计算参数，一般起始参数为 6

  2、第二种计算方法
  以日 MTM 指标为例，其计算过程如下：
  MTM（N 日）=（C÷CN×100）－100
  式中，C=当日的收盘价
  CN=N 日前的收盘价
  N 为计算参数，一般起始参数为 6

#+END_SRC
** MIKE MIKE 跟最高价,最低价,收盘价有关 中长期
#+BEGIN_SRC
1、计算初始价——TYP 的数值
TYP=（H＋L＋C）÷3
式中，H=当日的最高价
L=当日的最低价
C=当日的收盘价
TYP 为起始价

有的股市分析软件还采用加权方法进行计算，计算公式为：
TYP=（H＋L＋2C）÷4
两式中字母代号所表示的含义是一样的，计算的结果差别不大。MIKE 指标是利用起始价位来计算出股价的弱、中、强的三个压力价位和三个支撑价位，从而为预测股价未来走势提供帮助。

2、计算股价的三个压力价位
MIKE 指标中的三个压力价位分别为：初级压力——WR、中级压力——MR 和强力压力——SR。它们的计算公式为：
WR（N 日）=TYP＋（TYP－LN）
MR（N 日）=TYP＋（HN－LN）
SR（N 日）=2×HN－LN
式中，TYP=起始价
LN=N 日的最低价
HN=N 日的最高价

3、计算股价的三个支撑价位
MIKE 指标中的三个支撑价位分别为：初级支撑——WS、中级支撑——MS 和强力支撑——SS。它们的计算公式为：
WS（N 日）=TYP－（HN－TYP）
MS（N 日）=TYP－（HN－LN）
SS（N 日）=2×LN－HN
式中，TYP=起始价
LN=N 日内的最低价
HN=N 日内的最高价
#+END_SRC
** PSY PSY 跟收盘价有关 短期
#+BEGIN_SRC
PSY（N）=A÷N×100
其中，N 为周期，是 PSY 的参数，可以为日、周、月、分钟
A 为在这周期之中股价上涨的周期数
例如：N=20 日时，日之中有 12 日上涨，8 日下跌，则 PSY（20 日）=60
这里判断上涨和下跌是以收盘价为标准，计算日周期的收盘价如果比上一周期的收盘价高，则定为上涨；比上一周期的收盘价低，则定为下跌。
#+END_SRC
** BIAS BIAS 跟收盘价有关 短中长期
#+BEGIN_SRC
N 日 BIAS=（当日收盘价—N 日移动平均价）÷N 日移动平均价×100

N 的采用数值有很多种，常见的有两大种。一种是以 5 日、10 日、30 日和 60 日等以 5 的倍数为数值的；一种是 6 日、12 日、18 日、24 日和 72 日等以 6 的倍数为数值的。不过尽管它们数值不同，但分析方法和研判功能是相差不大.
#+END_SRC
** ASI ASI 跟当天及前一天的最高价,最低价,收盘价,开盘价有关
#+BEGIN_SRC
1. A=当天最高价-前一天收盘价
　　B=当天最低价-前一天收盘价
　　C=当天最高价-前一天最低价
　　D=前一天收盘价-前一天开盘价
　　A、B、C、D 皆采用绝对值
2. E=当天收盘价-前一天收盘价
　　F=当天收盘价-当天开盘价
　　G=前一天收盘价-前一天开盘价
　　E、F、G 采用其+－差值
3. X＝E＋1／2F＋G。
4. K=比较 A、B 两数值，选出其中最大值
5. 比较 A、B、C 三数值：
　　若 A 最大，则 R＝A＋ 1／2B＋ 1／4D
　　若 B 最大，则 R＝B＋1／２A 十 1／4D
　　若 C 最大，则 R= C＋1/4D
6. L＝3
7. SI= 50* X／R * K／L
8. ASI=累计每日之 SI 值
#+END_SRC
** EMV EMV 跟今日和前日的最高价, 最低价和今日成交额有关
#+BEGIN_SRC
1.A=（今日最高+今日最低）/2
  B=（前日最高+前日最低）/2
  C=今日最高-今日最低
2.EM=（A-B）*C/今日成交额
3.EMV=N 日内 EM 的累和
4.MAEMV=EMV 的 M 日的简单移动平均
5.参数 N 为 14，参数 M 为 9
#+END_SRC
** WVAD WVAD 跟收盘价,开盘价,最高价,最低价及成交金额有关
#+BEGIN_SRC
一) 以 WVAD 是否穿越零轴线，作为买卖标准时有很严重的延误性，往往股价已冲高许多时，才会出现买入信号，反之亦然。也有使用 WVAD 和 WVAD 的 6 日平均线做比较进行研判，但误差率较高，特别是在卖出信号的研判上。
　　1、A=当天收盘价－当天开盘价
　　2、B=当天最高价－当天最低价
　　3、V=当天成交金额
　　4、WVAD=∑(A÷B×V)
　　5、参数周期可更改为 6 或 12 天
二) 改进方案： 成交量改为成交额，使用成交量或使用成交额对于个股的研判并没有太大的区别.
　　WVAD＝当日收盘价－当日开盘价÷当日最高价－当日最低价×成交额
　　WVAD5＝当日收盘价－当日开盘价÷当日最高价－当日最低价×成交额的 5 日累加÷5
　　WVAD21＝当日收盘价－当日开盘价÷当日最高价－当日最低价×成交额的 21 日累加÷21
#+END_SRC
** ROC ROC 跟收盘价有关
#+BEGIN_SRC
1、AX=今天的收盘价—12 天前的收盘价
2、BX=12 天前的收盘价
3、ROC=AX/BX
#+END_SRC
** OBOS OBOS 跟股票价格上涨和下跌有关 中长期 股票指数
#+BEGIN_SRC
OBOS（N 日）=∑NA－∑NB

式中，∑NA——N 日内股票上涨家数之和

∑NB——N 日内股票下跌家数之和

N 为选择的天数，是日 OBOS 指标的参数
#+END_SRC
** ADR ADR 跟股票价格上涨和下跌有关 中长期 股票指数
#+BEGIN_SRC
ADR（N 日）=P1÷P2

式中，P1=ΣNA——N 日内股票上涨家数之和

P2=ΣND——N 日内股票下跌家数之和

N 为选择的天数，是日 ADR 的参数
#+END_SRC
** ADL ADL 跟股票价格上涨和下跌有关 股票指数
#+BEGIN_SRC
如果当日所有股票中上涨的共有 A 家，下降的共有 F 家，持平的为 B 家，这里涨跌标准是以当日收盘价与上一日收盘价相比较。这样当日的 ADL 值的计算公式为
当日 ADL=上一日 ADL＋A－F

由上式推出：
当日 ADL=∑A－∑F
式中，∑A 表示从开始交易的第一天算起，每一个交易日的上涨家数的总和
∑F 表示从开始交易的第一天算起，每一个交易日的下跌家数的总和
#+END_SRC
* explain some phenomenon
** 日内反转
   目的是买入(卖出)股票. 操作者上午(下午)快速大量的卖出, 然后在股价下跌(上升)的过程中接盘不停卖出(买入)的股票. 同时, 剧烈下跌(上升或下跌方向线的数值永远介于的估计)及高成交量使市场注意到这只股票. 就在股价跌至谷底(高峰), 成交量升至顶峰时, 操作者扭转战术, 买入(卖出)所有在售的股票.

   日内反转发生在股价顶端, 预示着下行趋势即将出现; 同理, 发生在股价低端时, 预示着上行趋势即将出现. 不管哪种情况, 其共同点是一天内高成交量伴随着股价上行继续深入之前的运动方向,  下午掉头向相反的方向, 最终收盘价是当日与开盘价相反的价格范围断点之上.

   不是所有日内反转都会带来股票快速, 显著的变化, 有时候需要很多天或者很多周之后股票才会动起来.
