注意应用， 考虑主力是怎么想的
* 技术分析理论
** 道琼斯理论，道氏理论(Dow theory) 
道氏理论有三个核心思想，即三重运动原理、相互验证原则和投机原理。
*** 三重运动原理
相互验证原则，通过相关性来验证结论的正确性，通过认识市场以及再认识市场，不断重复理论与实践的循环来验证市场与我们的预测之间的关系。

在三重运动原理中，道氏将市场的走势分为三种运动，即基本运动、次级运动以及日常波动。市场的基本运动是可以被预测的，预测次级运动很容易被欺骗，而日常运动是随机漫步的，是不可预测的，因此，市场的主体趋势是可以被预测的，而每一个价格的波动时间和位置又是测不准确的。必然当中有偶然，偶然中又有必然，这是一种辩证的思想方法。

短期趋势,持续数天至数个星期;中期趋势,持续数个星期至数个月;长期趋势,持续数个月至数年。任何市场中,这三种趋势必然同时存在,彼此的方向可能相反。

股价第一级的波动，即主级正向波，是最为重要的价格波动形式，是投资者获取战略性利润的基础，这也正是我们通常所说的牛市或熊市。第二级波动，即是次级逆向波，是最具虚假性的欺骗性波动，是市场得以存在的基础，也是绝大部分投资者亏损失败的陷阱，也正是我们通常所说的调整或反弹。第三级波动，即是日间杂波，是最无意义的价格波动，是诱惑投资者不断参与的诱饵，也正是我们通常所说盘中即时股价走势。该种日间杂波走势目前无法寻找到不变的规律，今后也永远无法寻找到。从本质上看，它具有最大的随意性、不确定性和可人为操纵性。
*** 相互验证原则
对于两个有较强相关性的品种或指数，当它们之间的走势一致的时候，其中一个品种或指数的走势可以得到另一个品种或指数的验证，这意味着趋势还将继续;当它们之间的走势背离的时候，则其中一个品种或指数的走势不能得到另一个品种或指数的验证，这意味着趋势难以继续。利用计算机建立模式，当我们得到相关系数ρ1 达到 70%以上，且相关系数ρ2 在 50%以上时，我们就可以认为两个变量存在着较强的相关性。

道氏所指的相互验证原理并非是现象间简单的验证，它既是指不同相关制约要素间的相互验证关系，也是指不同要素、不同指标间的相互验证。对此投资者应该进行准确的理解。两者的制约因素不同，但是又有较强的相关性，这是相互验证原则成立的必要条件。相互验证原则是十分重要的，它贯穿于市场分析的始终。

更重要的是，在相关市场所组成的群类中，各个市场倾向于同步，因此我们必须探索一下与研究对象同属一个群类的其他市场的行为。如果我们分析的是某金属市场，那么也应当看看其他金属市场的情况如何。对其他市场的研究经常为我们的分析对象提供一些线索。

　　我们还可以考察我们的分析是否与商品市场的大方向一致。如果商品市场在总体上处于下降趋势中，对于任何个别市场的看涨分析，我们都需要把它的分量打些折扣。因此，我们必须明确，商品的总体环境到底是牛市还是熊市。
*** 投机原理
投机原理，所谓投机也就是我们的预期是否能够在市场中得到贴现，可以说市场中已经包含了我们对于市场的预期，我们的预期是市场中不可分割的组成部分，因此投机也是市场的成分之一。

在投机的定义中表明，投机的本质特征是主体(投资者)伪愿望能在客体(市场)中得到反应。如果市场所反应的是广大投资者的愿望，这才是我们真正意义上的市场投机行为；但如果投机行为反应的仅仅是政府或政策的愿望，这将可能反而给市场带来过度投机;而如果投机行为反应的是战争发动者的愿望，一定将会带来极限投机。因此，我们有必要分清市场投机行为与过度投机行为和极限投机行为的区别。
*** 道氏理论的五个“定理”
**** 定理一：道氏的三种走势(短期,中期,长期趋势)
股票指数与任何市场都有三种趋势:短期趋势,持续数天至数个星期;中期趋势,持续数个星期至数个月;长期趋势,持续数个月至数年。任何市场中,这三种趋势必然同时存在,彼此的方向可能相反。

　　长期趋势最为重要,也最容易被辨认,归类与了解。它是投资者主要的考量,对于投机者较为次要。中期与短期趋势都属于长期趋势之中,唯有明白他们在长期趋势中的位置,才可以充分了解他们,并从中获利。

　　中期趋势对于投资者较为次要,但却是投机者的主要考虑因素。它与长期趋势的方向可能相同,也可能相反。如果中期趋势严重背离长期趋势,则被视为是次级的折返走势或修正(correction)。次级折返走势必须谨慎评估,不可将其误认为是长期趋势的改变。

　　短期趋势最难预测,唯有交易者才会随时考虑它。投机者与投资者仅有在少数情况下,才会关心短期趋势:在短期趋势中寻找适当的买进或卖出时机,以追求最大的获利,或尽可能减少损失。
**** 定理二：主要走势（空头或多头市场）
主要走势(Primary Movements):主要走势代表整体的基本趋势,通常称为多头或空头市场,持续时间可能在一年以内,乃至于数年之久。正确判断主要走势的方向,是投机行为成功与否的最重要因素。没有任何已知的方法可以预测主要走势的持续期限。
**** 定理三：主要的空头市场（包含三个主要的阶段）
空头市场会历经三个主要的阶段: 第一阶段,市场参与者不再期待股票可以维持过度膨胀的价格;第二阶段的卖压是反映经济状况与企业盈余的衰退; 第三阶段是来自于健全股票的失望性卖压,不论价值如何,许多人急于求现至少一部分的股票。这项定义有几个层面需要理清。"重要的反弹"(次级的修正走势)是空头市场的特色,但不论是"工业指数",或 "运输指数",都绝对不会穿越多头市场的顶部,两项指数也不会同时穿越前一个中期走势的高点。"不利的经济因素" 是指(几乎毫无例外)政府行为的结果:干预性的立法,非常严肃的税务与贸易政策,不负责任的货币或(与)财政政策以及重要战争。

个人也曾经根据"道氏理论"将 1896 年至目前的市场指数加以归类,在此列举空头市场的某些特质:

　　1. 由前一个多头市场的高点起算,空头市场跌幅的平均数(median)为 29.4%,其中 75%的跌幅介于 20.4%至 47.1%之间。

　　2. 空头市场持续期限的平均数是 1.1 年,其中 75%的期间介于 0.8 年至 2.8 年之间。

　　3. 空头市场开始时,随后通常会以偏低的成交量"试探"前一个多头市场的高点,接着出现大量急跌的走势。所谓"试探"是指价格接近而绝对不会穿越前一个高点。"试探"期限,成交量偏低显示信心减退,很容易演变为"不再期待股票可以维持过度膨胀的价格"。

　　4. 经过一段相当程度的下跌之后,突然会出现急速上涨的次级折返走势,接着便形成小幅盘整而成交量缩小的走势, 但最后仍将下滑至新的低点。

　　5. 空头市场的确认日(confirmation date),是指两种市场指数都向下突破多头市场最近一个修正低点的日期。两种指数突破的时间可能有落差,并不是不正常的现象。

　　6. 空头市场的中期反弹,通常都呈现颠倒的"V-型",其中低价的成交量偏高,而高价的成交量偏低。有关空头市场的情况,雷亚的另一项观察非常值得重视:
**** 定理四：主要的多头市场(也有三个主要的阶段)
多头市场有三个阶段:第一阶段,人们对于未来的景气恢复信心;第二阶段,股票对于已知的公司盈余改善产生反应; 第三阶段,投机热潮转炽而股价明显膨涨--这阶段的股价上涨是基于期待与希望。

　　这项定义也需要理清。多头市场的特色是所有主要指数都持续联袂走高,拉回走势不会跌破前一个次级折返走势的低点,然后再继续上涨而创新高价。在次级的折返走势中,指数不会同时跌破先前的重要低点。主要多头市场的重要特质如下:

　　1. 由前一个空头市场的低点起算,主要多头市场的价格涨幅平均为 77.5%。

　　2. 主要多头市场的期间长度平均数为两年又四个月(2.33 年)。历史上的所有的多头市场中,75%的期间长度超过 657 天(1.8 年), 67%介于 1.8 年与 4.1 年之间。

　　3. 多头市场的开始,以及空头市场最后一波的次级折返走势,两者之间几乎无法区别,唯有等待时间确认。

　　4. 多头市场中的次级折返走势,跌势通常较先前与随后的涨势剧烈。另外,折返走势开始的成交量通常相当大,但低点的成交量则偏低。

　　5. 多头市场的确认日,是两种指数都向上突破空头市场前一个修正走势的高点,并持续向上挺升的日子。
**** 定理五：次级折返走势
次级折返走势(Second Reactions)：就此处的讨论来说,次级折返走势是多头市场中重要的下跌走势,或空头市场中重要的上涨走势,持续的时间通常在三个星期至数个月;此期间内折返的幅度为前一次级折返走势结束之后主要走势幅度的 33%至 66%。次级折返走势经常被误以为是主要走势的改变,因为多头市场的初期走势,显然可能仅是空头市场的次级折返走势,相反的情况则会发生在多头市场出现顶部后。
** 艾略特波浪理论(Elliott Wave Principle)
　波浪是指股票价格的波动,都与大自然的潮汐,波浪一样,一浪跟着一浪,周而复始,具有相当程度的规律性,以一种"可识别的模式"前进和反转,这些模式在形态上不断重复(不一定在时间和幅度上重复)。
*** 波浪理论的出发点
- 人类社会永远进步向前;
- 人类群体的行为是可以预测的
- 股市反映的就是人类的群体行为
*** 波浪理论的基础
五升三降是波浪理论的基础

艾略特指出股市呈一定的基本韵律和型态，五个上升波和三个下降波构成了八个波的完整循环。三个下降波作为前五个上升波之调整（Correction），图 2 表示五个代表上升方向的推进波（Impulse Waves）和三个调整波（Corrective Waves）。

波动原理有三个重要概念：波的型态、波幅比率、持续时间。其中最重要的是型态。波有两个基本型态：推进波 5－3-5-3-5 和调整波 5－3－5。

波浪形成的基本概念可总结如下：

　　1）一个运动之后必有相反运动发生；

　　2）主趋势上的推进波与主趋势方向相同，通常可分为更低一级的五个波；调整波与主趋势方向相反，或上升或下降．通常可分为更低一级的三个波。

　　3）八个波浪运动（五个上升，三个下降）构成一个循环，自然又形成上级波动的两个分支。

　　4）市场形态并不随时间改变。波浪时而伸展时而压缩，但其基本形态不变。

　　在实践中,每一个波浪并不是相等的，它可以压缩，可以延长，可以简单，可以复杂。总之，一切以型态为准。下面，提供几个较为典型的例子（如图 4）。
*** 波浪理论的四个基本特点
  （1）股价指数的上升和下跌将会交替进行；

　　（2）推动浪和调整浪是价格波动两个最基本型态，而推动浪（即与大市走向一致的波浪）可以再分割成五个小浪，一般用第１浪、第２浪、第３浪、第４浪、第５浪来表示，调整浪也可以划分成三个小浪，通常用Ａ浪、Ｂ浪、Ｃ浪表示。

　　（3）在上述八个波浪（五上三落）完毕之后，一个循环即告完成，走势将进入下一个八波浪循环；

　　（4）时间的长短不会改变波浪的形态，因为市场仍会依照其基本型态发展。波浪可以拉长，也可以缩细，但其基本型态永恒不变。

　　总之，波浪理论可以用一句话来概括：即"八浪循环"

如何区分三浪和五浪结构?
　　看这一浪与它的上一层次浪的运行趋势是否相同,如相同,则为五浪,不同则为三浪.
*** 艾略特波段理论内容的几个基本的要点：

　　①一个完整的循环包括八个波浪，五上三落。

　　②波浪可合并为高一级的浪，亦可以再分割为低一级的小浪。

　　③.跟随主流行走的波浪可以分割为低一级的五个小浪。

　　④1、3、5 三个波浪中，第 3 浪不可以是最短的一个波浪。

　　⑤假如三个推动论中的任何一个浪成为延伸浪，其余两个波浪的运行时间及幅度会趋一致。

　　⑥.调整浪通常以三个浪的形态运行。

　　⑦黄金分割率理论奇异数字组合是波浪理论的数据基础。

　　⑧经常遇见的回吐比率为 0.382、0.5 及 0.618。

　　⑨第四浪的底不可以低于第一浪的顶。

　　⑩艾略特波段理论包括三部分：型态、比率及时间，其重要性以排行先后为序。⑾艾略特波段理论主要反映群众心理。越多人参与的市场，其准确性越高。
** 江恩法则
[[wiki.mbalib.com/wiki/江恩十二条买卖规则][江恩十二条买卖规则]]
江恩认为，进行交易必须根据一套既定的交易规则去操作，而不能随意地买卖，盲目地猜测市场的发展情况。随着时间的转变，市场的条件也会跟随转变，投资者必须学会跟随市场的转变而转变，而不能认死理。

　江恩在十二条规则之上，建立了整个买卖的系统。基本上，所使的方法是纯粹技术性为主，而买卖方法是以跟随市势买卖为主，与他的预测预备完全不同。

　　1. 决定市场的走势；

　　2. 在单底、双底或三底水平入市买入；

　　3. 根据市场波动的百分比买卖；

　　4. 根据三星期上升或下跌买卖；

　　5. 市场分段波动；

　　6. 利用 5 或 7 点波动买卖；

　　7. 成交量；

　　8. 时间因素；

　　9. 当出现高低点或新高时买入；

　　10. 决定于大势趋势的转向；

　　11. 最安全的买卖点；

　　12. 快速市场的价位波动。


江恩二十一条买卖法则
   1、每次入市买、卖，损失不应超过资金的十分之一。

　　2、永远都设立止损位，减少买卖出错时可能造成的损失。

　　3、永不过量买卖。

　　4、永不让所持仓位转盈为亏。

　　5、永不逆市而为。市场趋势不明显时，宁可在场外观望。

　　6、有怀疑，即平仓离场。入市时要坚决，犹豫不决时不要入市。

　　7、只在活跃的市场买卖。买卖清淡时不宜操作。

　　8、永不设定目标价位出入市，避免限价出入市，而只服从市场走势。

　　9、如无适当理由、不将所持仓平盘，可用止赚位保障所得利润。

　　10、在市场连战皆捷后，可将部分利润提取，以备急时之需。

　　11、买股票切忌只望分红收息。(赚市场差价第一)

　　12、买卖遭损失时，切忌赌徒式加码，以谋求摊低成本。

　　13、不要因为不耐烦而入市，也不要因为不耐烦而平仓。

　　14、肯输不肯赢，切戒。赔多赚少的买卖不要做

　　15、入市时落下的止损位，不宜胡乱取消。

　　16、做多错多，入市要等候机会，不宜买卖太密。

　　17、做多做空自如，不应只做单边。

　　18、不要因为价位太低而吸纳，也不要因为价位太高而沽空。

　　19、永不对冲。

　　20、尽量避免在不适当时搞金字塔加码。

　　21、如无适当理由，避免胡乱更改所持股票的买卖策略。
* 主要分析方法
* 主要分析指标
[[http://www.360doc.com/content/08/1221/14/92483_2170536.shtml][详解 24 个经典股票技术指标]]
** 平滑异同移动平均线——MACD
*** 简介
收盘价的移动平均。
MACD 指标又叫指数平滑异同移动平均线，是由查拉尔·阿佩尔（Gerald Apple）所创造的,是一种研判股票买卖时机、跟踪股价运行趋势的技术分析工具。

该指标主要是利用长短期二条平滑平均线，计算两者之间的差离值。该指标可以去除掉移动平均线经常出现的假讯号，又保留了移动平均线的优点。但由于该指标对价格变动的灵敏度不高，属于中长线指标，所以在盘整行情中不适用。
*** 指标的原理
MACD 指标是根据均线的构造原理，对股票价格的收盘价进行平滑处理，求出算术平均值以后再进行计算，是一种趋向类指标。

MACD 指标主要是通过 EMA、DIF 和 DEA（或叫 MACD、DEM）这三值之间关系的研判，DIF 和 DEA 连接起来的移动平均线的研判以及 DIF 减去 DEM 值而绘制成的柱状图（BAR）的研判等来分析判断行情，预测股价中短期趋势的主要的股市技术分析指标。其中，DIF 是核心，DEA 是辅助。DIF 是快速平滑移动平均线（EMA1）和慢速平滑移动平均线（EMA2）的差。BAR 柱状图在股市技术软件上是用红柱和绿柱的收缩来研判行情。
*** 计算公式

#+BEGIN_SRC python
  以 EMA1 的参数为 12 日，EMA2 的参数为 26 日，DIF 的参数为 9 日为例来看看 MACD 的计算过程
  1、计算移动平均值（EMA）
  12 日 EMA 的算式为
  EMA（12）=前一日 EMA（12）×11/13＋今日收盘价×2/13
  26 日 EMA 的算式为
  EMA（26）=前一日 EMA（26）×25/27＋今日收盘价×2/27
  2、计算离差值（DIF）
  DIF=今日 EMA（12）－今日 EMA（26）
  3、计算 DIF 的 9 日 EMA
  根据离差值计算其 9 日的 EMA，即离差平均值，是所求的 MACD 值。为了不与指标原名相混淆，此值又名 DEA 或 DEM。
  今日 DEA（MACD）=前一日 DEA×8/10＋今日 DIF×2/10
  计算出的 DIF 和 DEA 的数值均为正值或负值。
#+END_SRC

*** 一般研判标准
MACD 指标的一般研判标准主要是围绕快速和慢速两条均线及红、绿柱线状况和它们的形态展开。一般分析方法主要包括 DIF 和 MACD 值及它们所处的位置、DIF 和 MACD 的交叉情况、红柱状的收缩情况和 MACD 图形的形态这四个大的方面分析。
一、DIF 和 MACD 的值及线的位置
1、当 DIF 和 MACD 均大于 0（即在图形上表示为它们处于零线以上）并向上移动时，一般表示为股市处于多头行情中，可以买入或持股；
2、当 DIF 和 MACD 均小于 0（即在图形上表示为它们处于零线以下）并向下移动时，一般表示为股市处于空头行情中，可以卖出股票或观望。
3、当 DIF 和 MACD 均大于 0（即在图形上表示为它们处于零线以上）但都向下移动时，一般表示为股票行情处于退潮阶段，股票将下跌，可以卖出股票和观望；
4、当 DIF 和 MACD 均小于 0 时（即在图形上表示为它们处于零线以下）但向上移动时，一般表示为行情即将启动，股票将上涨，可以买进股票或持股待涨。
二、DIF 和 MACD 的交叉情况
1、当 DIF 与 MACD 都在零线以上，而 DIF 向上突破 MACD 时，表明股市处于一种强势之中，股价将再次上涨，可以加码买进股票或持股待涨，这就是 MACD 指标“黄金交叉”的一种形式。
2、当 DIF 和 MACD 都在零线以下，而 DIF 向上突破 MACD 时，表明股市即将转强，股价跌势已尽将止跌朝上，可以开始买进股票或持股，这是 MACD 指标“黄金交叉”的另一种形式。
3、当 DIF 与 MACD 都在零线以上，而 DIF 却向下突破 MACD 时，表明股市即将由强势转为弱势，股价将大跌，这时应卖出大部分股票而不能买股票，这就是 MACD 指标的“死亡交叉”的一种形式。
4、当 DIF 和 MACD 都在零线以上，而 DIF 向下突破 MACD 时，表明股市将再次进入极度弱市中，股价还将下跌，可以再卖出股票或观望，这是 MACD 指标“死亡交叉”的另一种形式。
三、MACD 指标中的柱状图分析
1、当红柱状持续放大时，表明股市处于牛市行情中，股价将继续上涨，这时应持股待涨或短线买入股票，直到红柱无法再放大时才考虑卖出。
2、当绿柱状持续放大时，表明股市处于熊市行情之中，股价将继续下跌，这时应持币观望或卖出股票，直到绿柱开始缩小时才可以考虑少量买入股票。
3、当红柱状开始缩小时，表明股市牛市即将结束（或要进入调整期），股价将大幅下跌，这时应卖出大部分股票而不能买入股票。
4、当绿柱状开始收缩时，表明股市的大跌行情即将结束，股价将止跌向上（或进入盘整），这时可以少量进行长期战略建仓而不要轻易卖出股票。
5、当红柱开始消失、绿柱开始放出时，这是股市转市信号之一，表明股市的上涨行情（或高位盘整行情）即将结束，股价将开始加速下跌，这时应开始卖出大部分股票而不能买入股票。
6、当绿柱开始消失、红柱开始放出时，这也是股市转市信号之一，表明股市的下跌行情（或低位盘整）已经结束，股价将开始加速上升，这时应开始加码买入股票或持股待涨。
*** 特殊分析法
一、形态法则
1、M 头 W 底等形态
MACD 指标的研判还可以从 MACD 图形的形态来帮助研判行情。
当 MACD 的红柱或绿柱构成的图形双重顶底（即 M 头和 W 底）、三重顶底等形态时，也可以按照形态理论的研判方法来加以分析研判。例如：
2、顶背离和底背离
MACD 指标的背离就是指 MACD 指标的图形的走势正好和 K 线图的走势方向正好相反。MACD 指标的背离有顶背离和底背离两种。
（1）顶背离
当股价 K 线图上的股票走势一峰比一峰高，股价一直在向上涨，而 MACD 指标图形上的由红柱构成的图形的走势是一峰比一峰低，即当股价的高点比前一次的高点高、而 MACD 指标的高点比指标的前一次高点低，这叫顶背离现象。顶背离现象一般是股价在高位即将反转转势的信号，表明股价短期内即将下跌，是卖出股票的信号。
（2）底背离
底背离一般出现在股价的低位区。当股价 K 线图上的股票走势，股价还在下跌，而 MACD 指标图形上的由绿柱构成的图形的走势是一底比一底高，即当股价的低点比前一次低点底，而指标的低点却比前一次的低点高，这叫底背离现象。底背离现象一般是预示股价在低位可能反转向上的信号，表明股价短期内可能反弹向上，是短期买入股票的信号。
在实践中，MACD 指标的背离一般出现在强势行情中比较可靠，股价在高价位时，通常只要出现一次背离的形态即可确认位股价即将反转，而股价在低位时，一般要反复出现几次背离后才能确认。因此，MACD 指标的顶背离研判的准确性要高于底背离，这点投资者要加以留意。
3、趋势线、压力线
二、分析周期法则
绿柱状间隔时间越长，未来上涨力度越大和时间越长
红柱状维持时间越长，未来下跌空间和力度越大，时间越长
*** 实战技巧
使用方法：
DIF 与 DEA 均为正值时，大势属多头市场，DIF 与 DEA 均为负值时，大势属空头市场，DIF 向上突破 DEA 时，可买进，DIF 向下突破 DEA 时，应卖出。
MACD 指标的实战技巧主要集中在 MACD 指标的“金叉”、“死叉”以及 MACD 指标中的红、绿柱状线的情况等两大方面。下面以分析家软件上的日参数为（26，52，52）的 MACD 指标来揭示 MACD 指标的买卖和观望功能。（注：MACD 指标在钱龙软件和分析家软件上指标参数选取及使用方法一样）。
一、买入信号
（一）DIF 线和 MACD 线的交叉情况分析
1、0 值线以下区域的弱势“黄金交叉”
当 MACD 指标中的 DIF 线和 MACD 线在远离 0 值线以下区域同时向下运行很长一段时间后，当 DIF 线开始进行横向运行或慢慢勾头向上靠近 MACD 线时，如果 DIF 线接着向上突破 MACD 线，这是 MACD 指标的第一种“黄金交叉”。它表示股价经过很长一段时间的下跌，并在低位整理后，一轮比较大的跌势后、股价将开始反弹向上，是短线买入信号。对于这一种“黄金交叉”，只是预示着反弹行情可能出现，并不表示该股的下跌趋势已经结束，股价还有可能出现反弹行情很快结束、股价重新下跌的情况，因此，投资者应谨慎对待，在设置好止损价位的前提下，少量买入做短线反弹行情。如图（7–1）所示。
2、0 值线附近区域的强势“黄金交叉”
当 MACD 指标中的 DIF 线和 MACD 线都运行在 0 值线附近区域时，如果 DIF 线在 MACD 线下方、由下向上突破 MACD 线，这是 MACD 指标的第二种“黄金交叉 ”。它表示股价在经过一段时间的涨势、并在高位或低位整理后，股价将开始一轮比较大的上涨行情，是中长线买入信号。它可能就预示着股价的一轮升幅可观的上涨行情将很快开始，这是投资者买入股票的比较好的时机。对于这一种“黄金交叉”，投资者应区别对待。
﹝1﹞当股价是在底部小幅上升，并经过了一段短时间的横盘整理，然后股价放量向上突破、同时 MACD 指标出现这种金叉时，是长线买入信号。此时，投资者可以长线逢低建仓。
﹝2﹞当股价是从底部启动、已经出现一轮涨幅比较大的上升行情，并经过上涨途中的比较长时间的中位回档整理, 然后股价再次调头向上扬升、同时 MACD 指标出现这种金叉时,是中线买入信号。
3、0 值线以上区域的一般“黄金交叉”
当 MACD 指标中的 DIF 线和 MACD 线都运行在 0 值线以上区域时，如果 DIF 线在 MACD 线下方调头、由下向上突破 MACD 线，这是 MACD 指标的第二种“黄金交叉”。它表示股价经过一段时间的高位回档整理后，新的一轮涨势开始，是第二个买入信号。此时，激进型投资者可以短线加码买入股票；稳健型投资者则可以继续持股待涨。
（二）柱状线分析
1、红色柱状线
红色柱状线的放出，表明市场上的多头力量开始强于空头力量，股价将开始一轮新的涨升行情，是一种比较明显的买入信号。对于这种买入信号，投资者也应从三个方面进行分析。
（1）当 DIF 线和 MACD 线都在 0 值线以上区域运行，说明股市是处于多头行情中，股价将继续上涨。当 MACD 指标在 0 值线上方经过短暂的回调整理后，红柱状线再次放出时，投资者可继续持股做多，空仓者可逢低买入。
（2）当 DIF 线和 MACD 线都在 0 值线以下区域运行，说明股市处于空头行情中，股价将继续下跌探底。当 MACD 指标中的绿柱线经过很长一段时间的低位运行，然后慢慢收缩后，如果红柱状线出现时表明股价可能出现反弹但中长期下跌趋势并没有完全改变。此时，激进型投资者可以在设置好止损点的前提下短线少量买入股票；稳健型投资者则可以继续持币观望。
（3）当 DIF 线和 MACD 线都在 0 值线以下区域运行，但这两条线在低位经过一次“黄金交叉”后，其运行方向开始同时向上并越来越向上靠近 0 值线时，如果此时红柱状线开始放出（特别是第二次放出），表明股价经过长时间的整理后，下跌趋势已经结束，股价在大量买盘的推动下将开始一轮新的上升行情。这也是投资者中长线买入股票的一个较好时机。此时，投资者应及时买入股票或持股待涨。
（三）MACD 指标的双底分析
当 MACD 指标中的 DIF 线和 MACD 线在 0 值线附近运行了很长一段时间后，绿色柱状线构成一底比一底高的双底形态时，表明股价的长期下跌趋势可能结束，股价将在成交量的配合下,开始一轮新的中长期上升行情。此时，投资者可以开始逢低分批建仓。

二、卖出信号
（一）DIF 线和 MACD 线的交叉情况分析
1、0 值线以上区域的强势“死亡交叉”
当 MACD 指标中的 DIF 线和 MACD 线在远离 0 值线以区域同时向上运行很长一段时间并向上远离 0 值线后，当 DIF 线开始进行横向运行或慢慢勾头向下靠近 MACD 线时，如果 DIF 线接着向下突破 MACD 线，这是 MACD 指标的第一种“死亡交叉”。它表示股价经过很长一段时间的上涨行情，并在高位横盘整理后，一轮比较大的跌势将展开。对于这一种“死亡交叉”，预示着股价的中长期上升行情结束，该股的另一个下跌趋势已可能开始，股价将可能展开一段时间较长的跌势，因此，投资者对于 MACD 指标的这种“死亡交叉”应格外警惕，应及时逢高卖出全部或大部分股票，特别是对于那些前期涨幅过高的股票更要加倍小心。
2、0 值线以下区域的弱势“死亡交叉”
当 MACD 指标中的 DIF 线和 MACD 线在远离 0 值线以下区域运行很长一段时间后，由于 DIF 线的走势领先于 MACD 线，因此，当 DIF 线再次开始慢慢调头向下靠近 MACD 线时，如果 DIF 线接着向下突破 MACD 线，这是 MACD 指标的另一种“死亡交叉”。它表示股价在长期下跌途中的一段时间的反弹整理后，一轮比较大的跌势又要展开，股价将再次下跌，是短线卖出信号。对于这种“死亡交叉”，它意味着下跌途中的短线反弹结束，股价的中长期趋势依然看淡，投资者应以逢高卖出剩余的股票或持币观望为主。
（二）柱状线分析
1、红色柱状线
红色柱状线的收缩，表明市场上的多头力量开始强于空头力量，股价将开始一轮新的下跌行情，是一种比较明显的卖出信号。对于这种卖出信号，投资者也应从三个方面进行分析。
（1）当 DIF 线和 MACD 线都在 0 值线以上区域运行时，一旦红柱状线开始无法放大并慢慢收缩时，说明股价的涨势已接近尾声，股价短期将面临调整但仍处于强势行情中。对于这种情况的出现，稳健型的投资者可先暂时短线获利了解，待股价运行趋势明朗后再做决策；而激进型的投资者可继续持股观望。
（2）当 DIF 线和 MACD 线都在 0 值线附近区域运行时，一旦红柱线消失，说明股价的上升行情已经结束，一轮中长线下跌行情即将展开。对于这种情况的出现，投资者应尽早中长线清仓离场，特别是 DIF 线和 MACD 线也同时向下运行时，更应果断离场。
（3）当 DIF 线和 MACD 线都在 0 值线以下区域运行时，如果 MACD 指标中的红柱线再次短暂放出后又开始收缩，则表明股价长期下跌途中的短暂反弹将结束，空方力量依然强大，投资者还应看空、做空，抢反弹的投资者应尽快离场。
（三）MACD 指标的双顶分析
当 MACD 指标中的 DIF 线和 MACD 线在 0 值线以上运行了很长一段时间后，红色柱状线构成一顶比一底顶低的双顶形态时，表明股价的长期上升趋势可能结束，股价将开始一轮新的中长期下跌行情。此时，投资者应及时逢高卖出股票。
三、持股待涨信号

（一）DIF 线和 MACD 线的运行方向分析

1、当 DIF 线和 MACD 线在 0 值线以上区域同时向上运行时，表明多方力量强于空方，股价处于一段上升行情之中，只要 DIF 线没有向下突破 MACD 线，投资者就可一路持股待涨或逢低买入。

2、当 DIF 线和 MACD 线在 0 值线以上区域运行，但由于 DIF 线领先于 MACD 线，如果 DIF 线开始向下运行并逐渐靠拢 MACD 线时，表明多空力量开始趋向平衡，股价面临短线回档整理的压力。对于这种情况的出现，投资者应小心操作、区别对待。只要 DIF 线没有有效向下突破 MACD 线，仍然可以持股待涨、直至 DIF 线向下有效突破 MACD 线、并同时向下运行后，便应及时卖出。

3、当 DIF 线和 MACD 线在 0 值线以下区域但同时向上运行时，表明多方力量开始慢慢积聚，股价处于一段慢慢的反弹恢复行情之中。对于这种情况的出现，激进型投资者可以开始少量逢低吸纳，短线持股待涨、做反弹行情。

（二）柱状线分析

1、当 DIF 线和 MACD 线在 0 值线以上区域运行时，如果 MACD 指标中的红柱线依然增多拉长时，表明多方力量强于空方力量，股价处于一种强势上升的行情之中，投资者应坚决持股待涨。

2、当 DIF 线和 MACD 线在 0 值线以下区域时，如果 MACD 指标中的红柱线开始放出并逐渐放大、并且 MACD 线和 DIF 线都同时向上运行时，表明多头力量在缓慢增长，激进型的投资者可以中长线逢低建仓并持股待涨。

3、当 DIF 线和 MACD 线在 0 值线以上区域运行时，如果 MACD 指标的绿柱线经过一段短时间的中位运行后再慢慢减少收缩时，表明多方的力量重新积聚，股价经过小幅高位整理后将再次企稳上攻。投资者也应短线持股待涨。

四、持币观望信号

（一）DIF 线和 MACD 线的运行方向分析

1、当 DIF 线和 MACD 线在 0 值线以上区域，但它们的运行方向都同时向下时，表明空方力量开始增大，股价上升行情可能结束，投资者应持币观望、不可盲目买入股票。特别是对于那些近期涨幅过高的股票。

2、当 DIF 线和 MACD 线在 0 值线以下区域、而且它们的运行方向也是同时向下时，表明空方力量过于强大，股价的下跌行情依然继续，此时，投资者更应坚决持币观望、尽量不做反弹行情。

（二）柱状线分析

1、当 DIF 线和 MACD 线在 0 值线以上区域运行时，如果 MACD 指标中的红柱线开始收缩并逐渐消失时，表明多方力量可能衰竭，股价随时反转向下，此时，投资者应以持币观望为主。

2、当 DIF 线和 MACD 线在 0 值线以上区域运行时，如果 MACD 指标中的绿柱线开始放出并逐渐增大拉长时，表明多方力量已经衰竭，空方力量逐渐强大，股价的下跌行情已经展开，此时，投资者应坚决持币观望。当 DIF 线和 MACD 线在 0 值线以上区域运行时，如果 MACD 指标中的绿柱线在依次向下拉大增强时，表明空方力量过于强大，股价将跌势依旧，此时，投资者也应坚决持币观望。

3、当 DIF 线和 MACD 线在 0 值线以下区域运行时，如果股价经过一轮短时间小幅反弹行情后，MACD 指标中的红柱线再次收缩并消失时，表明空方力量依然强大，股价再次反转向下，此时，投资者也应以持币观望为主。
** 随机指标——KDJ
*** 简介
收盘价在最高价和最低价之间所占的位置。
KDJ 指标又叫随机指标，是由乔治·蓝恩博士（George Lane）最早提出的，是一种相当新颖、实用的技术分析指标，它起先用于期货市场的分析，后被广泛用于股市的中短期趋势分析，是期货和股票市场上最常用的技术分析工具。
*** KDJ 指标的原理
随机指标 KDJ 一般是根据统计学的原理，通过一个特定的周期（常为 9 日、9 周等）内出现过的最高价、最低价及最后一个计算周期的收盘价及这三者之间的比例关系，来计算最后一个计算周期的未成熟随机值 RSV，然后根据平滑移动平均线的方法来计算 K 值、D 值与 J 值，并绘成曲线图来研判股票走势。

随机指标 KDJ 最早是以 KD 指标的形式出现，而 KD 指标是在威廉指标的基础上发展起来的。不过威廉指标只判断股票的超买超卖的现象，在 KDJ 指标中则融合了移动平均线速度上的观念，形成比较准确的买卖信号依据。在实践中，K 线与 D 线配合 J 线组成 KDJ 指标来使用。由于 KDJ 线本质上是一个随机波动的观念，故其对于掌握中短期行情走势比较准确。
*** KDJ 计算公式

#+BEGIN_SRC pseudocode
  首先要计算周期（n 日、n 周等）的 RSV 值，即未成熟随机指标值，然后再计算 K 值、D 值、J 值等。以日 KDJ 数值的计算为例，其计算公式为:
  n 日 RSV=（Cn－Ln）÷（Hn－Ln）×100
  式中，Cn 为第 n 日收盘价；Ln 为 n 日内的最低价；Hn 为 n 日内的最高价。RSV 值始终在 1—100 间波动。

  其次，计算 K 值与 D 值：
  当日 K 值=2/3×前一日 K 值＋1/3×当日 RSV
  当日 D 值=2/3×前一日 D 值＋1/3×当日 K 值
  若无前一日 K 值与 D 值，则可分别用 50 来代替。

  以 9 日为周期的 KD 线为例。首先须计算出最近 9 日的 RSV 值，即未成熟随机值，计算公式为
  9 日 RSV=（C－L9）÷（H9－L9）×100
  式中，C 为第 9 日的收盘价；L9 为 9 日内的最低价；H9 为 9 日内的最高价。
  K 值=2/3×前一日 K 值＋1/3×当日 RSV
  D 值=2/3×前一日 K 值＋1/3×当日 RSV
  若无前一日 K 值与 D 值，则可以分别用 50 代替。

  需要说明的是，式中的平滑因子 1/3 和 2/3 是可以人为选定的,不过目前已经约定俗成，固定为 1/3 和 2/3。在大多数股市分析软件中，平滑因子已经被设定为 1/3 和 2/3，不需要作改动。另外，一般在介绍 KD 时，往往还附带一个 J 指标。
  J 指标的计算公式为：
  J=3D—2K
  实际上，J 的实质是反映 K 值和 D 值的乖离程度，从而领先 KD 值找出头部或底部。J 值范围可超过 100。
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 相对强弱指标——RSI
*** 简介
相对强弱指标 RSI 又叫力度指标，其英文全称为“Relative Strength Index”，由威尔斯·魏尔德﹝Welles Wilder﹞所创造的，是目前股市技术分析中比较常用的中短线指标。
*** 指标的原理
相对强弱指标 RSI 是根据股票市场上供求关系平衡的原理，通过比较一段时期内单个股票价格的涨跌的幅度或整个市场的指数的涨跌的大小来分析判断市场上多空双方买卖力量的强弱程度，从而判断未来市场走势的一种技术指标。

从它构造的原理来看，与 MACD、TRIX 等趋向类指标相同的是，RSI 指标是对单个股票或整个市场指数的基本变化趋势作出分析，而与 MACD、TRIX 等不同的是，RSI 指标是先求出单个股票若干时刻的收盘价或整个指数若干时刻收盘指数的强弱，而不是直接对股票的收盘价或股票市场指数进行平滑处理。

相对强弱指标 RSI 是一定时期内市场的涨幅与涨幅加上跌幅的比值。它是买卖力量在数量上和图形上的体现，投资者可根据其所反映的行情变动情况及轨迹来预测未来股价走势。在实践中，人们通常将其与移动平均线相配合使用，借以提高行情预测的准确性。
*** 计算公式

#+BEGIN_SRC 
相对强弱指标 RSI 的计算公式有两种
其一：
假设 A 为 N 日内收盘价的正数之和，B 为 N 日内收盘价的负数之和乘以（—1）
这样，A 和 B 均为正，将 A、B 代入 RSI 计算公式，则
RSI（N）=A÷（A＋B）×100

其二：
RS（相对强度）=N 日内收盘价涨数和之均值÷N 日内收盘价跌数和之均值
RSI（相对强弱指标）=100－100÷（1+RS）
这两个公式虽然有些不同，但计算的结果一样。

以 14 日 RSI 指标为例，从当起算，倒推包括当日在内的 15 个收盘价， * 以每一日的收盘价减去上一日的收盘价 *，得到 14 个数值，这些数值有正有负。这样，RSI 指标的计算公式具体如下：
A=14 个数字中正数之和
B=14 个数字中负数之和乘以（—1）
RSI（14）=A÷（A＋B）×100
式中：A 为 14 日中股价向上波动的大小
B 为 14 日中股价向下波动的大小
A＋B 为股价总的波动大小
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 成交量比率指标——VR
*** 简介
VR 指标又叫成交率比率指标、数量指标或容量指标，其英文全称为“Volume Ratio”,是重点研究量与价格间的关系的一种短期技术分析工具。
*** 指标的原理
VR 指标是以研究股票量与价格之间的关系为手段的技术指标，其理论基础是“量价理论”和“反市场操作理论”。VR 指标认为，由于量先价行、量涨价增、量跌价缩、量价同步、量价背离等成交量的基本原则在市场上恒久不变，因此，观察上涨与下跌的成交量变化，可作为研判行情的依据。同时，VR 指标又认为，当市场上人气开始凝聚，股价刚开始上涨和在上涨途中的时候，投资者应顺势操作，而当市场上人气极度旺盛或极度悲观，股价暴涨暴跌时候，聪明的投资者应果断离场或进场，因此，反市场操作也是 VR 指标所显示的一项功能。

一般而言，低价区和高价区出现的买卖盘行为均可以通过成交量表现出来，因此。VR 指标又带有超买超卖的研判功能。同时，VR 指标是用上涨时期的量除以下跌时期的量，因此，VR 指标又带有一种相对强弱概念。

总之，VR 指标可以通过研判资金的供需及买卖气势的强弱、设定超买超卖的标准，为投资者确定合理、及时的买卖时机提供正确的参考。

*** 计算公式

#+BEGIN_SRC pseudocode
（1）N 日以来股价上涨的那一日的成交量都称为 UV，将 N 日内的 UV 总和相加称为 UVS。

（2）N 日以来股价下跌的那一日的成交量都称为 DV，将 N 日内的 DV 总和相加称为 DVS。

（3）N 日以来股价平盘的那一日的成交量都称为 PV，将 N 日内的 PV 总和相加称为 PVS。

（4）最后 N 日的 VR 就可以计算出来

VR（N）=（UVS＋1/2PVS）÷（DVS＋1/2PVS）
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 趋向指标——DMI
*** 简介
DMI 指标又叫动向指标或趋向指标，其全称叫“Directional Movement Index,简称 DMI”，也是由美国技术分析大师威尔斯·威尔德（Wells Wilder）所创造的，是一种中长期股市技术分析方法。

必须注意，当市场的上升（下跌）趋势非常明显时，利用该指标进行买卖指导效果较好，当市场处于盘整时，该指标会失真。
*** 指标的原理
DMI 指标的基本原理是在于寻找股票价格涨跌过程中，股价藉以创新高价或新低价的功能，研判多空力量，进而寻求买卖双方的均衡点及股价在双方互动下波动的循环过程。

在大多数指标中，绝大部分都是以每一日的收盘价的走势及涨跌幅的累计数来计算出不同的分析数据，其不足之处在于忽略了每一日的高低之间的波动幅度。比如某个股票的两日收盘价可能是一样的，但其中一天上下波动的幅度不大，而另一天股价的震幅却在 10%以上，那么这两日的行情走势的分析意义决然不同，这点在其他大多数指标中很难表现出来。而 DMI 指标则是把每日的高低波动的幅度因素计算在内，从而更加准确的反应行情的走势及更好的预测行情未来的发展变化。

*** 计算公式
DMI 指标的计算方法和过程比较复杂，它涉及到 DM、TR、DX 等几个计算指标和+DI（即 PDI，下同）、﹣DI（即 MDI，下同）、ADX 和 ADXR 等 4 个研判指标的运算。

#+BEGIN_SRC pseudocode
1. 计算当日动向值
  上升动向： +DM=今天最高—昨天最高价之差  （差值≤0，则记成 0）   
  下降动向： —DM=昨天最低—今天最低价之差  （差值≤0，则记成 0）  
  无动向：  1). +DM， -DM 同时为 0. 2). 上升动向值正好等于下降动向值.

  +DM7=7 天的+DM1 值总合  —DM7=7 天的—DM1 值总合

2. 计算真实波幅（TR）
  TR 代表真实波幅，是当日价格较前一日价格的最大变动值。

  A、当日的最高价减去当日的最低价的价差。
  B、当日的最高价减去前一日的收盘价的价差。
  C、当日的最低价减去前一日的收盘价的价差。
  TR 是 A、B、C 中的数值最大者

  TR7=7 天的 TR1 总合

3. 计算方向线 DI 
  方向线 DI 是衡量股价上涨或下跌的指标，分为“上升指标”和“下降指标”。在有的股市分析软件上，+DI 代表上升方向线，﹣DI 代表下降方向线。其计算方法如下：

  +DI=（DM÷TR）×100

  ﹣DI=（﹣DM÷TR）×100

  要使方向线具有参考价值，则必须运用平滑移动平均的原理对其进行累积运算。以 12 日作为计算周期为例，先将 12 日内的+DM、﹣DM 及 TR 平均化，所得数值分别为+DM12，﹣DM12 和 TR12，具体如下：

  +DI（12）=（+DM12÷TR12）×100

  ﹣DI（12）=（﹣DM12÷TR12）×100

  随后计算第 13 天的+DI12、﹣DI12 或 TR12 时，只要利用平滑移动平均公式运算即可。
  例如：
  当日的 TR12=11/12÷前一日 TR12＋当日 TR
  上升或下跌方向线的数值永远介于 0 与 100 之间。

4. 计算动向平均数 ADX
  依据 DI 值可以计算出 DX 指标值。其计算方法是将+DI 和—DI 间的差的绝对值除以总和的百分比得到动向指数 DX。由于 DX 的波动幅度比较大，一般以一定的周期的平滑计算，得到平均动向指标 ADX。具体过程如下：

  DX=(DI DIF÷DI SUM) ×100

  其中，DI DIF 为上升指标和下降指标的价差的绝对值

  DI SUM 为上升指标和下降指标的总和

  ADX 就是 DX 的一定周期 n 的移动平均值。
5. 计算评估数值 ADXR
  在 DMI 指标中还可以添加 ADXR 指标，以便更有利于行情的研判。

  ADXR 的计算公式为：

  ADXR=（当日的 ADX＋前一日的 ADX）÷2
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 中间意愿指标——CR
*** 简介
CR 指标又叫中间意愿指标，它和 AR、BR 指标又很多相似之处，但更有自己独特的研判功能，是分析股市多空双方力量对比、把握买卖股票时机的一种中长期技术分析工具。
*** 指标的原理
CR 指标同 AR、BR 指标有很多相似的地方，如计算公式和研判法则等，但它与 AR、BR 指标最大不同的地方在于理论的出发点有不同之处。CR 指标的理论出发点是：中间价是股市最有代表性的价格.

CR 指标不但能够测量人气的热度、价格动量的潜能，而且能够显示出股价的压力带和支撑带，为分析预测股价未来的变化趋势，判断买卖股票的时机提供重要的参考。
*** 计算公式
由于选用的计算周期不同，CR 指标也包括日 CR 指标、周 CR 指标、月 CR 指标、年 CR 指标以及分钟 CR 指标等很多种类型。经常被用于股市研判的是日 CR 指标和周 CR 指标。虽然它们计算时取值有所不同，但基本的计算方法一样。

#+BEGIN_SRC pseudocode
  以日 CR 指标为例，其计算公式为：
  CR（N 日）=P1÷P2×100
  式中，P1=∑（H－YM），表示 N 日以来多方力量的总和
  P2=∑（YM－L），表示 N 日以来空方力量的总和
  H 表示今日的最高价，L 表示今日的最低价
  YM 表示昨日（上一个交易日）的中间价

  目前比较常用地中间价计算方法有四种：

  1、M=（2C+H+L）÷4
  2、M=（C+H+L+O）÷4
  3、M=（C+H+L）÷3
  4、M=（H+L）÷2
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 平行线差指标——DMA
*** 简介
DMA 指标又叫平行线差指标，是目前股市分析技术指标中的一种中短期指标，它常用于大盘指数和个股的研判。

*** 指标的原理
DMA 指标是属于趋向类指标，也是一种趋势分析指标。DMA 是依据快慢两条移动平均线的差值情况来分析价格趋势的一种技术分析指标。它主要通过计算两条基准周期不同的移动平均线的差值，来判断当前买入卖出的能量的大小和未来价格走势的趋势。
*** 计算公式

#+BEGIN_SRC pseudocode
DMA 指标的计算方法比较简单，其计算过程如下：
DMA=短期平均值—长期平均值
AMA=短期平均值
以求 10 日、50 日为基准周期的 DMA 指标为例，其计算过程具体如下：
DMA（10）=10 日平均值—50 日平均值
AMA（10）=10 日平均值
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 能量潮指标——OBV
*** 简介
OBV 指标又叫能量潮指标，是由美国股市分析家葛兰碧本世纪 60 年代所创造的，是一种重点研判股市成交量的短期技术分析工具。
*** 指标的原理
股市技术分析的四大要素：价、量、时、空。OBV 指标就是从“量”这个要素作为突破口，来发现热门股票、分析股价运动趋势的一种技术指标。它是将股市的人气——成交量与股价的关系数字化、直观化，以股市的成交量变化来衡量股市的推动力，从而研判股价的走势。关于成交量方面的研究，OBV 能量潮指标是一种相当重要的分析指标之一。

OBV 指标由 OBV 值和 OBV 线构成的。OBV 线方法是葛兰碧又一大贡献。他将“量的平均”概念加以延伸，认为成交量是股市的元气，股价只不过是它的表象特征而已。因此，成交量通常比股价先行。这种“先见量、后见价”的理论早已为股市所证明。

能量潮理论成立的依据重要是：
1、投资者对股价的评论越不一致，成交量越大；反之，成交量就小。因此，可用成交量来判断市场的人气和多空双方的力量。

2、重力原理。上升的物体迟早会下跌，而物体上升所需的能量比下跌时多。涉及到股市则可解释为：一方面股价迟早会下跌；另一方面，股价上升时所需的能量大，因此股价的上升特别是上升初期必须有较大的成交量相配合；股价下跌时则不必耗费很大的能量，因此成交量不一定放大，甚至有萎缩趋势。

3、惯性原则——动则恒动、静则恒静。只有那些被投资者或主力相中的热门股会在很大一段时间内成交量和股价的波动都比较大，而无人问津的冷门股，则会在一段时间内，成交量和股价波幅都比较小。

*** 计算公式
#+BEGIN_SRC pseudocode
今日 OBV=昨天 OBV+sgn×今天的成交量  
其中 sgn 是符号的意思，sgn 可能是+1，也可能是-1，这由下式决定。
Sgn=+1 今收盘价≥昨收盘价  Sgn=—1 今收盘价<昨收盘价.   
成交量指的是成交股票的手数，不是成交金额。
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 人气和买卖意愿指标——AR、BR
*** 简介
AR 指标又叫人气指标,BR 指标又叫买卖意愿指标，它们是衡量市场上多空双方力量对比变化的最重要指标。它们既可以单独使用，更多情况下是一同使用，是一种中长期技术分析工具。
*** 指标的原理
如果一定时期内多方力量占据优势，股价将会不断上升；如果一定时期内空方力量占据优势，股价则会不断下跌；多空双方力量如果大致平衡，股价在会在某一区域内窄幅波动。而市场上多方力量大，则买方气势就会比较强、卖方气势就会减弱；市场上空方力量大，则卖方气势就会比较强、买方气势就会衰弱。

正如每个事物都有一个开始的地方一样，在股票市场上，多空双方的争斗都是从某一个均衡价位区（或基点）开始的。股价在这个均衡区上方，说明多方力量占优势；股价在这个平衡区下方，说明空方力量占优势。

AR、BR 指标就是根据股票的开盘价、收盘价、最高价和最低价之间的关系来分析多空力量的对比，预测股价的未来走势的。

AR 指标是通过比较一段周期内的开盘价在该周期价格中的高低。从而反映市场买卖人气的技术指标。

BR 指标是通过比较一段周期内的收盘价在该周期价格波动中的地位，来反映市场买卖意愿程度的技术指标。
*** 计算公式
#+BEGIN_SRC pseudocode
AR 指标的计算方法:
N 日 AR=N 日内（H－O）之和除以 N 日内（O－L）之和.
其中，H 为当日最高价，L 为当日最低价，O 为当日收盘价，N 为设定的时间参数，一般原始参数日设定为 26 日

BR 指标的计算方法:
N 日 BR=N 日内（H－CY）之和除以 N 日内（CY－L）之和.
其中，H 为当日最高价，L 为当日最低价，CY 为前一交易日的收盘价，N 为设定的时间参数，一般原始参数日设定为 26 日。
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 三重指数平滑移动平均指标——TRIX
*** 简介
指标又叫三重指数平滑移动平均指标，其英文全名为“Triple Exponentially Smoothed Average”，是一种研究股价趋势的长期技术分析工具。

*** 指标的原理
TRIX 指标是根据移动平均线理论，对一条平均线进行三次平滑处理，再根据这条移动平均线的变动情况来预测股价的长期走势。

与 TRMA 等趋向类指标一样，TRIX 指标一方面忽略价格短期波动的干扰，除去移动平均线频繁发出假信号的缺陷，以最大可能地减少主力“骗线行为”的干扰，避免由于交易行为过于频繁而造成较大交易成本的浪费，二则保留移动平均线的效果，凸现股价未来长期运动趋势，使投资者对未来较长时间内股价运动趋势有个直观、准确地了解，从而降低投资者深度套牢和跑丢“黑马”的风险。
*** 计算公式

#+BEGIN_SRC pseudocode
1、计算 N 天的收盘价的指数平均 AX

AX=（I 日）收盘价×2÷（N＋1）＋（I－1）日 AX（N－1）×（N＋1）

2、计算 N 天的 AX 的指数平均 BX

BX=（I 日）AX×2÷（N＋1）＋（I－1）日 BX（N－1）×（N＋1）

3、计算 N 天的 BX 的指数平均 TRIX

TRIX=（I 日）BX×2÷（N＋1）＋（I－1）日 TAIX（N－1）×（N＋1）

4、计算 TRIX 的 m 日移动平均 TRMA

TRMA=＜（I－M）日的 TRIX 累加＞÷M
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 顺势指标——CCI
*** 简介
CCI 指标又叫顺势指标，其英文全称为“Commodity Channel Index”，是由美国股市分析家唐纳德·蓝伯特（Donald Lambert）80 年代所创造的，是一种重点研判股价偏离度的股市分析工具。
*** 指标的原理
与大多数单一利用股票的收盘价、开盘价、最高价或最低价而发明出的各种技术分析指标不同，CCI 指标是根据统计学原理，引进价格与固定期间的股价平均区间的偏离程度的概念，强调股价平均绝对偏差在股市技术分析中的重要性，是一种比较独特的技术分析指标。

CCI 指标是专门衡量股价是否超出常态分布范围，属于超买超卖类指标的一种,但它与其他超买超卖型指标又有自己比较独特之处。象 KDJ、WR%、CCI 等大多数超买超卖型指标都有“0——100”上下界限，因此，它们对待一般常态行情的研判比较适用，而对于那些短期内暴涨暴跌的股票的价格走势时，就可能会发生指标钝化的现象。而 CCI 指标却是波动于正无穷大到负无穷大之间，因此不会出现指标钝化现象，这样就有利于投资者更好地研判行情，特别是那些短期内暴涨暴跌的非常态行情。
*** 计算公式
#+BEGIN_SRC pseudocode
以日 CCI 计算为例，其计算方法有两种。

第一种计算过程如下：
CCI（N 日）=（TP－MA）÷MD÷0.015
其中，TP=（最高价+最低价+收盘价）÷3
MA=最近 N 日收盘价的累计之和÷N
MD=最近 N 日（MA－收盘价）的累计之和÷N
0.015 为计算系数，N 为计算周期

第二种计算方法表述为
中价与中价的 N 日内移动平均的差除以 N 日内中价的平均绝对偏差
其中，中价等于最高价、最低价和收盘价之和除以 3
平均绝对偏差为统计函数
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 布林线指标——BOLL
*** 简介
BOLL 指标又叫布林线指标，其英文全称是“Bolinger Bands”，是用该指标的创立人﹝约翰·布林﹞的姓来命名的，是研判股价运动趋势的一种中长期技术分析工具。
*** 指标的原理
BOLL 指标是美国股市分析家约翰·布林根据统计学中的标准差原理设计出来的一种非常简单实用的技术分析指标。一般而言，股价的运动总是围绕某一价值中枢（如均线、成本线等）在一定的范围内变动，布林线指标指标正是在上述条件的基础上，引进了“股价通道”的概念，其认为股价通道的宽窄随着股价波动幅度的大小而变化，而且股价通道又具有变异性，它会随着股价的变化而自动调整。正是由于它具有灵活性、直观性和趋势性的特点，BOLL 指标渐渐成为投资者广为应用的市场上热门指标。

在众多技术分析指标中，BOLL 指标属于比较特殊的一类指标。绝大多数技术分析指标都是通过数量的方法构造出来的，它们本身不依赖趋势分析和形态分析，而 BOLL 指标却股价的形态和趋势有着密不可分的联系。BOLL 指标中的“股价通道”概念正是股价趋势理论的直观表现形式。BOLL 是利用“股价通道”来显示股价的各种价位，当股价波动很小，处于盘整时，股价通道就会变窄，这可能预示着股价的波动处于暂时的平静期；当股价波动超出狭窄的股价通道的上轨时，预示着股价的异常激烈的向上波动即将开始；当股价波动超出狭窄的股价通道的下轨时，同样也预示着股价的异常激烈的向下波动将开始。

投资者常常会遇到两种最常见的交易陷阱，一是买低陷阱，投资者在所谓的低位买进之后，股价不仅没有止跌反而不断下跌；二是卖高陷阱，股票在所谓的高点卖出后，股价却一路上涨。布林线特别运用了爱因斯坦的相对论，认为各类市场间都是互动的，市场内和市场间的各种变化都是相对性的，是不存在绝对性的，股价的高低是相对的，股价在上轨线以上或在下轨线以下只反映该股股价相对较高或较低，投资者作出投资判断前还须综合参考其他技术指标，包括价量配合，心理类指标，类比类指标，市场间的关联数据等。
*** 计算公式
BOLL 指标的计算方法是最复杂的之一，其中引进了统计学中的标准差概念，涉及到中轨线（MB）、上轨线（UP）和下轨线（DN）的计算。另外，和其他指标的计算一样，由于选用的计算周期的不同，BOLL 指标也包括日 BOLL 指标、周 BOLL 指标、月 BOLL 指标年 BOLL 指标以及分钟 BOLL 指标等各种类型。经常被用于股市研判的是日 BOLL 指标和周 BOLL 指标。虽然它们的计算时的取值有所不同，但基本的计算方法一样。

#+BEGIN_SRC pseudocode
1、日 BOLL 指标的计算公式
中轨线=N 日的移动平均线
上轨线=中轨线＋两倍的标准差
下轨线=中轨线－两倍的标准差

2、日 BOLL 指标的计算过程
（1）计算 MA
MA=N 日内的收盘价之和÷N
（2）计算标准差 MD
MD=平方根 N 日的（C－MA）的两次方之和除以 N
（3）计算 MB、UP、DN 线
MB=（N－1）日的 MA
UP=MB＋2×MD
DN=MB－2×MD
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 威廉指标——W%R
*** 简介
威廉指标 W%R 又叫威廉超买超卖指标，简称威廉指标，是由拉瑞·威廉（Larry William）在 1973 年发明的，是目前股市技术分析中比较常用的短期研判指标。
*** 指标的原理
威廉指标主要是通过分析一段时间内股价最高价、最低价和收盘价之间的关系，来判断股市的超买超卖现象，预测股价中短期的走势。它主要是利用振荡点来反映市场的超买超卖行为，分析多空双方力量的对比，从而提出有效的信号来研判市场中短期行为的走势。

威廉指标是属于研究股价波幅的技术分析指标，在公式设计上和随机指标的原理比较相似，两者都是从研究股价波幅出发，通过分析一段时间的股票的最高价、最低价和收盘价等这三者关系，来反映市场的买卖气势的强弱，借以考察阶段性市场气氛、判断价格和理性投资价值标准相背离的程度。

威廉指标在计算时首先要决定计算参数，此数可以采取一个买卖循环周期的半数。以日为买卖的周期为例，通常所选用的买卖循环周期为 8 日、14 日、28 日或 56 日等，扣除周六和周日，实际交易日为 6 日、10 日、20 日或 40 日等，取其一半则为 3 日、5 日、10 日或 20 日等。

威廉指标是表示当天的收盘价在过去一段时间里的全部价格范围内所处的相对位置，因此，计算出的 W%R 值位于 0——100 之间。越接近 0 值，表明目前的价位越接近过去 14 日内的最低价；越接近 100 值，表明目前的价位越接近过去 14 日内的最高价，从这点出发，对于威廉指标的研判可能比较更容易理解。
*** 计算公式
W%R=（Hn—C）÷（Hn—Ln）×100
其中：C 为计算日的收盘价，Ln 为 N 周期内的最低价，Hn 为 N 周期内的最高价，公式中的 N 为选定的计算时间参数，一般为 4 或 14。

以计算周期为 14 日为例，其计算过程如下：
W%R（14 日）=（H14—C）÷（H14—L14）×100
其中，C 为第 14 天的收盘价，H14 为 14 日内的最高价，L14 为 14 日内的最低价。
*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 动量指标——MTM
*** 简介
MTM 指标又叫动量指标，其英文全称是“Momentom Index”，是一种专门研究股价波动的中短期技术分析工具。
*** 指标的原理
动量指标 MTM 是一种利用动力学原理，专门研究股价在波动过程中各种加速、惯性作用以及由静到动或由动转静的现象。动量指标的理论基础是价格与供求量的关系。它认为股价的涨跌幅度随着时间的推移会逐渐变小，股价变化的速度和能量也会慢慢减缓后，行情就可能反转。在多头行情里，随着股价地不断上升，股价上涨的能量和速度必将日渐萎缩，当上涨的能量和速度减少到一定程度时，行情将会出现大幅回荡整理或见顶反转的行情；而在空头行情里，随着股价地不断下跌，股价下跌的能量和速度也将日渐萎缩，当下跌的能量和速度萎缩到一定程度时，行情也会出现大幅反弹或见底反转的行情。

因此，动量指标就是通过观察股价波动的速度，衡量股价波动的动能，从而揭示股价反转的规律，为投资者正确地买卖股价提供重要的参考。
*** 计算公式
#+BEGIN_SRC pseudocode
  1、第一种计算方法
  以日 MTM 指标为例，其计算过程如下：
  MTM（N 日）=C－CN
  式中，C=当日的收盘价
  CN=N 日前的收盘价
  N 为计算参数，一般起始参数为 6

  2、第二种计算方法
  以日 MTM 指标为例，其计算过程如下：
  MTM（N 日）=（C÷CN×100）－100
  式中，C=当日的收盘价
  CN=N 日前的收盘价
  N 为计算参数，一般起始参数为 6

#+END_SRC
*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 麦克指标——MIKE
*** 简介
MIKE 指标又叫麦克指标，其英文全称是“Mike Base”,是一种专门研究股价各种压力和支撑的中长期技术分析工具。
*** 指标的原理
目前，大多数技术分析指标都是利用股票的价格、从各种角度来分析判断股价的走势，其中，最典型的是开盘价、收盘价、最高价和最低价。虽然这四种价格已经基本上能反映股价的走势，但在某种程度上，这四种价格又都不能完全准确地反映股价在某一时期的真正走势。比如，在日常走势中，我们经常能看见在靠近收市时的几分钟里，某一股票的尾市行情突然风云变化，在短短几分钟里，在大量买盘的推动下，本来下跌的行情却变成大幅上涨的行情，股价也拔地而起。很显然，这种股价尾市的突然飙升并不能代表股价一整天的下跌走势，因此，这天该股票的收盘价并不能真实地反映股票当天的大部分时间的走势，该天的收盘价也就失去了的真实性。同样，很多股票的某些交易日的开盘价、最高价和最低价也会在主力机构地刻意拉抬或打压下，会经常发生这样的情况。

为了在某种程度上去弥补那些由于利用股票的开盘价、收盘价等价格的技术指标在行情研判上的误差，MIKE 指标设定了一个起始价格（即 Typicalprice 简称 TYP），以此作为计算基准，求得股价的初级、中级和强力等 6 种支撑或压力价位区，从而为投资者预测股价的短中长期的走势提供重要的参考。
*** 计算公式

#+BEGIN_SRC pseudocode
1、计算初始价——TYP 的数值
TYP=（H＋L＋C）÷3
式中，H=当日的最高价
L=当日的最低价
C=当日的收盘价
TYP 为起始价

有的股市分析软件还采用加权方法进行计算，计算公式为：
TYP=（H＋L＋2C）÷4
两式中字母代号所表示的含义是一样的，计算的结果差别不大。MIKE 指标是利用起始价位来计算出股价的弱、中、强的三个压力价位和三个支撑价位，从而为预测股价未来走势提供帮助。

2、计算股价的三个压力价位
MIKE 指标中的三个压力价位分别为：初级压力——WR、中级压力——MR 和强力压力——SR。它们的计算公式为：
WR（N 日）=TYP＋（TYP－LN）
MR（N 日）=TYP＋（HN－LN）
SR（N 日）=2×HN－LN
式中，TYP=起始价
LN=N 日的最低价
HN=N 日的最高价

3、计算股价的三个支撑价位
MIKE 指标中的三个支撑价位分别为：初级支撑——WS、中级支撑——MS 和强力支撑——SS。它们的计算公式为：
WS（N 日）=TYP－（HN－TYP）
MS（N 日）=TYP－（HN－LN）
SS（N 日）=2×LN－HN
式中，TYP=起始价
LN=N 日内的最低价
HN=N 日内的最高价
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 平行线差指标——DMA
*** 简介
DMA 指标又叫平行线差指标，是目前股市分析技术指标中的一种中短期指标，它常用于大盘指数和个股的研判。
*** 指标的原理
DMA 指标是属于趋向类指标，也是一种趋势分析指标。DMA 是依据快慢两条移动平均线的差值情况来分析价格趋势的一种技术分析指标。它主要通过计算两条基准周期不同的移动平均线的差值，来判断当前买入卖出的能量的大小和未来价格走势的趋势。
*** 计算公式

#+BEGIN_SRC pseudocode
DMA=短期平均值—长期平均值
AMA=短期平均值

以求 10 日、50 日为基准周期的 DMA 指标为例，其计算过程具体如下：
DMA（10）=10 日平均值—50 日平均值
AMA（10）=10 日平均值
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 心理线指标——PSY
*** 简介
心理线 PSY 指标是从英文 Phycholoigical Line 直译过来的，是研究投资者对股市涨跌产生心理波动的情绪指标，是一种能量类和涨跌类指标，它对股市短期走势的研判具有一定的参考意义。
*** 指标的原理
作为分析股市的涨跌指标，PSY 指标是在时间的角度上计算 N 日内的多空总力量，来描述股市目前处于强势或弱势，是否处于超买或超卖状态。它主要是通过计算 N 内股价或指数上涨天数的多少来衡量投资者的心理承受能力，反映股市未来发展趋势及股价是否存在过度的涨跌行为，为投资者买卖股票提供参考。

*** 计算公式
#+BEGIN_SRC pseudocode
PSY（N）=A÷N×100
其中，N 为周期，是 PSY 的参数，可以为日、周、月、分钟
A 为在这周期之中股价上涨的周期数
例如：N=20 日时，日之中有 12 日上涨，8 日下跌，则 PSY（20 日）=60
这里判断上涨和下跌是以收盘价为标准，计算日周期的收盘价如果比上一周期的收盘价高，则定为上涨；比上一周期的收盘价低，则定为下跌。
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 乖离率指标——BIAS
*** 简介
乖离率 BIAS 指标又叫 Y 值，是由移动平均原理派生出来的一种技术分析指标，是目前股市技术分析中一种短中长期皆可的技术分析工具。
*** 指标的原理
乖离率 BIAS 指标是依据葛兰碧移动均线八大法则而派生出来的项技术分析指标，它是通过一定的数学公式，来计算和总结出当价格偏离移动平均线的程度，指出买卖时机。

乖离率 BIAS 是表示计算期的股价指数或个股的收盘价与移动平均线之间的差距的技术指标。它是对移动平均线理论的重要补充。它的功能在于测算股价在变动过程中与移动平均线的偏离程度，从而得出股价在剧烈变动时，因偏离移动趋势过远而可能造成得回挡和反弹。

乖离率指标 BIAS 认为如果股价离移动平均线太远，不管是股价在移动平均线之上，还是在移动平均线之下，都不会保持太长的时间，而且随时会有反转现象发生，使股价再次趋向移动平均线。
*** 计算公式
#+BEGIN_SRC pseudocode
N 日 BIAS=（当日收盘价—N 日移动平均价）÷N 日移动平均价×100

N 的采用数值有很多种，常见的有两大种。一种是以 5 日、10 日、30 日和 60 日等以 5 的倍数为数值的；一种是 6 日、12 日、18 日、24 日和 72 日等以 6 的倍数为数值的。不过尽管它们数值不同，但分析方法和研判功能是相差不大.
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 振动升降指标(Accumulation Swing Index)——ASI
*** 简介
振动升降指标又称 ASI 指标（Accumulation Swing Index）、实质线，由 Welles Wilder 所创。ASI 企图以开盘、最高、最低、收盘价构筑成一条幻想线，以便取代目前的走势，形成最能表现当前市况的真实市场线（Real Market）。
*** 指标的原理
韦尔达认为当天的交易价格，并不能代表当时真实的市况，真实的市况必须取决于当天的价格，和前一天及次一天价格间的关系，他经过无数次的测试之后，决定了 ASI 计算公式中的因子，最能代表市场的方向性。由于 ASI 相对比当时的市场价格更具真实性，因此，对于股价是否真实的创新高或新低点，提供了相当精确的验证，又因 ASI 精密的运算数值，更为股民提供了判断股价是否真实突破压力，或支撑的依据。

ASI 和 OBV 同样维持“N”字型的波动，并且也以突破或跌破“N”型高、低点，为观察 ASI 的主要方法。ASI 不仅提供辨认股价真实与否的功能，另外也具备了“停损”的作用，及时地给投资人多一层的保护。
*** 计算公式

#+BEGIN_SRC pseudocode
1. A=当天最高价-前一天收盘价
　　B=当天最低价-前一天收盘价
　　C=当天最高价-前一天最低价
　　D=前一天收盘价-前一天开盘价
　　A、B、C、D 皆采用绝对值
2. E=当天收盘价-前一天收盘价
　　F=当天收盘价-当天开盘价
　　G=前一天收盘价-前一天开盘价
　　E、F、G 采用其+－差值
3. X＝E＋1／2F＋G。
4. K=比较 A、B 两数值，选出其中最大值
5. 比较 A、B、C 三数值：
　　若 A 最大，则 R＝A＋ 1／2B＋ 1／4D
　　若 B 最大，则 R＝B＋1／２A 十 1／4D
　　若 C 最大，则 R= C＋1/4D
6. L＝3
7. SI= 50* X／R * K／L
8. ASI=累计每日之 SI 值
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 简易波动指标——EMV
*** 简介
它是根据成交量和人气的变化，构成一个完整的股价系统循环。指示投资者在人气聚集且成交热络的时候买进股票，并且在成交量逐渐展现无力，而狂热的投资者尚未察觉能量即将用尽时，卖出股票。
*** 指标的原理
EMV 指标是一个将价格与成交量的变化结合在一起的指标。其设计者认为，价格在上升趋势的保持过程中不会耗用太多的能量，仅当趋势发生转折时成交量才会放大。这种说法虽然与传统价升量增的观点相悖，但确有独到之处。
从 EMV 指标的设计理念来看，投资者应当高度重视其所发出的信号。因为该指标可以依靠指标的变动情况，就能得出一个主力资金粗略的控盘程度。
*** 计算公式

#+BEGIN_SRC pseudocode
1.A=（今日最高+今日最低）/2
  B=（前日最高+前日最低）/2
  C=今日最高-今日最低
2.EM=（A-B）*C/今日成交额
3.EMV=N 日内 EM 的累和
4.MAEMV=EMV 的 M 日的简单移动平均
5.参数 N 为 14，参数 M 为 9
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 威廉变异离散量(William's Variable Accumulation Distribution)——WVAD
*** 简介
WVAD(Williams's Variable Accumulation/Distribution)是一种加权的量价动量指标，由 Larry Williams 所设计，其作用在于测量从开盘到收盘期间，买方与卖方各自的爆发力程度。
*** 指标的原理
威廉变异离散量的主要的理论精髓，在于重视一天中开盘到收盘之间的价位，而将此区域之上的价位视为压力，区域之下的价位视为支撑，求取此区域占当天总波动的百分比，以便测量当天的成交量中，有多少属于此区域。成为实际有意义的交易量。

如果区域之上的压力较大，将促使 WVAD 变成负值，代表卖方的实力强大，此时应该卖出持股。如果区域之下的支撑较大，将促使 WVAD 变成正值，代表买方的实力雄厚，此时应该买进股票。

WVAD 正负之间，强弱一线之隔。非常符合我们推广的东方哲学技术理论，由于模拟测试所选用的周期相当长,测试结果也以长周期成绩较佳。因此，建议长期投资者适合使用，如同 EMV 使用法则一样，应该在一定的投资期限内，不断的根据 WVAD 讯号将交易买卖，以求得统计盈亏概率的成果。
*** 计算公式
#+BEGIN_SRC pseudocode
一) 以 WVAD 是否穿越零轴线，作为买卖标准时有很严重的延误性，往往股价已冲高许多时，才会出现买入信号，反之亦然。也有使用 WVAD 和 WVAD 的 6 日平均线做比较进行研判，但误差率较高，特别是在卖出信号的研判上。
　　1、A=当天收盘价－当天开盘价
　　2、B=当天最高价－当天最低价
　　3、V=当天成交金额
　　4、WVAD=∑(A÷B×V)
　　5、参数周期可更改为 6 或 12 天
二) 改进方案： 成交量改为成交额，使用成交量或使用成交额对于个股的研判并没有太大的区别.
　　WVAD＝当日收盘价－当日开盘价÷当日最高价－当日最低价×成交额
　　WVAD5＝当日收盘价－当日开盘价÷当日最高价－当日最低价×成交额的 5 日累加÷5
　　WVAD21＝当日收盘价－当日开盘价÷当日最高价－当日最低价×成交额的 21 日累加÷21
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 变动率指标——ROC
*** 简介
以今天的收盘价比较其 N 天前的收盘价的差除以 N 天前的收盘（本质其实是 N 日 K 线的涨幅），以比率表示之，此指标经由 Gerald Apple 和 Fred Hitschler 两人于"Stock Market Trading Systems"一书中介绍，采用 12 天及 25 天周期可达到相当的效果。
*** 指标的原理
*** 计算公式
#+BEGIN_SRC pseudocode
1、AX=今天的收盘价—12 天前的收盘价
2、BX=12 天前的收盘价
3、ROC=AX/BX
#+END_SRC
*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 超买超卖指标——OBOS
*** 简介
预测股票指数走势。
OBOS 指标又叫超买超卖指标，其英文全称是“Over Bought Over Sold”，和 ADR、ADL 一样是专门研究股票指数走势的中长期技术分析工具。

*** 指标的原理
超买超卖指标 OBOS 主要是运用一段时间内整个股票市场中涨跌家数的累积差关系，来测量大盘买卖气势的强弱及未来演变趋势，以作为研判股市呈现超买或超卖区的参考指标。

OBOS 指标的原理主要是对投资者心理面的变化作为假定，认为当股市大势持续上涨时，必然会使部分敏感的主力机构货利了结，从而诱发大势反转向下，而当大势持续下跌时，又会吸引部分先知先觉的机构进场吸纳，触发向上反弹行情。因此，当 OBOS 指标逐渐向上并进入超越正常水平时，即代表市场的买气逐渐升温并最终导致大盘超买现象。同样，当 OBOS 指标持续下跌时，则导致超卖现象。对整个股票市场而言，由于 OBOS 指标在某种程度上反应了部分市场主力的行为模式。因此在预测上，当大盘处于由牛市向熊市转变时，OBOS 指标理论上具有领先大盘指数的能力；而当大盘处于由熊市向牛市反转时，OBOS 指标理论上稍微落后于大盘指数的缺陷，但从另一种角度看，它可以真正确认大盘的牛转熊是否有效。

*** 计算公式

#+BEGIN_SRC pseudocode
OBOS（N 日）=∑NA－∑NB

式中，∑NA——N 日内股票上涨家数之和

∑NB——N 日内股票下跌家数之和

N 为选择的天数，是日 OBOS 指标的参数
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 涨跌比率指标——ADR
*** 简介
ADR 指标又叫涨跌比率指标或上升下降比指标，其英文全称是“Advance Decline Ratio”。和 ADL 指标一样，是专门研究股票指数走势的中长期技术分析工具。
*** 指标的原理
涨跌比率 ADR 指标是将一定时期内上市交易的全部股票中的上涨家数和下跌家数进行比较，得出上涨和下跌之间的比值并推断市场上多空力量之间的变化，进而判断市场上的实际情况。由于和 ADL 指标存在着一定的联系，ADR 指标又称为回归式腾落指数。该指标集中了股票市场中个股的涨跌信息，可反映股市大盘的强弱趋向，但没有表现个股的具体的强弱态势，因此，它和 ADL 一样，同属于是专门大势广量指标，是专门研究股票指数的指标，而不能用于选股与研究个股的走势。

涨跌比率 ADR 指标的构成基础是“钟摆原理”，即当一方力量过大时，会产生物极必反的效果，向相反的方向摆动的拉力越强，反之，亦然。该原理表现在股市上，就意味着当股市中人气过于高涨，股市屡创新高的以后，接下来可能就会爆发一轮大跌的行情，而当股市中人气低迷，股价指数不断下挫而跌无可跌的时候，可能一轮新的上涨行情即将展开。ADR 指标就是通过一定时期内的整个股票市场上的上涨和下跌家数的比率，衡量多空双方的变化来判断未来股票市场整体的走势。
*** 计算公式

#+BEGIN_SRC pseudocode
ADR（N 日）=P1÷P2

式中，P1=ΣNA——N 日内股票上涨家数之和

P2=ΣND——N 日内股票下跌家数之和

N 为选择的天数，是日 ADR 的参数
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** 腾落指标——ADL
*** 简介
ADL 指标又叫腾落指数或涨跌线指标，其英文全称是“Advance Decline Line”，缩写为 ADL。它是专门研究股票指数走势的技术分析工具。
*** 指标的原理
在正常情况下，股市大势指数上升，上涨股票的家数必然较多；相反，股市大势指数指数下跌，下降股票的家数较多。两者之间的关系往往成正比，而股市大势的升降与市场的人气的强弱情形也是相同的。但是，当股市大势指数接近高位或低位时，也常有例外发生。这主要是由于股市大势指数的计算一般都是以股市大势高低和股本总额的大小来选样加权计算的，这就使得市场上的高价股和股本流通盘大的股票（即指标股或成分股），其上升或下跌在指数运算中所占的比例甚重，对指数的涨跌影响较大。而市场上的主力为了吸引买盘的兴趣，或诱逼卖方抛售，达到有效控制市场的目的，经常利用股本大或者股市大势高的个股占股市大势指数的特性，刻意拉抬或者打压指标股，从而间接地影响大盘走势的涨跌。
*** 计算公式

#+BEGIN_SRC pseudocode
如果当日所有股票中上涨的共有 A 家，下降的共有 F 家，持平的为 B 家，这里涨跌标准是以当日收盘价与上一日收盘价相比较。这样当日的 ADL 值的计算公式为
当日 ADL=上一日 ADL＋A－F

由上式推出：
当日 ADL=∑A－∑F
式中，∑A 表示从开始交易的第一天算起，每一个交易日的上涨家数的总和
∑F 表示从开始交易的第一天算起，每一个交易日的下跌家数的总和
#+END_SRC

*** 一般研判标准
*** 特殊分析法
*** 实战技巧
** model
*** 简介
*** 指标的原理
*** 计算公式
*** 一般研判标准
*** 特殊分析法
*** 实战技巧
