交易中你必须明白，当 你被告知不要做某件事的时候，这并不意味你应该去做相反的事情。

* 规则一: 不要持有 仓位，除非你的交易已经被证明是正确的。

交易是“失败者”游戏，而不是“胜利 者”游戏

在市场证明我们的交易是正确的以前， 已建立的仓位必须不断减少和清除。

市场可能没有证明仓位是 正确的，同时也非常有可能并没有证明它是错误的。如果你等待，并希望市场最终会证明你
是正确的，你可能在浪费时间、金钱和精力，因为你的交易可能是错的。

如果交易没有被证明是正确的，就要尽早平仓。等待一笔交易被证明是错的，会产生更大的价格滑动，因为在那个时候，每一个人都获得了相同的市场信息。
* 规则二:正确加码才能获利
毫无例外并且正确地对你的赢利仓位加码。

大多数交易者在帐面盈利时，经常有一种冲动去套现，从而证明自己是正确的。然而， 正确的交易本身实际上并不能产生主要利润。

一般情况下，他们会看着自己亏损仓一天天亏下去而不知所措，而赢利仓刚刚开始启动， 就急着平仓出场。这是人性在市场中的反应。在交易中，人的本能其实是一个障碍。

对一个已经确认盈利的仓位进行加码，必须有正确地执行方法，这样才不会在顶部建立 新仓位，以避免可能的风险。

你的原始仓位有 6 口合 约，那么在你第一次加码时增加 4 口合约，第二次则加 2 口合约。这样通过总共两次加仓， 你的原始仓位翻倍，其比例为 3:2:1。

当日交易者的目标是快速获利，所以一个好的加码计划操作起来会很困难。最好的当日交易方法，是一次性建立所有的仓位，然后用规则一进行平仓。

如果你可以把你的损失控制在很小的一个范围内， 而不是每次都赢了一点点的话，你会成为最优秀的交易员!
* 改变你的行为习惯
  在一个像交易这样的失败者游戏中......一开始时我们就是与大多数人对立的立场上，在 被证明是正确的以前，我们假定我们是错的!直到市场证明我们的仓位正确之前，我们必须 不断地减仓或清仓(我们不假定我们是正确的，直到被证明错了。我们让市场去证明正确的 和不正确的仓位)。

  我们将会专注于保护自己，而不是首先期望盈利，这就是行为习惯改变。在交易中，这 一点和任何进退决策都一样重要。

  你应该能理解我这样说的理由。在交易者最初开户时，从来没有人向他们强调过，知识 和行为习惯改变是成功交易的必要条件。

  交易是失败者的游戏， 经得起失败的人是最大的获胜者!
** 电梯例子

   我们在远离交易区的地方，观察最高层电梯间的情况。我们观察的第一组人是那些正等 待上电梯的交易员，我们要看这些人会有什么样的行为。

   我们设计了电梯到达时将要出现的两种状态。第一种状态是电梯一开门交易员就立即挤 进电梯，第二种状态则是在电梯开门时他们会先向后退，以便里边的人出来。通过使用这两 种状态的二进制输入方式，我们就有了一个很好的计算程序
   实验结果相当令人吃惊。电梯到顶层刚开门，大多数人就会使劲往里面挤。他们没有考 虑到会有人下电梯，甚至当电梯里的人还没来得及出电梯之前，一些人就会挤进去。这显得 得奇怪，大多数等在电梯外的人没有意识到电梯到了顶层:所有在电梯里的人都会出来的，当电梯到达时，他们竟然就堵在电梯门口。

   也有少数人会向后退一步，他们意识到里面的人要先出来，外面的人才能进入电梯，他 们没进去之前电梯是不会关门下降的，于是他们会等到最后进去，而且到目的楼层时，他们 还将是第一批出电梯的人。我不会提醒你们三组人中哪一组做得最好，因为你自己决定你将 作出何种反应。

