* 常用快捷键
ctrl+shift+G: 选中你所要查看的方法名, 就可以查看所有调用过该方法的地方了。在 Search 视图里面可以查看得到
这个样子是可以的，你也可以按 Ctrl+H 全文检索一下
** [[http://www.open-open.com/solution/view/1320934157953][Eclipse 快捷键 10 个最有用的快捷键]]
更多快捷键组合可在 Eclipse 按下 ctrl+shift+L 查看。
   1. ctrl+shift+r：打开资源

    这可能是所有快捷键组合中最省时间的了。这组快捷键可以让你打开你的工作区中任何一个文件，而你只需要按下文件名或 mask 名中的前几个字母，比如 applic*.xml。美中不足的是这组快捷键并非在所有视图下都能用。

   2. ctrl+o：快速 outline

    如果想要查看当前类的方法或某个特定方法，但又不想把代码拉上拉下，也不想使用查找功能的话，就用 ctrl+o 吧。它可以列出当前类中的所有方法及属性，你只需输入你想要查询的方法名，点击 enter 就能够直接跳转至你想去的位置。

   3. ctrl+e：快速转换编辑器

    这组快捷键将帮助你在打开的编辑器之间浏览。使用 ctrl+page down 或 ctrl+page up 可以浏览前后的选项卡，但是在很多文件打开的状态下，ctrl+e 会更加有效率。

   4. ctrl+2，L：为本地变量赋值

    开发过程中，我常常先编写方法，如 Calendar.getInstance()，然后通过 ctrl+2 快捷键将方法的计算结果赋值于一个本地变量之上。 这样我节省了输入类名，变量名以及导入声明的时间。Ctrl+F 的效果类似，不过效果是把方法的计算结果赋值于类中的域。

   5. alt+shift+r：重命名

    重命名属性及方法在几年前还是个很麻烦的事，需要大量使用搜索及替换，以至于代码变得零零散散的。今天的 Java IDE 提供源码处理功能，Eclipse 也是一样。现在，变量和方法的重命名变得十分简单，你会习惯于在每次出现更好替代名称的时候都做一次重命名。要使 用这个功能，将鼠标移动至属性名或方法名上，按下 alt+shift+r，输入新名称并点击回车。就此完成。如果你重命名的是类中的一个属性，你可以点击 alt+shift+r 两次，这会呼叫出源码处理对话框，可以实现 get 及 set 方法的自动重命名。

    6. alt+shift+l 以及 alt+shift+m：提取本地变量及方法

    源码处理还包括从大块的代码中提取变量和方法的功能。比如，要从一个 string 创建一个常量，那么就选定文本并按下 alt+shift+l 即可。如果同 一个 string 在同一类中的别处出现，它会被自动替换。方法提取也是个非常方便的功能。将大方法分解成较小的、充分定义的方法会极大的减少复杂度，并提 升代码的可测试性。

    7. shift+enter 及 ctrl+shift+enter

    Shift+enter 在当前行之下创建一个空白行，与光标是否在行末无关。Ctrl+shift+enter 则在当前行之前插入空白行。

    8. Alt+方向键

    这也是个节省时间的法宝。这个组合将当前行的内容往上或下移动。在 try/catch 部分，这个快捷方式尤其好使。

    9. ctrl+m

    大显示屏幕能够提高工作效率是大家都知道的。Ctrl+m 是编辑器窗口最大化的快捷键。

    10. ctrl+.及 ctrl+1：下一个错误及快速修改

    ctrl+.将光标移动至当前文件中的下一个报错处或警告处。这组快捷键我一般与 ctrl+1 一并使用，即修改建议的快捷键。新版 Eclipse 的修改建 议做的很不错，可以帮你解决很多问题，如方法中的缺失参数，throw/catch exception，未执行的方法等等。

** [[http://www.cnblogs.com/yanyansha/archive/2011/08/30/2159265.html][研读代码必须掌握的 eclipse 快捷键]]
1. Ctrl+左键 和 F3
这个是大多数人经常用到的，用来查看变量、方法、类的定义
跳到光标所在标识符的定义代码。当按执行流程阅读时，F3 实现了大部分导航动作。

2 Ctrl+Shift+G
在工作空间中查找引用了光标所在标识符的位置。可以说是与 F3 相反的快捷键。当按类定义进行阅读时，可以迅速找出当前类方法在被哪些类调用了。

3. Ctrl+O

查看一个类的纲要，列出其方法和成员变量。提示：再多按一次 Ctrl+O，可以列出该类继承的方法和变量。

助记："O"--->"Outline"--->"纲要"

4 F4
打开继承树。显示当前类所在的继承树。不但包括父类，还包括当前类的子类。

5. Ctrl+T

查看一个类的继承关系树，是自顶向下的，再多按一次 Ctrl+T, 会换成自底向上的显示结构。与"F4"快捷键不同的是显示方式。

提示：选中一个方法名，按 Ctrl+T，可以查看到有这个同名方法的父类、子类、接口。

助记："T"------->"Tree"----->"层次树"

6.Alt+左右方向键

我们经常会遇到看代码时 Ctrl+左键，层层跟踪，然后迷失在代码中的情况，这时只需要按“Alt+左方向键”就可以退回到上次阅读的位置，同理，按“Alt+右方向键”会前进到刚

才退回的阅读位置，就像浏览器的前进和后退按钮一样。

Alt+-->返回上一个阅读位置。使用查找功能或导航功能跳转后，可以用 ALT-左箭头返回上一个阅读位置，而且还是多层历史记录。类似 IE 的后退。若要这个后退功能 达到最好效

率，就要养成使用它的习惯，例如遇到了一个方法调用，用 F3 打开了它所在的类文件，看完后应用 alt-左箭头来后退，而不是直接关掉新打开的标 签页。否则这个新开的标签页将

会被记录到历史中，下次后退到这里时又会被重新打开。

7.Ctrl+Alt+H

如果你想知道一个类的方法到底被那些其他的类调用，那么请选中这个方法名，然后按“Ctrl+Alt+H”，Eclipse 就会显示出这个方法被哪些方法调用，最终产生一个调用关系树。

助记："H"--->"Hierarchy"--->"调用层次"

8 Alt+M,U
Open Super Implementation

打开光标所在类方法所覆盖的超类方法，相当于在覆盖方法中用鼠标点左边的覆盖方法三角标志。此功能没有默认快捷键，须在主菜单 Windows->Preferences->General-
>Keys->Modify->Command->Navigate, Open Super Implementation 中设置，我个人习惯设为 Alt+M,U。
 
9Alt+M,S
Show Selected Element Only
仅显示光标所在元素（类方法等）。隐藏当前代码中的其他部分，把光标所在的类方法置顶显示。我个人比较喜欢这种方式，一来屏幕比较清洁，二来此时使用导航 功能导航到类
方法必然是置顶显示，三来可以迫使自己习惯使用导航功能（F3，ALT+左右箭头）等进行导航而不是习惯性地拖滚动条。再按一次则取消此方式。
此功能没有默认快捷键，须在主菜单 Windows->Preferences->General->Keys->Modify->Command->Navigate, Open Super Implementation 中设置，我个人习惯设为 Alt+M,S。

10 Ctrl+E
弹出一个简易对话框用来精确切换代码编辑栏。(注意不要不小心按了 Ctrl+W 把当前栏目关了，可以考虑取消 Ctrl+W 关闭当前栏目的设定，因为 Ctrl+W 实在太容易误按。我个人比较习惯用 Ctrl+F4 来关闭栏目）
 
11ctrl+M
最大化当前窗口。配合 F12（编辑窗口获得焦点），可以立刻最大化代码编辑栏。(F12、Ctrl+M)

12Ctrl+小键盘的+ - * /
控制代码结构的折叠与展开。由于我个人喜欢用 Show Selected Elemnt Only 多于折叠代码，而且要看类成员结构可以用 Outline 栏目（Shift+Alt+Q,O）或 Ctrl+O。因此比较少用这个功能。主要用来集中 查看类方法的 Inline JavaDoc 注释。
 
13 Open Implemention
就是可以跳转到某个调用的方法的具体实现的地方去。为什么说这个是超级好用呢？用过 Spring 的人都知道，现在都提倡面向接口编程，所以，如果使用 Open Declaration 来追踪
一个方法的调用的话，只会看到该方法在接口中的声明，而看不该方法在具体类中的实现，当然，可以使用 Call Hierarchy 先得到该方法的整个的调用层次，然后再导航到具体的实现处，但操作有些麻烦了。有了 Open Implemention，就可以直接看到实现的代码了，在方法名上点击右键，选择 Open Implemention 就可以了！只是要享受这个功能，可安装一个 Eclipse 插件，到这里可以下载 http://eclipse-tools.sourceforge.net/implementors/

Ctrl+Shift+T
在工作空间内查找类型（包括所有项目中的类，引用 JAR 包中的类）。这是按名称打开一个类最快捷的方法。

Ctrl-PageUp/Ctrl-PageDown
切换到上一个/下一个标签页

ctrl+F4 或 ctrl+w
关闭当前标签页

Shift+Alt+Q
打开一个特定栏目，Shift+Alt+Q 后可跟一个键表示要打开的栏目。按下 Shift+Alt+Q 后过一会可看到提示窗。

Ctrl+J
递增式查找。在当前编辑窗口中进行递增式查找。查找过程中按下箭头可跳到下一个匹配点，按上箭头跳到上一个匹配点，按 ESC 退出递增式查找。

Ctrl+H
打开查找窗口。打开一个可以进行详细设置的查找对话框。由于 Eclipse 各种导航功能很完善，我比较少用这个查找功能。主要用来进行一些用正则表达式做条件的查找。在查找中，用 Ctrl+K 查找下一个匹配。

Ctrl+Shift+E
弹出一个对话框来切换或关闭多个代码编辑栏。

当然还有最基本的，Ctrl+Shift+L，显示快捷键列表。
* 安装
** color theme
点击 eclipse 里的 help->install new software. 然后点击弹出窗口的 add,名字可以随便起一个,URL 地址填写: http://eclipse-color-theme.github.io/update/

点击 OK 之后,下面的插件全部选上,然后按照向导安装即可.安装完成之后,会提示重启 eclipse.

然后再 preferences -> general -> appearance -> color theme

** c - c++
** Vrapper
