[[link]http://wenku.baidu.com/link?url=vt2H4NuC7QY26Bf_0K-3YNEUBsuqXOZvVPyG5g8TfJD_HjPwfWZM-9oolGyPn9ZRYa4ZLGvhfHQ2Et32ulTraUFEWW87cfYrgQATtRIDx_C]
* 数据仓库层次结构规范
** 基本分层结构
*** stage 层（对应原来数据模型的 SRC 接口层)信息模型
STAGE 是生产系统数据源的直接拷贝，由 ETL 过程对数据源进行直接抽取，在格式和数据定义上不作任何改变。与生产系统数据的唯一不同是，STAGE 层数据具有时间戳。
STAGE 层存在的意义在于两点：
（1） 对数据源作统一的一次性获取，数据仓库中其他部分都依赖于 STAGE 层的数据，不再重复进行抽取，也不在生产系统上作运算，减小生产系统的压力；
（2） 在生产系统数据已经刷新的情况下，保存一定量的生产系统的历史数据，以便在二次抽取过程中运算出错的情况下可以进行回溯。

*** ODS/DWD 层对应原模型的 ODS 和 DW 层）信息模型：简称 DWD 层
是数据仓库的*细节数据层*，是对 STAGE 层数据进行沉淀，减少了抽取的复杂性，同时
ODS/DWD 的信息模型组织主要遵循企业业务事务处理的形式，将各个专业数据进行集中。
为企业进行经营数据的分析，系统将数据按分析的主题的形式存放，跟 STAGE 层的粒度一
致，属于分析的公共资源。

*** MID 信息模型
轻度综合层是新模型增加的数据仓库中 DWD 层和 DM
层之间的一个过渡层次，是对 DWD 层的生产数据进行轻度综合和汇总统计。轻度综合层与
DWD 的主要区别在于二者的应用领域不同，DWD 的数据来源于生产型系统，并为满足一些不
可预见的需求而进行沉淀；轻度综合层则面向分析型应用进行细粒度的统计和沉淀。

*** DM 信息模型(data mining)
为专题经营分析服务，系统将数据按分析的专题组织成
多维库表的形式存放，属于分析目标范畴的数据组织与汇总，属于分析的专有资源。其信
息主要来源于 DWD 和 MID 层汇总，反映实时的经营状况，时间维度为天。而历史经营状况
的分析，时间维度一般为月，同时也具有季度、年这样的维度。

*** MDW 元数据信息模型
描述数据及其环境的数据，即是对数据资源的描述,
是信息共享和交换的基础和前提，用于描述数据集的内容、质量、表示方式、
空间参考、管理方式以及数据集的其他特征。一般来说,它有两方面的用途。首先,元数据能提供基于用户的信息,如记录数据项的业务描述信息的元数据能帮助用户使用数据。其次,元数据能支持系统对数据的管理和维护, 元数据机制主要支持以下五类系统管理功能: （１）描述哪些数据在数据仓库中;
（２）定义要进入数据仓库中的数据和从数据仓库中产生的数据; （３）记录根据业务事
件发生而随之进行的数据抽取工作时间安排; （４）记录并检测系统数据一致性的要求和
执行情况; （５）衡量数据质量。

** 各层物理表前缀
  file:../Pictures/warehouse/各层物理表.png
