* level 2
** unit 1
*** 描述演出的形容词
   许多可以用来描述演出的形容词都以 -ing 结尾，从动词变化而来。比如，形容词 relaxing 来自动词 relax。

   interesting	有趣的           
   boring 	无聊的
   relaxing	轻松的
   exciting	令人兴奋的
   surprising     	令人惊讶的

   以下是其他一些描述演出的形容词。

   fun  	快乐的，有趣的
   incredible	精彩的
   loud	喧闹的
   quiet	安静的
   wonderful	出色的
   terrible	糟糕的

   识记形容词的一个方法是同时学习它们的反义词。
 
   interesting - boring 
   relaxing - exciting 
   loud - quiet 
   wonderful - terrible  
*** why and because
    Why 和 because
 
   使用疑问词 why 询问原因，使用单词 because 说明原因。

   A: Why did you go to Paris?
   B: I went to Paris because it's beautiful!	你为什么去巴黎？
   我去巴黎因为她太美了！

   单词 because 引出原因从句，比如 because it's beautiful。原因从句与提出句子主题的主句共同使用，比如 I went to Paris。下面还有一些例子。

     主句          	原因从句
   I go to that restaurant 	because it's cheap, and the food is delicious.       
   I love surfing	because it's exciting.
   I go to concerts	because I enjoy classical music.

   在英语口语中，常常只用带有 because 的分句回答问题。主句 (I went to Paris) 意思都明白。

   A: Why did you go to Paris?
   B: Because it's beautiful!	Why did you go to Paris? Because it's beautiful!
   因为它美极了！
*** 建议活动
    提出活动建议有几种方法。
 
   Let's + 搭配动词原形

   Let's go to the dance performance.	我们去看舞蹈演出吧。

   How about 或 what about + 搭配动名词

   What about meeting some friends?	去见一些朋友怎么样？

   Could + 搭配动词原形

   We could go out for a drink at Harry's Bar.	我们可以去 Harry's Bar 酒吧喝点东西。

   Why don't we + 搭配动词原形

   Why don't we try a new restaurant?	我们为什不试试一家新餐馆呢？
*** 一般现在时表示的将来时
 
   谈论将来时，你有时可以使用一般现在时。如果谈及的演出活动隶属某计划表、时间表或演出日程，这种情况最为常见。表示演出开始或结束的动词，比如 begin 和 close，常常以一般现在时来表示将来时。

   表示演出开始的一般现在时

     begin	开始
     start	开始
     open	开始
   
   The dance performance begins at 8 o'clock tonight.	舞蹈演出今晚八点开始。
   
   Harold's Department Store opens at 9 a.m. tomorrow.	Harold's Department Store 明天早上九点开张。

   表示演出结束的一般现在时

     close 	结束
     end 	结束
     be over 	结束，完了
     finish 	结束

   

   The movie is over at 9:15 p.m.       	电影晚上九点一刻结束。
   
   She closes her shop at 6 o'clock.	她六点钟关店。

   语言点：记住在 he、she 和 it 后面，动词一般现在时后加 s。例如：  

   
   The movie ends at midnight. 	电影午夜结束。
*** 询问有关电影的信息
 
 想去看电影时，你需要了解有关电影的一些基本信息。你需要知道电影开始的时间、上映地点和电影票价。同时还要了解在哪里买票。使用下列问题来获取这一信息。
 

 Can you give me some information?	你能告诉我一些信息吗？

 Do you have a website?	你们有网站吗？

 Can I buy tickets online?	我可以网上购票吗？

 What's your address?	地址在哪里？

 What time is the next show?	下一场演出在什么时候？

 Are tickets still available?	还有票吗？

 How much are tickets?	票多少钱一张？
*** 表达恼怒
 
 表达恼怒有许多方法。主要的方法是提高说话音量。这表达出强烈的情感。
 
 重复
 
 表达恼怒的另一种方法是重复短语表示强调。
 

 OK, OK. I'm coming. I'm coming.	好好，我来了，我来了。                           

 表达怀疑

 通过表示你不相信某人做了某事，也能传达你的恼怒。
 

 I don't believe it! 	我不相信！

 I can't believe it!	我不敢相信！


 夸张
 
 你也可以通过夸大某人犯错的频率来表达愤怒。使用 always 和 never 来表示夸大。重读这些词来强调频率。
 

 Jake always forgets.	Jake 老是忘记。

 Mary never helps me.	Mary 从来不帮我。

 表达强烈的恼怒
 
 你可以使用 stupid 或 crazy 等形容词表达程度更强的恼怒。如果你用这些词形容一个人，表示你不是恼怒，而是生气了。谨慎使用这些词，因为它们可能伤害人的感情。
 

 This is stupid!	这很傻。

 Are you crazy?	你疯了吗？
** unit 2 
*** 人的外形描述
good-looking
漂亮的

a nice smile
迷人的笑容

blue eyes
蓝色的眼睛

long and dirty
长而脏

successful
成功的

handsome
帅气的

在描述人的身体时，我们通常会谈到身高和体重。需要注意的是，说人 fat 或者 overweight 往往被视为不礼貌的。不过在对人进行描述时，overweight 一词不礼貌的程度稍轻。
 

tall	高

medium height	中等高度

short	矮

overweight	超重

fat	肥胖

thin	瘦

在描述人的面孔时，我们通常会谈及眼睛的颜色和任何其他显著的容貌。描述容貌时，我们通常使用动词 have。
 

She has blue eyes.	她长着一双蓝眼睛。

He has big ears. 	他长着一对大耳朵。

He has a nice smile.	他拥有迷人的笑容。

当描述一个人的头发时，我们通常谈论长度，发型以及颜色。一个人秃顶我们就描述成 bald. 这里有一些有用的形容词：

long 	长发

medium length	中长发

short	短发

curly	卷发

straight	直发

blond	金发

bald	秃顶
 	 	 
在描述人的头发时，我们通常使用动词 have。但是，如果某人是 bald，我们就会使用动词 be。

She has long, straight, brown hair.	她拥有一头棕色的长长的直发。

My father is bald.	我父亲是秃顶。

另一种描述人的方法是谈论年龄。
 	 	 

old	老年

middle-aged	中年

young	年轻

*** 形容词的排序
 
  当您使用一个以上的形容词进行描述时，一般的规则是把它们按大小，年龄，然后颜色的顺序排列。
 
  
  That is a fat, old, black dog.	
  那是一只肥肥的老黑狗。

  请注意这些例子中的大小-年龄-颜色的顺序：
 
  
  He has big, brown eyes.	
  他长着一双大大的棕色眼睛。
  
  Her hair is shorter and grayer than before.	
  她的头发比以前更短了，也变得更灰白了。
  
  He's a thin, middle-aged man.	
  他是个瘦瘦的中年男子。
  
  That tall, young, blond man drives a truck.	
  那个高个儿的，金发碧眼的年轻男子开一辆卡车。

What is (person) like? 或者 What does (person) look like?是用来询问一个人的身材，形体，年龄或者整体的外貌。 使用动词 *be* 来描述整体的外貌。
 

A: What does he look like?	他长什么样？
B: He is tall and middle-aged. He's very good-looking.	他高个子，中年人，样子很好看。

您也可以使用像 What's his hair like? 或 What color are his eyes? 这样的疑问句去询问一个人的身体特定部位的描述。 使用动词 *have* 来指身体的部位。
 

A: What color are his eyes?	他的眼睛是什么颜色的？
B: They're brown.	它们是棕色的。
 	 	 

A: How tall is she?	她有多高？
B: She's very tall.	她很高。
 	 	 
A: What do the children look like?	这些小孩看起来像什么？
B: They have curly, red hair. Jasmine has big, brown eyes, and Jason has blue eyes.	他们的头发又红又卷，杰斯敏的眼睛大大的，是棕色的，而贾森的眼睛是蓝色的。


这里有很多形容词来给您描述一个人的外貌。请注意动词 be 与它们搭配时的用法。

 

He's not very good-looking.	他长得不是很好看。

She's beautiful!             	她天生丽质!

He's very attractive.                  	他很迷人。

He's handsome.                 	他相貌英俊。

语言点 Good-looking 与 attractive 具有相同的含义。Good-looking 与 attractive 可用于描述男性和女性。通常 Beautiful 用于描述女性，handsome 则一般用于描述男性。

*** 关系词汇
 
您应该已经知道家庭成员的基本词汇了。这里还有一些您将需要到的：
 

wife	妻子
        

husband	丈夫

granddaughter	孙女

grandson	孙子

aunt	阿姨

uncle	叔叔

niece	侄女

nephew	侄子

cousin	堂表兄弟姐妹

使用 friend 以区分哪些是您熟悉并喜爱的人。使用 girlfriend 来确定与一位女性的恋爱关系，使用 boyfriend 确定与一位男性的恋爱关系。

Is he your friend?	他是您的朋友?

I'm meeting my girlfriend tonight.	我今晚要去见我的女朋友。

He's my boyfriend.	他是我的男朋友。

partner 这个词可以指各种关系。您可以使用它来确定与一个人的配偶关系。它可以也指商业伙伴或其他业务关系。

This is my partner, Paul.	这是我的配偶, Paul。

James and I are business partners.	James 和我是商业伙伴。

您也可以用这些词来确定工作关系：

boss	上司

colleague	同事

描述关系
 
使用类似以下的表达来描述一段关系中正在发生的事情。注意，所有表达都后接动名词 (verb + -ing)。
 
表达式可以是肯定的：
 

We spend time watching movies. 	我们看电影打发时间。

I always have fun talking with him.	和他谈天我总是感到很开心。

表达式可以是否定的：
 

We have a hard time getting together.	我们好不容易在一起。

She has trouble making money.	赚钱对她来说是件困难的事。

They often waste time fighting.	(他们常常浪费时间吵架。)


谈论关系
 
请使用类似以下的问题来询问别人一段关系。注意答复中表达式 +动名词的结构。
 

A: How are you and your brother doing?
B: We're doing well, thanks. We spend time talking on the phone.	你和你哥哥（弟弟）关系还好吗？
我们关系很好，谢谢。我们会花时间打电话聊天。
 	 	 

A: What do you and Sylvia do for fun?
B: Let's see … We have a lot of fun playing tennis together.	你和 Sylvia 都玩什么？
让我想想……我们一起打网球，玩得很开心。

您可以使用 you two 表达密切的关系 - 例如，丈夫与妻子之间或母亲与孩子之前。
 

A: Are you two having trouble?
B: Yeah, we are. I am having trouble understanding her problems.
A: I'm sorry to hear that.	你们两人碰到什么难题了吗？
是的，我们碰到了难题。我难以理解她的问题。
听到这我很难过。

*** 描述员工
performance appraisals
绩效评估

hardworking
勤奋的

does a really good job
做得出色

worked really well with the team
与团队合作融洽

team player
有团队精神的人
 
not efficient enough
不够高效的

organized
有条理的

lazy
懒惰的

good in meetings
在会议中表现出色

helpful
有帮助的

使用这些形容词和短语来形容员工积极工作的品质。
 

hardworking	勤劳的

efficient	有效率的

creative	富有创造性的

helpful 	有用的

positive	积极的

does a good job 	做得不错

works well with the team / team player	与团队/ 队员合作愉快

getting better	逐渐在改善

good in meetings	善于开会

使用这些形容词和短语来描述员工消极的工作品质。
 

could do better 	可以做得更好

late 	迟到

negative	消极的

disorganized	混乱的

lazy	懒惰

一种更积极的方式来应对员工的弱点即是给出建设性的批评，而不是简单地给出消极的评论。
 

She's so disorganized. > She needs to be more organized.	她很混乱。 > 她应该要更有条理些。

He's too negative. > He should be more positive.	他太消极了。 > 他应该积极些。
 
'Too' 和 'enough'
 
请用 too + 形容词来描述某样东西超过必要，或超过所需时。
 

Her project is late because she's too disorganized.	她的项目已经晚了，因为她太没有条理了。

She's too negative. She thinks too much about problems.	她太消极了。 她想问题考虑得太多了。

请用形容词 + enough 来描述当某件东西足够的，或让人满意的时候。
 

Carson is hardworking and efficient enough to be the new manager.	Carson 够勤劳且够有效率，够格成为新经理。

请用 not + 形容词 + enough 来描述某件东西缺乏或不尽人意时。
 

Sally's not efficient enough. 	Sally 的效率还不够高。

He's not creative enough to work in marketing.   	他没有足够的创造力做市场营销工作。
 
*** 发表意见
    发表意见的时候用 'I think that'
 
使用 I think that 来表示您在发表一个意见。 使用 so do I 来表示同意一个 I think that 和 I like 这样的短语所表达的意见. 
 

A: I think that he does a really good job. 
B: So do I.      	
我觉得他干的不错。 
我也觉得。
 	 	 

A: I like them both.  
B: So do I.        	我喜欢他俩。

我也觉得。

使用 neither do I 来赞成 I don't think that 这样句式所表达的意见, 或其他否定意见。
 

A: I don't think she's lazy.  
B: Neither do I. 	我并不觉得她懒。

我也不觉得。

请注意 that 可以省掉且句子的含义没有受到影响。


要征求别人的意见，您可以使用 what do you think about 以及 do you think。
 

A: What do you think about Denise?  
B: She's very efficient.     	您觉得 Denise 怎么样?

她很有效率。
 	 	 

A: Do you think Paul is too disorganized?
B: No, not really.  	您觉不觉得 Paul 这个人太混乱了?

不，不是的。

语言注释：neither 有两种发音方法。在下面的例子中，第一个在美国比较普遍的；第二种多见于英国。但它们可以互换使用。
 

A: I don't think he's disorganized.
B: Neither do I. 	我并不觉得他这个人没有调理。

我也不觉得。
 	 	 

A: I don't think she's very efficient.
B: Neither do I. 	我并不觉得她很有效率。

我也不觉得。

*** 在工作中所用的副词
 
副词解释 how, when or where。它们可以修饰一个动词，形容词或另一个副词。许多副词以-ly 结尾的是最容易识别的和形成的。但是，许多副词是不以-ly 结尾的,识别它们的最好的方式是将它们连接到它们所修饰的动词，形容词或副词。
 
使用状态副词加动词来表示完成某件事情的方式。
 

Martina works quickly. 	Martina 工作效率高。

She works well with the team.	她与团队合作得很愉快。

I highly recommend Martina.	我强烈推荐 Martina。

I'm going to miss her terribly. 	我将会非常想念她。

使用时间副词加动词来表示时间。
 

Her husband is already in New York.  	她的丈夫已经在纽约了。

She's leaving that soon?	她这么快就走了?

使用频率副词加动词来表示一个动作的频率。
 

 She was always organized.     	她一向都很有条理的。

使用可能性副词加动词来表示一个行动的可能性。
 

She can probably learn that in one or two days.   	她可能会在一或两天内知道。

您可以使用 only 加动词来把注意力集中到信息上。
 

 The project only took her one day.    	她可以仅用一天时间完成此项目。

您可以使用副词来修饰形容词。
 

The brochure was really beautiful.    	这本小册子真的很漂亮。

She's so creative.     	她真有创意。

有些副词修饰其他副词. 请注意 pretty 和 so 是如何给这些句子添加额外的细节的。
 

She can learn that pretty quickly.	她能领悟得相当快。

He writes so well.     
他写得真好。

您可以使用副词 honestly 在一个句子前边来强调强调某个要点。
 

Honestly, what are we going to do?    	说实话, 我们去干嘛? 

*** 撰写信件
    写一封介绍信

以下是一些在介绍信不同部分所使用到的表达式。

1. 日期及称呼

写信前先写日期

September 16, 2012

如果你知道收信人的名字，使用 Dear + 人的名字作为致敬语。
 
Dear Mr. Park,  	(敬爱的 Park 先生,)

如果您写一封普通的信，请使用：

To whom it may concern:   
(它可能会涉及到的人:)
2. 您为什么写

请使用这个段落格式来解释您为什么写：
 
I am writing to highly recommend Jacqueline Johnson. I worked with her for two years.	 	我正在写信，大力推荐 Jacqueline Johnson。我和她共事两年。

3.员工的品质及成就

在本段中，请写几个描述员工的品质和所取得的成就的句子。
 
Ms. Johnson was our chief designer. She was very creative. She also worked really quickly. Her last project only took her three days. It usually takes one week. Honestly, Ms. Johnson was the perfect employee.	 	Johnson 小姐是我们的首席设计师。她有很强的创造力，而且做事极快。她的上个项目只用三天就完成了。这通常需要一周时间。实话实说，Johnson 是员工的模范。

4. 结尾 – 联系信息及签名行

您可以用这句话来告诉他人您愿意进一步谈论某个员工：
 
Please feel free to contact me about Ms. Johnson at …     	
请随时在...与我联系谈论关于约翰逊女士

您可以用这个表达方式来正式地给一封信收尾：
 
Sincerely,          	
(诚挚地,)
      

把您的签名行 - 包括姓名，职务和公司 - 置于最下方：

Giovanni McKean
Vice President, Design
Imagicot

** unit 3
*** 动词过去时 
动词过去时
 
许多动词过去时只用在动词词尾添加 -ed 即可。 

walk - walked

clean - cleaned                                                        
 	 
不规则动词 
 
但是，一些最常用的动词都是不规则的，也就是说它们的过去形式不以 -ed 结尾。它们有多种不同的形成方式。 

have - had

make - made

eat - ate

drink - drank

let - let
*** 询问过去的事件/活动
    开放式问题一般更利于推动对话。它们让和你对话的人可以自由回答，回答方法也有多种。开放式问题主要分为两种：描述性问题和意见性问题。
 
描述性问题
 
What was it like?	（它什么样子？）
What was the wedding like?	婚礼是什么样子？
What did he look like?	他长什么样？
 	 
意见性问题
 	 
How did you like Beijing?	你有多喜欢北京？
How was your vacation?	你的假期怎么样？
How was Russia?	（俄罗斯怎么样？）
 
语言点：谨慎使用单词 like，该词有两种不同的意思。
 	 
描述：What was it like?	（它是什么样子？）
观点：How did you like it?	（你有多喜欢它？）
*** 不规则动词的过去时
    不规则动词过去时态
 
许多动词的过去时形式都是不规则的，也就是说它们的过去时形式不能通过简单在词尾添加 -ed 形成。
 
有些不规则动词的过去时和现在时截然不同，必须加以熟记。
 

steal - stole
go - went  	去                                                            

eat - ate  	吃

bring - brought  	带来

leave - left    	离开

sell - sold                         	卖

其他不规则动词的过去时形式只是改变了一个字母，因此更容易识记。
 

make - made	做

*rise - rose *	上升

get - got        	得到
 
一些动词的一般现在时和过去时的形式相同。
 

*cut - cut*   	切割

let - let 	让

*shut - shut*	关闭

动词 read 的一般现在时和过去时拼法相同，但读音不同。请听这两句中 read 的读音。
 

I often read novels.  	我经常看小说。

I read a good novel last week.	上周我看一本精彩的小说。
*** 开启对话
 
开启对话有多种方法。
 
一般性问题
 
如果没有想要谈论的话题，问候完后你可以使用一个常见的一般性问题。
 	 	 

How are you doing? 	你还好吗？

How are you today?  	你今天怎么样？

What's up?	你好吗？

What's happening?	在忙什么呢？

What's going on? 	发生什么事了？

How was your weekend?	你周末过得怎么样？
特定问题
 
你可以向你认识的人询问他们的生活。
 	 	 

How was Peru? 	秘鲁怎么样？

How is your mom feeling?     	你妈妈感觉怎么样？
 
陈述句 
 
在有些场合，你会有一个你想讨论的话题。你可以提出陈述，然后听众会对你的陈述发表意见。 
 	 	 

A: Hey, there was a great movie on last night.
B: Really? What was it? 	嗨，昨天晚上的电影很好看。
真的吗？什么电影？
 	 	 

A: That was a great game last night!
B: Yeah, it was really exciting! 	昨天晚上的比赛非常精彩！
是啊，真的令人兴奋！


 改变话题
 
对话从一个话题转到另一个话题，有一些表达可以帮助人们暗示他们要改变话题。
 
'By the way'
 
使用表达 by the way 来引入新话题，它也表示你刚想起了某事。 
 

A: By the way, I saw Joe last night. He looked good.
B: Really? I'm so glad!	对了，我昨天晚上见到 Joe 了。他气色看起来不错。
真的吗？我非常高兴！
 
'That reminds me'
 
当你想起了想说的其他事情，使用 that reminds me 来转变话题。 
 

A: There was a great baseball game on TV last night.
B: Oh, that reminds me. I have two tickets to tonight's game. Do you want to go?
A: Yeah!	昨天晚上电视上有一场精彩的棒球比赛。
哦，我想起来了。我有两张今天晚上比赛的票。你想去吗？
是啊！

'Anyway'
 
使用单词 anyway 来结束或总结话题，这样一来你可以开始一个新话题。当你听厌了某人谈论某事，非常想改变话题时，就可以使用这个词。
 

A: That restaurant wasn't very good.
B: No, it wasn't! The meat tasted bad, and the salad wasn't fresh. And the waiter was awful! His clothes were dirty!
A: Anyway, we're not going there again. So, how's Jane?	那家餐馆不是很好。
是啊，不怎么好！肉有味道，沙拉也不新鲜。而且服务员也很差劲！他的衣服很脏！
总之，我们不打算再去了。对了，Jane 还好吧？ 
*** 新闻词汇
 
新闻消息涵盖罪行、政治和商业等各种各样的话题。我们再次只关注 crime。以下是一些和 crime 相关的有用名词。
 
与罪行相关的名词
 

crime	犯罪案件                    

police 	警察

thief  	小偷

theft	盗窃
 	 	 
thief 是指犯偷窃罪的人，theft 则是偷窃这一事件。thief 一词的复数形式是不规则的：thieves。
 与罪行相关的动词
 	 	 
以下是一些和 crime 相关的有用动词。
 	 	 

break into   	闯入，破门而入

murder	谋杀

kill	杀死

arrest	逮捕

steal	偷盗
 
steal 是不规则动词，过去式形式是 stole。
*** 不定代词
 
有些代词并不指代某个已知的名词，它们就是不定代词，包括以下三个单词。
 

somewhere	
某处                                                            

someone	某人

something	某事   
 
使用 somewhere 谈论不确定的地点。
 

John lives somewhere in Tokyo. I don't know his address.	John 住在东京的某个地方，我不知道地址。
 
使用 someone 谈论不确定或不知道的人。
 

Someone stole a painting from the museum.     	有人从博物馆偷了一幅画。
使用 something 谈论不确定的事物。
 

The thief stole something from the woman's bag.  	小偷从那位女士的包里偷了什么东西。
 
语言点：单词 somebody 与 someone 意义相同。
*** 排列叙事顺序
    故事排序
 
在讲故事或写故事时，将事情发生的顺序理清很重要。理清顺序有几种方法。
 
如果你描述的事情在另一件事情一天之后发生，使用短语 the next day。
 

They stole 15 computers on Friday night. The next day, the police came.
 	他们周五晚上偷了 15 台电脑，第二天来了警察。
 
要表示一件事情在某事多久之后发生，使用数字 + 时间单词 + later。
 

There was a theft on Friday night. Three days later, we hired a security guard.
 	周五晚上发生了盗窃。三天后，我们聘请了一名保安。


向他人讲述某件发生的事情，你也可以使用本课中之前学到的时间表达。
 

The theft was three days ago.	盗窃发生在三天前。

They broke in last Friday.	他们上周五闯了进去。      

They stole money the day before yesterday.	他们前天偷了钱。
*** 预览新闻文章

随着你的英语更加熟练，你将开始阅读难度更大的文字，比如新闻和杂志文章。这时培养理解这些文字的策略很重要。一种有用的策略是在开始阅读故事前先预览或通看整篇文章。以下是一些具体步骤，将让你的阅读更加具有效率。


标题

标题以一种特有的简短英语形式撰写，因此起初可能会难以理解。例如，标题 U.K., U.S. Talk Trade 表示英美两国协商贸易问题。由于标题涵盖文章大意，尤其应该引起你的注意。


照片和插图

照片和插图置于文中，可以让文章更容易理解，增加阅读趣味。慢慢仔细观看照片和图片。如果图片配有文字说明，阅读这些说明，获取更多有关图片和故事的信息。
导语

新闻文章的第一段称为导语，通常包含该新闻最重要的细节。导语常常引出人物、时间、时间和地点，有时也会介绍方式和原因。由于导语信息充分，因此你应该密切关注。


新闻来源

在文章上方，你可能看到至少下列一项：署名行（记者姓名）、日期栏（记者发稿的城市）和通讯社的名称。有时通讯社的名称见于括号中 (Global News)，有时缩写为 (GN)。
 
** unit 4 重大事件
*** 一生中的大事
 
请用这些词来谈谈一生中的大事
 	 
             动词	             名词

be born	出生

birth	出生

graduate	毕业

graduation	毕业

marry	结婚	

marriage	婚姻

get promoted	升职

promotion	升职

retire 	退休	

retirement	退休

die	去世

death 	死亡


其中三个单词具有形容词形式。
 	 	 
             形容词

married	已婚

retired  	退休的

dead	过世了

一生的大事中所用到的'Get'
 
请用 get 与这些词语谈谈关系的里程碑。
 

get married	结婚

get pregnant	怀孕

get divorced	离婚

get over a relationship	走出一段感情

请用 get 与这些词谈谈生活及事业的里程碑。
 

get a degree	获得学位

get a job	得到一份工作

get promoted	升职

get fired	被解雇

get a driver's license	考取驾照

get old	变老
*** when' 引导的从句
 
由 'when' 引导的从句为句子补充有关时间的信息。
 

When I was young, we didn't sit around all day texting.	 	在我年轻的时候，我们不会整天坐着发短信。

Do you remember when we bought that house on Oak Street?	 	你记得 Oak Street 街上的那所房子我们什么时候买的吗？

She spent a lot of time in her car when she first got her driver's license.	 	她刚拿到驾照时很多时间都呆在车里。
 	 
如果由 'when' 引导的从句起句，则用逗号 (,) 与句子其余部分分隔。如 'when' 引导的从句位于结尾，则无需使用逗号。
*** 
更多人生事件
 
人一生中总会发生各种大事。想想自己人生中发生的大事。这些事情发生了吗？什么时间发生的？如果没有，你认为什么时候会发生？
 

I first traveled abroad when I was 15.	（15 岁时，我第一次出国旅行。）
 	 	 

I got my first car when I was 17.  	（17 岁时，我买了第一辆车。）
 	 	 

I moved out of my parents' house when I was 18.	（18 岁时，我搬出了父母的房子。）
 	 	 

I moved away from home when I was 18.   	（18 岁时，我离开了家乡。）
 	 	 

I got my first apartment with my best friend. 	（我和我的好朋友找到了我的第一间公寓。）


I met the love of my life when I was 22.	（22 岁时，我遇到了一生中的挚爱。）
 	 	 

We fell in love and got married.	（我们相恋，然后结婚。）
 	 	 

We had our first child when I was 25.	（在我 25 岁时，我们有了第一个孩子。）
 	 	 

We had our first grandchild when I was 46.	（在我 46 岁时，我们有了第一个孙儿。）
*** after' 引导的从句
 
与 'when' 引导的从句一样，由 'after' 引导的从句也为句子补充有关时间的信息。
 

After I moved out of my parents' house, I got my first apartment.	（在搬出父母的房子后，我找到了自己的第一间公寓。）

I got my first apartment after I moved out of my parents' house.	（在搬出父母的房子后，我找到了自己的第一间公寓。）
 	 	 
与 'when' 引导的从句一样，如果句子以 'after' 引导的从句起句，则用逗号 (,) 与句子其余部分分隔。如 'after' 引导的从句位于结尾，则无需使用逗号。
*** 面试
appointment
约会

resume
简历

candidate
候选人

position
职位，工作

opportunity
机会

strengths
长处

background
背景

team
团队

What are your strengths?	你有什么优点？


What is your greatest weakness?	你最大的缺点是什么？

Tell me about your work background.	跟我说说你的工作经历。

What is your greatest weakness?	你最大的缺点是什么？

Tell me about your work background.	跟我说说你的工作经历。


面试相关的表达
 
当你到达面试地点时，先表明你来的原因。然后，感谢面试人的接见。
 

I have a 3 o'clock job interview with Ken Smith. 	我三点钟和 Ken Smith 有一个工作面试。

Thank you for seeing me, Mr. Smith.	谢谢您见我，Smith 先生。

Thank you for the opportunity to meet with you.	谢谢您给我见您的机会。

面试人将就你的简历提出一些后续问题。请相应回答。
 

Interviewer: I see that you got your MBA from The Wharton School.	我看到你获得了沃顿商学院的 MBA 学位。
Candidate: Yes, it was a wonderful program.	是的，这是一个非常好的项目。
 	 	 

Interviewer: I see that you're currently working at DBX Systems. Why are you thinking of leaving?	（我看到，你目前在 DBX Systems 公司就职。为什么想离开？）
Candidate: Well, to be honest, the work isn't very challenging.	（哦，坦白来讲，这份工作并不难。）

谈论你的缺点时，一个策略是从正面角度入手，比如工作太拼命，让缺点不成为缺点。
 

Interviewer: What do you think are some of your strengths and weaknesses?
（你认为你有什么优点和缺点？）
 
Candidate: Well, I am a very hard worker, but sometimes I work too much.
（嗯，我工作非常勤奋，但有时候工作太拼命。）

如果面试人认为你是潜在的人选，他或她可能会讲述之后的步骤，甚至询问你的入职时间。
 

Interviewer: I'd like you to talk with some other members of the team. Also, are you OK with the start date?
（我想让你和团队的其他成员谈谈。还有，入职时间你觉得可以吗？）	 
 
Candidate: That sounds great and, yes, the start date works for me. Thank you again for meeting with me.
（听起来不错，可以，入职时间我觉得没问题。再次感谢您与我见面。）
*** 省略形式
 
英语为母语的讲话人与人交谈时，并不总是把每个词的每个音都发出来。尤其元音常常会缩短或省略。这些省略形式在标准英语中并不会出现。但是，当你听到它们时，重要的是能够进行辨认。
 	 
请听省略形式。注意它们书写和发音的不同之处。
 	 

What do you think?  

Where did you work?  

When do you study?  

Why did you leave?  

How do you like it?  
*** 使用 just 表示最近的过去

使用 just + 动词谈论刚刚或最近完成的行动。
 

Zach and I just bought a house. 	（我和 Zach 刚买了房子。）                           

Carla just got promoted.	（Carla 刚刚升职。） 
*** 开启和改变对话话题

你可以使用 Guess what? 来引出或改变话题。
 	 

A: Hey, Daniel. How's it going?
B: Good. Guess what?
A: What?
B: I just got a promotion.	你好，Daniel。最近好吗？
还好。猜猜怎么着？
怎么了？
我刚刚升职了。
 	 	 
记住，你可以使用 that reminds me 或 by the way 转到与当前话题相关的话题。
 	 

A: I just had my 33rd birthday! 
B: Well, happy birthday! Hey, that reminds me. Do you want to come to my son's birthday party?	我刚过了 33 岁生日。
哦，生日快乐！嗨，这想起来了。你想参加我儿子的生日派对吗？
 	 

A: Wow! This pizza tastes amazing. 
B: It sure does. By the way, I'm having pizzas and movies at my house on Saturday.	哇！这个披萨味道真好。
的确不错。对了，星期六我打算在家吃披萨看电影。
*** 可能性副词

可能性副词表示某事发生的相对可能性。
 
副词通常直接位于其修饰的动词之前，如果是 be 动词，则位于其后。maybe 是例外，常常位于句首。
 
表示百分之百的可能性，使用 definitely 或 absolutely。
 

I definitely saw Sheila at the party.	（我肯定在派对上看到了 Sheila。）                    

Lucille absolutely can't come.	（Lucille 绝对不能来。）

表示较大的可能性，使用 probably。
 

They are probably late.	（他们很可能迟到了。）

Dylan probably brought drinks.	（Dylan 很可能带了酒水。）

They probably can't buy snacks.	（他们很可能不能买零食。）
表示较小的可能性，使用 maybe。注意该词用于句首。
 

Maybe we can have a surprise party.	（我们也许可以办一个惊喜派对。）

A: Is Rhonda coming?
B: Maybe not. She's still working.	Rhonda 来吗？
（可能不来，她还在工作。）

表示非常小的可能性，你可以使用 unlikely。
 

A: Is Grandma coming to the celebration?
B: It's unlikely. She's not feeling well.	祖母 外婆 来参加庆祝活动吗？
（不大可能。她身体不舒服。）

你可以在一个单词的回答中使用可能性副词。
 

A: Are you inviting Dylan?
B: Definitely.	你请 Dylan 吗？
（当然！）

A: Can I see you tonight? 
B: Maybe.	我今晚能见你吗？
（可能吧。）

提出及回应邀请	 
 	 
使用类似这些表达提出邀请。提出邀请前，先具体说明邀请的场合是有好处的。	 
 	 

We're having some people over next weekend. Kelsey and I are hoping that you and Cody can come.	 	我们下周末打算邀请一些人到家里来。Kesley 跟我都希望你和 Cody 能来。	 
 	 	 	 	 

I'm having a birthday party for Tyler in two weeks. I'd like you to come.	 	两周后我要为 Tyler 办生日派对。我希望你能来。	 
 	 	 	 	 

Are you free Friday night? Would you like to come to a housewarming?	 	你周五晚上有空吗？你想来参加暖屋派对吗？	 
 	 	 	 	 

We should get together for dinner this week. What does your schedule look like?	 	我们本周应该聚在一起吃顿饭。你的日程怎么样？

接受或讨论邀请，使用类似的表达：	 
 	 

Great! I'm definitely coming.	 	太棒了！我一定来！	 

We can probably come. Let me talk to Dave about it.	 	我们很有可能来。让我跟 Dave 说说。	 

Thanks – I'd be delighted.	 	谢谢 – 荣幸之至。	 
 	 	 
谢绝邀请，使用类似这样的表达：	 
 	 	 	 	 

Sorry – Chelsea probably can't come. She has a cold.	 	抱歉 - Chelsa 很可能来不了。她感冒了。	 

Oh, that weekend's no good. Sorry!	 	哦，这个周末不行。对不起！	 

Thanks - I'd be delighted.
谢谢 – 荣幸之至。
*** 欢迎客人
    使用类似这样的表达欢迎客人：
 

Welcome! 	欢迎光临！

Hi! It's so good to see you.	嗨！很高兴见到你。

I've missed you!	我好想你！
 
使用类似这样的表达邀请客人进到你家里：
 

Come in!	请进！

Make yourself at home.	不要客气。

Please make yourselves comfortable. 	请不要拘束。
使用类似的表达让客人感到自在：
 

Can I take your coat? 	我帮你拿外套吧？                      

You can put your things over here.   	你可以把你的东西放在这里。

Can I get you something to drink? 	想喝点什么吗？
 
客人落座后，你可以提出类似这样的问题，礼貌地对话：
 

How was your trip? 	旅途怎么样？

How was traffic?	交通状况如何？
*** 形容词搭配不定式

你可以使用形容词 + to + 动词解释情感和状态。
 

I'm happy to hear that you like Korean food.	（我很高兴听到你喜欢韩国菜。）            

I was surprised to get the promotion.	（我很惊讶获得升职。）

So good to see you!	（很高兴见到你！）

Amy's ready to eat dinner.	（Amy 准备好吃饭了。）
*** 礼貌地提议和请求
提供东西和提出礼貌的请求

使用 would you like 礼貌向客人提供某物。
 

Would you like something to drink?	你想喝点什么吗？                            

Would you like to have a seat?	（你想坐下吗？）
 
使用 could 或 may 向主人提出礼貌的请求
 

May I use the restroom?	我可以用一下厕所吗？

Could I have some water?	我能喝点水吗？
 
语言点：在美式英语中，restroom 是家中厕所非常礼貌的称法，Bathroom 相对礼貌，toilet 不礼貌。在英式英语中，toilet 是家中厕所非常礼貌的称法，Loo 是可以接受的用法，但只限于非正式场合和熟悉的人。
*** 听到好消息和坏消息的反应

听到好消息时，使用类似这样的表达作出反应。
 

Congratulations!	恭喜！

Really? I'm so happy for you!	真的吗？我为你感到非常高兴！

That's great news!	这消息太棒了！
 
喝酒时，你可以说 to your 和 to your 来祝酒。
 

To your new job! Cheers!	（为你的新工作！干杯！）

To your new baby. Cheers!	（为你的新生宝宝干杯！）

听到坏消息时，使用类似的表达作出反应：
 	 

A: Sorry – the sofa is not very comfortable.
B: That's OK.	对不起 - 沙发不是很舒服。
没关系。
 	 	 

A: I just got fired.
B: That's terrible! I'm so sorry to hear that.	我刚被解雇了。
太糟糕了！听到这个我感到很抱歉。
 	 
听到好消息和坏消息时，你都可以使用 it's crazy。
 	 

I was surprised to get this great promotion. It's crazy.	（这次得到升职，我感到很吃惊。不可思议。）

It felt terrible to get fired. It's totally crazy.	（遭到解雇感觉糟透了。这简直不可思议。）
*** 形容词同义词

使用同义词或具有相同意义的单词，可以让你的英文更富于乐趣和变化。学习同义词也是识记新词的一种好办法。
 
以下是一些有用的形容词同义词：
 

great - wonderful - delightful       	好的 / 极好的 / 令人高兴的                           

fun - enjoyable	令人愉快的 / 令人愉快的

happy - glad - pleased     	高兴的 / 乐意的 / 喜欢的

beautiful - lovely - gorgeous 	美丽的 / 可爱的 / 迷人的

delicious - tasty - yummy  	美味的 / 可口的 /好吃的
*** 美式英语和英式英语

美式英语和英式英语在发音、词汇、表达、拼写和语言等方面存在诸多不同。这些差异不一定很明确，但碰到时如果能够辨识也很重要。

发音
 
下为美式英语和英式英语中音节重读差异的一个例子。
 

American: caFE	咖啡馆

British: CAfe


词汇
 
下为一些词汇差异的例子。
 

American: gas	（汽油）

British: petrol
 	 	 

American: restroom	（厕所）

British: toilet
 	 	 

American: cellphone	（手机）                                         

British: mobile
 

表达
 
虽然这些短语中的第一个在美式和英式英语中都可以使用，但 spot on 多在英式英语中使用。它们的意思相同。
 

American / British: That's exactly right!	（确实如此!）

British: Spot on!
 	 
语法	 
 	 
你在英美两国都能听到这些疑问句结构。但是，do you have 多用于美国，have you got 则多用于英国。	 
 	 

American: Do you have a pen?	你有笔吗？	 

British: Have you got a pen?	 
*** 离开某人家时
Have you got everything?
你东西都拿了吗？

Your shop's really lovely.
你的店真的很迷人。

We had a great time.
我们过得很愉快。

You must come to us next time.
你下次一定要来我们家。

It was lovely to see you again.
很高兴再次见到你。

当你离开某人家时，使用类似这样的表达：
 

The party was wonderful. 	派对很精彩。

We had a great time.  	我们过得很愉快。

It was so nice to see you again.  	很高兴又见到你。
 
你的主人也许会检查确认你没有遗忘东西。
 

A: Do you have everything? 
B: I think so. 	你东西都拿了吗？
我想是的。
 	 	 

A: Have you got everything? 
B: Yes, I have, thanks.	你东西都拿了吗？
是的，我都拿了，谢谢。

你可以邀请主人将来到你家拜访。这里的第一个例子更接近美式英语，第二个例子更接近英式英语。
 

Next time, it's our turn to host.              	下次我们来办。

You must come to us next time.	你下次一定要来我们家。
 
人们在听到这些句子后通常会表示感谢。
*** 'Hope to' 和 'hope that'
Hope to' 和 'hope that'

使用 Hope to 和 hope that 谈论你希望发生的事情。注意，Hope to 后接动词原形，hope that 后接从句。
 

I hope to see you again soon.                    	我希望不久后能再见到你。                  

I hope that I see you again soon. 	我希望我不久后能再见到你。
 
在英语口语和书面语中，单词 that 有没有都可以，在句中省略不会影响句子意思。
 

I hope I see you again soon.
我希望我不久后能再见到你。
 
使用 I hope so, too 肯定应答 hope to 或 hope that 的句子。
 

A: I hope to see you again soon.                
B: I hope so, too. 	我希望不久后能再见到你。
我也这样希望。
*** 谈论有趣的活动
使用下列表达谈论有趣的活动：
 

I had a really good time.	我过得很愉快。                               

I really enjoyed myself.	我玩得非常开心。

It was great!	非常棒！

I had a lot of fun.	我玩得很高兴。
 
如果你表达了这样的感觉，你的主人一般会向你表示感谢。
*** 撰写感谢信
 
下为撰写感谢信的一些步骤。
 
先写日期。
 
September 16, 2012
 
问候收信人，使用 Dear + 姓名，后接逗号 (,)。
 
Dear Andy,  	（亲爱的 Andy，）
 
对收信人表示感谢，提及感谢的原因。
 
Thank you for inviting me to your party.
Thanks for the wonderful gift.	（谢谢你邀请我参加派对。）
（谢谢你送的精美礼物。）
 
恭维收信人
 
The food at the party was delicious.  
Your home is lovely.    
The scarf is beautiful.	（派对上的食物很好吃。）
（你的家很迷人。）
（围巾很漂亮。）
 
提及你对未来见面的期待。
 
I hope to see you again soon. 
I hope that you can visit me soon.	（我希望不久后能再见到你。）
（我希望你不久后能再来我家。）
 
结语和签名。
 
Sincerely, 	（此致）
Jane   
** unit 6
*** 谈论天气、季节和温度
 
描述一个地方的天气和气候有多种方法。

你可以描述天气和温度。
 

It's often windy.	常常刮风。

It's so cold and cloudy.	天很阴，又很冷。

It gets to 115 degrees Fahrenheit. That's, like, 46 degrees Celsius!	温度达到华氏 115 度，相当于 46 摄氏度。

你可以使用表达感觉和观点的形容词。
 

Fall is perfect.	秋天很美。

Winter is terrible.	冬天很糟。

It's lovely in spring.	春天真美。  

你可以比较时间、地点和环境。
 

It gets cooler at night.	夜晚天气变得更凉爽。

It's nicer here than in the desert.	这里比沙漠更好。

It's hot in summer and cold in winter.	冬冷夏热。
*** 阅读策略
 
在阅读第二语言时，你可能会碰到不熟悉的单词和表达。要解决这一问题，一种策略是通过阅读前后的单词和句子得出生词的意思。你常常会在生词附近的上下文中找到它的同义词和反义词、定义和解释。

在下面的第一个句子中，你看到单词 waterfall。紧接着下一句你就会读到解释：water from the Paine River falls beautifully into Pehoe Lake，你可以用这来猜测单词 waterfall 的意思。

Take a hike to Salto Grande waterfall. There, water from the Paine River falls beautifully into Pehoe Lake.  
*** 询问和介绍地点的信息
 
询问他们是否喜欢自己的家乡，是鼓励他人谈论其家乡的一种方法。
 

A: Where are you from?	你来自哪里？
B: I'm from Ottawa.	我来自渥太华。
A: Do you like it there?	你喜欢那里吗？
B: Oh, yeah. There are fantastic museums and festivals.	哦，是的。那里有许多很好的博物馆和节日。
 询问某件具体的事情，你可以使用表达 What's the + 名词 + like?。记住，这里的 like 不同于 Do you like ...? 中的用法。
 

A: What's the weather like in your hometown?	你的家乡天气什么样子？
B: It's cold and snowy in winter. It gets to -30 degrees. But it's warm in summer and fall.	冬天寒冷，还会下雪。温度降到零下 30 度。但夏天和秋天很暖和。
 	 

A: What's the food like in Ottawa?	在渥太华都吃什么？
B: Well, we eat a lot of fish. And poutine is popular. It's special french fries with cheese.	嗯，我们常常吃鱼，奶酪蘸番茄酱薯条很受欢迎。这种薯条搭配奶酪，很特别。
 

A: What are the people like?	人都怎么样？
B: Many people are university graduates and can speak English and French.	许多人读过大学，会讲英语和法语。
*** 度假活动
'Be' + 'going to' 表示计划, 'will' 表示预测
 
使用 be + going to + 动词谈论未来确认的计划或打算。
 

A: What are you going to do on vacation?
B: I'm going to visit friends and family. And I'm not going to work.	你假期打算做什么？
我打算去探望朋友和家人。我不打算工作。

使用 will + 动词表示你预计或认为会发生的事情。在英语口语中，代词和动词通常缩写。
 

We'll probably stay in a hotel.	我们可能会呆在酒店。

I'll be happy living by the sea.	（我会很高兴住在海边。）

You'll like Paris.	（你会喜欢巴黎的。）

如果动词和代词不缩写，通常是为了表示特意的强调。
 

You will have fun.  	（你会玩得开心的。）

We will not fight.      	（我们不会打架。）

表达否定意义，使用 will + not + 动词，缩写形式为 won't。
 

I won't get sick. 	（我不会生病。）

They won't come with us.  	（他们不会跟我们来。）

要确定时间，你可以添加表示将来的时间表达：
 

I'm going to go horseback riding on Thursday. 	（星期四我打算去骑马。）

The next two days will be an adventure. 	（接下来两天将是一场冒险。）
*** 表达疑虑
 
使用类似下面的表达表示疑虑。注意语调的变化如何加深说话人的疑虑程度。  
 

Are you sure about that?	那你确定吗？

If you say so. 	既然你这么说。

表达疑虑还有一种方法，就是重复或反驳某人刚说的话。再次注意表示疑虑的人的语调。
 

A: I'll probably go to the spa tonight.
B: The spa?   	我今晚很可能会去水疗中心？
水疗中心？

A: We're going to travel through Europe this year.
B: You're not going to Asia?	我们今年打算环游欧洲。
你不打算去亚洲吗？

语言点：注意这些表示疑虑的表达的使用方式和对象。比如，跟老板说 If you say so 可能不大好！
*** 用 'Will' 表达提议或主动做某事
 
使用 will + 动词提议或自愿在不久或更远的将来做某事。 
  

Let's go to Istanbul. I'll make the plane reservations right now.	（我们去伊斯坦布尔吧。我马上订机票。）

I'll drive you to the airport next week, if you want.	（如果你愿意，下周我开车送你去机场。）

使用 will + 动词提出非正式请求。
 

A: When I go on vacation, will you take care of my dog?
B: Sure, I'll take care of little Sammie.	（我去度假期间，你帮我照顾狗，好吗？）
（没问题，我帮你照顾小 Sammie。）

你可以使用 will not 谢绝请求，但务必谨慎使用：可能显得过于直接，可能会让人不高兴。
 

A: Will you get my luggage?
B: No, I won't.	（你帮我拿行李，好吗？）
（不，我不行。）
*** 告别语
 
当某人出发旅行时，使用类似这样的表达送别：
 

Have a great trip! 	旅途愉快！

Drive safely!   	小心驾驶！

Have a good flight.  	坐飞机一路愉快！

Call me when you get there. 	到了打电话给我。

Don't worry about anything.	什么都不要担心。

当某人出发旅行时，你可以使用短语 Bon voyage!，该短语直接源于法语。
 

A: OK, then. I'm going.	好吧。那我走了。
B: Bon voyage! 	一路平安！
*** 
动词 'try'、'remember' 和 'stop'
 
动词 'try'、'remember' 和 'stop' 的意义会根据后接动词的形式而改变。
 
'Try'
 
当动词 try 后接不定式 （to + 动词） 时，例如 to buy，表示试图做某事。

I can't go to the mall. Maybe I'll try to buy something online.          	（我不能去商场。也许我会试着网上购物。）
 	 	 
当动词 try 后接动名词时 （动词 + -ing），例如 swimming，表示第一次做某事，或尝试做不同的事情。

I don't like biking. Maybe I'll try swimming on my vacation.	（我不喜欢骑自行车。也许假期我会试着游游泳。）


'Remember'
 
当动词 remember 后接不定式时，例如 to call，表示记得去履行一项职责或任务。

I always remember to call my mother on Sunday.	我星期天总是记得打电话给我母亲。
 	 	 
当动词 remember 后接动名词时，例如 calling，表示记得过去做过某事。

I remember calling the neighbors.	（我记得给邻居打电话了。）
 	 	 
'Stop'
 
当动词 stop 后接不定式时，如 to eat，表示停止一个动作，开始另一个动作。在本例中，这个人在工作，但停下工作吃东西。

I stopped to eat when I got hungry. 	当我饿的时候，我停下来去吃了点东西。
 	 	 
当动词 stop 后接动名词时，如 eating，表示一个中止的动作。

I stopped eating when I felt sick.	（我感觉恶心，停止了吃东西。）
*** 省略形式

记住，在英语口语中，每个词的每个音并不是总要发出来。尤其是元音常常缩短或是省略。这些形式很少在书面英语中使用，但听到时能够辨识很重要。

请听 going to、have to 和 want to 的省略形式。注意它们书写和发音的不同之处。
 
'Going to'

We're going to fly to Hawaii.	我们打算坐飞机去夏威夷。

I'm going to call my mom. 	我打算打电话给我妈妈。

It's going to rain. 	要下雨了。

She's going to play computer games.
她打算玩电脑游戏。

'Have to'

I have to go.	我得走了。

We have to be quick.	我们不得不快点。

She has to leave.	她不得不离开。

He has to get up early.
他不得不早起。

'Want to'

I want to go to bed.	我想上床睡觉。

Do you want to go to the movies?	你想去看电影吗?

She wants to eat out.	她想出去吃饭。

He wants to go home.
他想回家。

注意，如果主格代词是 he、she 或 it，have to 和 want to 的口语省略形式会改变，但 going to 的省略形式保持不变。
*** 与度假相关的动词
visit
拜访

relaxing
使人轻松的

eating out
外出用餐

took a tour
参观

lost his passport
遗失了他的护照

stay in London
在伦敦逗留

embassy
大使馆

I hope our money lasts.
我希望我们的钱够用。
*** 用 So 来描述结果
 
你可以使用 So 来描述某一行动或时间的结果。注意，原因(he lost his passport)位于结果之前(he went to the embassy)。
 

Shawn lost his passport, so he went to the embassy.  	（Shawn 遗失了他的护照，所以去了大使馆。）

注意：So 用于引出结果，because 用于引出原因。观察以下句子的不同之处：
 

Emily recommended Corcovado, so we went there. 	（Emily 推荐基督山，所以我们去了那里。）

We went to Corcovado because Emily recommended it.	（我们去基督山，因为 Emily 推荐了那里。）
*** 表达目的
 
使用 in order to + 基本动词表达目的。如果 in order to + 从句位于句子主句之前，使用逗号；如果位于主句之后，则不必使用逗号。
 

In order to reserve our room, I called the hotel.	（为了预订房间，我们打电话到酒店。）
I called the hotel in order to reserve our room.
 	 	 
你可以完全省略 in order，只用 to。事实上，to 使用更加普遍，在英语口语中尤其如此。
 

Courtney went early to avoid the crowds.	（Courtney 为了躲开人流早早就去了。）


你也可以使用 so that + 从句表达目的。如果位于主句之前，则在 so that 从句之后使用逗号，如果位于主句之后则不必使用逗号。
 

I turned off my phone so that I could relax.      	（我关了手机，以便能够休息。）
So that I could relax, I turned off my phone. 
 
你可以省略 that，只是用 so。
 	 	 
 	I saved my money so I could visit Terry.	（我省钱，以便能够去看 Terry。）



I need to arrange accommodation at my destination before I leave.

I need to take some business cards to give to clients and colleagues.
*** 使用恰当的语体
 
写信时使用正确的语体很重要。以下开头和结尾的一些正式和非正式表达。

非正式开头
Dear Kim,  
Hi, Mom!  	（亲爱的 Kim，）   
（嗨，妈妈！）                                                        

非正式结尾
Love,  
Take care.
See you soon.	（爱你的，）
（保重。）
（再见。）

正式开头
Dear Ms. Tackett,  
To whom it may concern:  	（亲爱的 Tackett 小姐，）
（敬启者：）

正式结尾
Sincerely yours,   
Best regards,  	（谨上，）
（此致，）
** Word
 | En                     | Zh                                                                     |
 |------------------------+------------------------------------------------------------------------|
 | events                 | 演出                                                                   |
 | concert hall           | 音乐厅                                                                 |
 | auditorium             | 礼堂                                                                   |
 | check it out           | 检查,仔细查看                                                          |
 | band                   | 乐队                                                                   |
 | nightclub              | 夜店                                                                   |
 | traditional            | 传统的                                                                 |
 | stadium                | 体育馆                                                                 |
 | aquarium               | 水族馆                                                                 |
 | wedding anniversary    | 结婚纪念日                                                             |
 | picnic                 | 野餐                                                                   |
 | admission              | 入场费                                                                 |
 | Central                | 中心的；主要的；中枢的                                                 |
 | Orchestra              | 管弦乐队；乐队演奏处                                                   |
 | concert                | 音乐会                                                                 |
 | soccer                 | 英式足球, 足球                                                         |
 | incredible             | 难以置信的，惊人的                                                     |
 | festival               | n. 节日；庆祝，纪念活动；欢乐 adj. 节日的，喜庆的；快乐的              |
 | horror                 | 恐怖的                                                                 |
 | drama                  | 剧情,戏剧                                                              |
 | comedy                 | 喜剧                                                                   |
 | curly                  | 卷发                                                                   |
 | bald                   | 秃顶的, 光秃的, 单调的                                                 |
 | straight               | 秃顶                                                                   |
 | blond                  | 金发的                                                                 |
 | colleague              | 同事                                                                   |
 | cousin                 | 表(堂)兄妹                                                             |
 | nephew                 | 侄子                                                                   |
 | performance appraisals | 绩效评估                                                               |
 | organized              | 有条理的                                                               |
 | gorgeous               | adj. 华丽的，灿烂的；极好的                                            |
 | brochur                | 小册子                                                                 |
 | sinceraly              | 诚挚的                                                                 |
 | iron                   | 熨, 熨斗                                                               |
 | dishes                 | n. 菜肴；餐具（dish 的复数）                                           |
 | jogging                | n. 慢跑 v. 慢跑（jog 的 ing 形式）；轻推；唤起                         |
 | spaghetti              | n. 意大利式细面条                                                      |
 | robbery                | 抢劫                                                                   |
 | crime                  | 犯罪案件                                                               |
 | upset                  | vt. 使心烦；颠覆；扰乱 adj. 心烦的；混乱的；弄翻的 n. 混乱；翻倒；颠覆 |
 | gallery                | 画廊. 走廊, 在..挖地道                                                 |
 | supervisor             | n. 监督人，[管理] 管理人；检查员                                       |
 | delighte               | adj. 高兴的；欣喜的 v. 使…兴高采烈；                                   |
 | dessert                | 饭后甜点                                                               |
 | delightful             | 令人高兴的                                                             |
 | gorgeous               | 迷人的                                                                 |
 | yummy                  | 好吃的                                                                 |
 | desert                 | 沙漠                                                                   |
 | coast                  | 海岸                                                                   |
 | hills                  | 小山, 山丘                                                             |
 | valley                 | 山谷, 溪谷, 流域                                                       |
 | ocean                  | 海洋, 海                                                               |
 | beach                  | 海滩                                                                   |
 | forggy                 | adj. 有雾的；模糊的，朦胧的                                            |
 | horseback riding       | 骑马                                                                   |
 | sightseeing            | 游览                                                                   |
 | diving                 | 潜水                                                                   |
 | bon voyage             | 一路平安                                                               |
 | itinerary              | n. 旅程, 旅行日程     adj. 旅程的                                      |
 | accommodation          | n. 住处，膳宿；调节；和解；预订铺位                                    |
 | Reservation            | n. 预约，预订；保留                                                    |
 | umbrella               | 雨伞                                                                   |
 | sightseeing            | n. 观光 v. 观光 adj. 观光的                                            |
 |                        |                                                                        |


* level 3
** unit 1
*** 现在完成时

用现在完成时表达在过去的一个时间（未具体说明）完成的事对现在有影响。用 have + 过去分词构成现在完成时。
 

I have printed my boarding pass.	我打印了我的登机证。

She has lost her ticket.	她弄丢她的票了。

用 have not 和 has not 造否定句 ，在英语口语中使用 haven't 和 hasn't 缩写形式，除非你很强调 not。
。
 
I have not lost my passport.	我没有弄丢我的护照。
Joseph hasn't lost his passport.	约瑟夫没有弄丢他的护照。

have + 主语 + 过去分词来造一个现在完成时的问句。也请注意回答的缩略形式。
 
A: Has she packed her bags?
B: Yes, she has.	她收拾了行李了吗？
是的。
 	 	 
A: Have the Taylors bought their tickets? 
B: No, they haven't.	泰勒一家买票了吗？
不，他们还没有。
*** 提出不同的选择
You basically have three options.
你主要有三个选择。
You can take a taxi.
你可以坐的士。
There are also buses to downtown.
也有去市中心的巴士。
You could take the express train.
你可以坐特快列车。
Would a taxi be the fastest?
的士是最快的吗？
The best choice for you is ...
你最好的选择是……


 使用类似这些表达，告诉他人有多少种选择。
 
There are several options.	有几种选择。
You have four options.	你有四种选择。
 	 	 
使用 can 和 could 给予建议。
 	 	 
You can take the shuttle.	你可以乘坐机场大巴。
You could take a taxi.	你可以乘坐出租车。
 

使用类似这些表达，在众多选择中给出最佳方案。
 
Your best option is to go by subway.	你最好搭乘地铁。
Your best bet is to take the express train.	你最好搭乘特快列车。
A rental car would be the cheapest option.	租车是最便宜的选择。

省略形式
 
记住，在英语口语中，单词的每个音素并非始终发音。尤其是元音常常缩短或省略。这些形式在书面英语中并不使用，但听到时要能够辨认，这非常重要。
 
请听 have to 的省略形式。注意书面和口语中不同的书写形式。Have to 听起来像 'hafta'，Has to 听起来像 'hasta'，Had to 听起来像 'hadta'。
 
Have to
 
They have to take a taxi.
I have to catch the express train.
Do you have to rent a limousine?


Has to
 
She has to wake up early and get on the subway.
The bus driver has to wait for those passengers.
Karl has to get his rental car.
 	 
Had to
 
I had to find the subway station.
He had to walk.
Lisa had to take a morning flight.
*** 过去分词
记住用这些过去分词构成现在完成时。同时记住，谈论发生在过去某个不确定的时间的事情时，使用现在完成时。
 
肯定陈述	否定陈述	疑问句
have + 过去分词 	haven't + 过去分词	Have + 主语 + 过去分词 + ?
 
A: Have you been to Bolivia?
B: No, I haven't been there before.	你去过玻利维亚吗？
没，我从没去过。

语言提示：在美国英语，I've got 表示持有，就像 I've got my ticket. 。说 I've gotten a ticket. 意味着你已经得到或买到一张票。在英国英语，got 都可以用于两种情况。
*** 国外旅行
How was your flight?
你的飞行顺利吗？
change planes
转机
customs
海关
immigration
移民
jet lag
时差
Back home, it's about 2 p.m.
在国内，现在是下午两点左右。
unfortunately
不幸地
dinner on the plane
飞机餐食
I'm buying.
我来买。
*** 现在完成时使用的副词
 
用副词 yet, already, never 和 ever 在现在完成时中表示从过去直到现在的一段时间。
 
'Yet'
 
用副词 yet 表示某事尚未发生，或询问某事是否已经发生。该副词常放在句尾。
 
I haven't printed my boarding pass yet.	我还没有打印登机牌。
They haven't packed their bags yet.	他们还没有收拾行李。
Has she left for the airport yet?	她已经出发去机场了吗？

'Already'
 
使用副词 already 来表达某事已经发生，或询问某事是否已经发生。该副词常直接放在主要动词之前。
 
You can't come? But I've already booked the tickets!	你来不了吗？可我机票都定好了！
Carly has already been to Paris, but I haven't.	Carly 已经去过巴黎，我还没去过。
Has John already been to the Louvre?	John 已经去过卢浮宫了吗？

'Never' 和'ever'

 
用副词 ever 询问是否有事情发生，或谈论某人的经历。作为否定的回应，用 never，这类副词常常放在主要动词前面。
 
A: Have you ever lived in another country? 
B: No, I've never lived in another country.	你在其他国家生活过吗？
不，我从未居住在另一个国家。

语言提示：学习者的一个普遍的错误是在肯定句中使用副词 ever，注意在例子中做出正确反应。
 
A: Have you ever been to Paris?
B: Yes, I have been to Paris.	您去过巴黎吗？
是的，我去过巴黎。
** unit 2
*** 用'as ... as' 做比较

用 as + 形容词 + as 表达在某种情况下，两样东西是一样的。
 
My cat, Gatsby, is as intelligent as a person.  	我的猫 Gatsby 和人一样聪明。
That dog isn't as loud as my parrot.  	那条狗没我的鹦鹉吵。

您也可以用 as + 副词 + as 表达两种事物在某种情况下相同。
 
Trudy sings as well as Madonna. 	Trudy 歌唱得像麦当娜一样好。
Your brother eats as quickly as my snake. 	你的兄弟吃起东西来跟我的蛇一样快。
*** 变化规则的形容词最高级
对于大部分有两个或更多音节的形容词，用 most 或 least + 形容词，形容词不变。
 
intelligent > most intelligent / least intelligent
Are monkeys the most intelligent animals?	猴子是最聪明的动物吗？
My least favorite animal is the snake.	我最不喜欢的动物是蛇。
I think the dolphin is the most beautiful sea animal.	我认为，海豚是最美的海洋动物。
*** 提出强烈建议
You'd better be careful.
你最好当心一点。
Don't go into the mountains alone.
不要独自进山去。
Make sure you get excellent equipment.
务必携带质量优良的装备。
Always tell someone where you're going.
总是告诉别人你要去的地方
*** 使用逗号

在系列表达中，用 (,)隔开词句，不要在 and 前用逗号。

I saw dogs, turtles, birds, a snake and fish in the park.
 

当连个从句被 but 连接时，用逗号。逗号放在 but 前。

I saw an elephant, but I didn't see a lion.
 

当 when 或 after 引导的从句放在句首时，用逗号与后面的主句隔开。

When I was on vacation in Chile, I saw a lot of wild animals.

After I got home, I looked at all my photographs.

如果 when 或 after 从句放在句尾，不要用逗号与前面的主句隔开。

John talked a lot about Africa after he got home.

They got a new cat when their old one died.


使用逗号分隔城市名称与州或国家。

I live in Beijing, China.
*** 过去进行时
*** 讲述故事
讲故事的惯用方法
 
描述过去发生的事情时，使用这些常见的讲故事的惯用方法。
 
故事背景中的过去进行时

设定故事背景时，使用过去进行时态
 
Let me tell you the story about how I met Shane. I was sitting in the movie theater.	 	我告诉你我是怎么遇见 Shane 的故事。我坐在电影院里。

开头和结尾
 
你讲的故事应该有头有尾。
 
I was sitting in the movie theater. He dropped his pizza on his shoes. I helped him clean up, and we left together.    	 	我坐在电影院里。他把披萨掉自己鞋上了，我帮他弄干净，然后一起离开了。

故事事件的排序

使用类似表达开始故事。
At first, I didn't like him.	起初，我不喜欢他。
In the beginning, he seemed unfriendly.	刚开始，他看起来不是很友好。

使用类似表达继续讲述故事。
Later, we started talking in the break room.	后来，我们在休息室开始交谈。
After that, we had lunch a couple of times.	之后，我们一起吃过几次午饭。
Next, we went on a date.	接下来，我们约会了。

使用类似表达结束故事。
Finally, he asked me to marry him.	最后，他要我嫁给他。
In the end, we got married and had three children.	最后，我们结婚，生了三个孩子。
*** 谈论关系
Buddy 是表示朋友的非正式用语。注意，该词多为男性使用，指代他们的男性朋友。
Relatives 是指你家族中的人，比如 cousins 和 aunts。
有许多描述职业关系的方法。Co-workers 和 colleagues 是指和你共事的人。两个词是同义词，意思相同。
boss 和 manager 也表示同一事情，但 boss 正式程度更低。
使用 acquaintance 表示你了解一点的人。这可能是个人关系，也可能是职业关系。
*** 含有过去进行时的'When' 从句
用过去进行时描述动作在某一个时间正在进行，一个含有一般过去时的 when 从句用来表达动作被打断。
 
I was writing an email when the phone rang.	我正在写邮件，这时电话铃响了。
I was taking a shower when someone knocked on the door.	我正在洗澡，这时有人敲门。


I first met my best friend when we were swimming at summer camp. We were 8 years old. Natasha was incredibly tall. She was taller than all the other children. She asked me a question: 'Why are you wearing that orange swim cap?' So I asked her: 'Why are you so tall?' Natasha laughed. Her mouth was purple from eating strange candy. I laughed, too.    
 

I first met my colleague, John, when we were studying at Duke University. He walked into my room, said hello, and then we started talking about history together. John looks like one of those little people in 'Lord of the Rings,' with funny ears. He always has a smile in his eyes. He also tells crazy stories. He has one story about playing the flute in New Orleans. He was playing on the street when a river of water came down the street. He ran! In the end, both John and I got hired by BTC. Now he's an old friend.
*** 状态动词
 
有些动词不描述动作 ——它们描述状态、状况或形势。它们称为 stative verbs。注意，这些动词几乎从不用于 -ing 形式。
 
类似 see、hear 和 know 的静态动词可描述你感知或理解的东西。
I hear birds outside.	我听到外面有鸟叫。
have 和 own 等静态动词可描述你拥有的东西。
She has a new car.	她有一辆新车。
love 和 hate 等静态动词可描述你对某事的感受。
I hate vegetables!	我讨厌蔬菜！

记住：静态动词几乎从不用于 -ing 形式。
*** 
描述情感

要描述自己的感受，你可以使用动词 feel 或 be。
I was really embarrassed.	我非常尴尬。
I felt guilty.	我觉得很内疚。

要描述他人的感受，如果你肯定他的感受，你可以使用动词 be。
He was upset.	他很沮丧。

如果你觉得你知道对方的感受但不是完全肯定，使用动词 seem。
He seemed upset.	他似乎很沮丧。

描述对于某一事件的感受时，使用 be 和 happen 等动词。
The hike was fantastic!	远足太棒了！
Something crazy happened.	很蠢的事情发生了。
*** 叙述现在时
 
你可以用现在时讲述过去发生的事情。使用现在时，可以让人感觉故事正在发生，更加生动。讲故事时，人们常常在一般现在时和一般过去时之间来回变换。
 
Audio Player

OK, so it's yesterday morning. I wake up. I'm still sleepy. I look out the window. I couldn't believe it! There's a wolf in my backyard. And it's sitting in my favorite chair. 
 

MELISSA: Okay, so Ralph walks  up to me, and he has a picture  in his hand.
NICK: A picture of what?
MELISSA: A cat. In a pink sweater.
NICK: What? Whose cat?
MELISSA: His. The cat in the pink sweater is Ralph's  !
NICK: Really?
MELISSA: Yep, and so Ralph gives  me the picture. He says  , 'Isn't Lucky cute in this picture?'
NICK: Ha! Very surprising.
MELISSA: I know! I couldn't believe it! Ralph isn't all bad. He is very strange, though. 
*** 灾难和紧急事件
I ended up on the sidewalk.  我最终倒在人行道上。
*** 含过去进行时的'While' 从句
 
使用 while + 过去进行时，描述被另一动作中断的一个持续动作(While it was raining)。中断的动作使用一般过去时(the electricity went out)。
 
Audio Player

While it was raining, the electricity went out.	下雨的时候停电了。
Audio Player

While we were sleeping, the electricity came back on.	我们睡觉的时候，又有电了。


当两个过去持续的动作同时发生，你可以把 while 用在任意一个动作上。
 
Audio Player

While Ken was calling the police, the neighbor's dog was barking.	当肯在给警方打电话时，邻居的狗在犬叫。
Audio Player

While I was driving, I was putting on my lip gloss.	开车时，我涂上了润唇膏

如果 while 从句位于句后，不使用逗号。
 
Audio Player

The electricity came back on while we were sleeping.	我们睡觉时又有电了。
Audio Player

The neighbor's dog was barking while Ken was calling the police.	肯在给警察打电话时，邻居的狗在犬叫。

pizza delivery guy  送披萨的外卖员

I bet! 我肯定！



Zen Garden is a great choice for lunch or dinner. Their specialty  is vegetarian dishes, but there are also some lovely fish and chicken choices. The restaurant is very popular, and many people come for the authentic  French desserts. The menu doesn't have a wide variety  of choices, but everything is fresh and the prices are reasonable  . Outdoor seating  is available from June to August. Zen Garden is located at 1415 Grove Street. Call 760-434-9292 for reservations  .
*** 餐厅定位
A: Good afternoon. Zen Garden. How can I help you?
B: Yes, good afternoon. I'd like to make a reservation.

A: Certainly. For what day?	当然可以，你想预订哪一天？
B: Tomorrow evening.	明天晚上。
A: OK, that's Friday the 19th. And how many people in your party?	好的，那就是 19 号，星期五。你的派对有多少人？
B: Three people. I was thinking around 7:30 or 8.	三个人。我想预订 7:30 或 8 点左右。

A: And what's the name, please?	请问，你的姓名是什么？
B: Jane Grimes.	简·格兰姆斯。
A: Very good, Ms. Grimes. I have you reserved for three people tomorrow night, Friday the 19th, at 9 pm. Thank you for calling.	很好，格兰姆斯女士。我帮你预订在明晚，即 19 号星期五，晚上九点，三个人。谢谢你的来电。
B: Great. Thank you very much.
*** 'waiter' 的不同说法
 
传统上来讲，在餐厅里如果向您提供服务的是男士则被称为 waiter，如果是女士则称为 waitress。然而，随着英语越来越中性化，通常在餐厅里向您提供服务的男士和女士都一律称为 waiters。  

您还可以使用另一个中性词 server。该词适用于表达站在柜台后面的人，或等您点餐的人，或把食物送到您餐桌上的人。
*** specials
特色菜
Audio Player

starter
前菜
Audio Player

tomato salad
番茄沙拉
Audio Player

goat's cheese
山羊奶酪
Audio Player

olives
橄榄
Audio Player

main course
主菜
Audio Player

wild salmon
野生三文鱼
Audio Player

lemon and butter
柠檬和黄油
Audio Player

dessert
甜品
Audio Player

fresh strawberries
新鲜草莓

一顿饭的各部分
 
在说英语国家的绝大部分餐馆，一份 starter 或 appetizer 是开餐的一小碟食物，包括类似这样的食品：
 
Audio Player

mushroom soup	蘑菇汤                                                
Audio Player

Caesar salad	凯撒沙拉
Audio Player

fresh oysters	新鲜生蚝
Audio Player

shrimp cocktail	鸡尾冷虾

一个 main course, 或 entree, 是一餐饭的主菜。这将包括类似这样的东西：
 
Audio Player

roasted chicken with vegetables	烤鸡配蔬菜
Audio Player

steak and baked potato	牛排和烤土豆
Audio Player

fresh fish with rice	鲜鱼配米饭


dessert 通常是在饭后吃的一碟甜食，常配茶或咖啡吃。这包括这些东西：
 
Audio Player

apple pie	苹果派
Audio Player

chocolate mousse	巧克力慕斯
Audio Player

lemon sorbet	柠檬果汁冰球

您的侍者也许会给您介绍餐馆提供的 specials，也许没有列在菜单上。specials 也许包括餐饮的任何部分。只有在一年的某个时段才能提供的新鲜的当地水果就是很好的例子，



SERVER: Good evening. My name is Carol. I'll be your server  tonight. Here are your menus  . Can I get you something to drink?
PENNY: No, thank you. Water is fine for now.
SERVER: Can I tell you about our specials  this evening?
PENNY: Yes, please.
SERVER: As a starter  , we have fresh oysters. We also have a very nice shrimp cocktail. For the main course  , we have chicken with vegetables, and we also have a sirloin steak with baked potato.
JOHN: Oh, I'm getting hungry!
SERVER: Our dessert special  is chocolate mousse with fresh strawberries.
PENNY: Thank you very much. I think we need a few minutes.
*** 餐馆实物

sirloin steak
西冷牛排
Audio Player

the salmon
三文鱼
Audio Player

baked potato
烤土豆
Audio Player

french fries
薯条
Audio Player

sour cream on the side
配酸奶油
Audio Player

a glass of iced tea
一杯冰茶
Audio Player

chef's salad
生拌蔬菜沙拉
Audio Player

dressing
调味酱
Audio Player

blue cheese
蓝纹干酪


a glass of iced tea

steak and baked potato

french fries

mushroom soup

wild salmon

chef's salad

sour cream on the side

blue cheese dressing

** unit 6
It's my pet hate.

So disgusting.

Somebody call the fashion police.

cares as much about fashion as you do.

通常用 far too, way too 的表达批评别人, 以强调反对.
That dress looks way too baggy.

*** 寻求和表示赞美
 
用 look +形容词来恭维某人的外貌。
 
Audio Player

You look fantastic!	你看起来很美！
Audio Player

That shirt looks great on you.	你穿那件衬衫很好看。
Audio Player

That color looks good with your hair.	那个颜色和你的发色很配。
 
您也可以用 good at +动词 + -ing 来恭维他人。
 
Audio Player

You're good at putting together an outfit.	你很擅长搭配衣服。
Audio Player

You're great at creating new styles.	你很擅长创造新的风格。

*** 寻求和给予安慰
如果您对您的外表有疑问，用 I'm not sure about 来确认，告诉别人不要担心以消除疑虑，然后说上一句恭维。
 
Audio Player

A: I'm not sure about this tie.
B: I wouldn't worry about it. The color looks good with your suit.	我不确定这条领带是否合适。
要我就不担心。这个颜色和你的西服很配。
 	 	 
Audio Player

A: I'm not sure about my outfit.
B: Don't worry. You look great!	我不确定我的衣服打扮好不好。
别担心。你看起来很棒！
 
您也可以用带有 think 的问题来请求确认，说 not at all 或 Actually, no.来消除疑虑。您也可以告诉他们不要担心，并加一句恭维。
 
Audio Player

A: Do you think this outfit makes me look ugly?
B: Not at all!	
你觉得我这一套衣服看起来难看吗？
一点也不！
 	 	 
Audio Player

A: You don't think this necklace is weird?  
B: Actually, no. Don't worry, you look fabulous.	你不觉得这条项链很怪吗？
实际上不是。别担心，你看起来很美。

*** 形容词顺序
 
描述中使用形容词超过一个时，一般按照观点、大小、年龄、颜色、来源、材料的顺序依次排列。
 
Audio Player

Look at this fabulous, long, old, navy blue, Chinese, silk jacket.	看看这件极棒的海军蓝中式长款旧丝绸上衣。
 
观点	大小	年龄	颜色	来源	材料
fabulous	long	old	navy blue	Chinese	silk
 
注意这些例子中的形容词顺序：
 
Audio Player

Heidi's carrying a stylish, beige, leather handbag.	海蒂拿着一只时尚的米黄色手提包。
Audio Player

Your baseball cap is way too nasty, small and old.	你的棒球帽实在是太脏了，而且又小又旧。
Audio Player

How about your new, gray, Italian, wool suit?	你那新的灰色意大利羊毛西服怎么样？
Audio Player

I look for brands that use classic, Egyptian, cotton fabrics.	我在找采用埃及传统棉纺面料的品牌。



I prefer wearing stylish, comfortable clothes, not formal outfits. I'd rather wear natural fabrics than polyester. One of my favorite outfits is some cool, old jeans with a thin, green, cotton T-shirt. I like to wear it with my new, blue tennis shoes. In the winter, I like to put on a big, black, polyester jacket. It's not natural fabric, but it's incredibly warm.

* level 4
** unit 1
** words
 | En                     | Zh                                                                     |
 |------------------------+------------------------------------------------------------------------|
 | events                 | 演出                                                                   |
* refers
  [[http://sciencing.com/native-plants-animals-china-6618275.html][Native Plants & Animals of China]]
