* 心得 Self
  1. 注意看换手率, 换手率高而股价又下来的, 可能是庄家已经出手, 尾盘不要进
  2. 信息不对称使得拥有信息优势的人可以通过内幕交易获取超额收益， “羊群效应”的存在很大程度上放大了信息不对称对市场的影响。当一方长期处于信息优势时，另一端的弱势方将会密切跟踪对方的交易行 为，如果信息优势方大量买入股票，弱势方则会大量跟进。这种行为使 得很多有资金实力的投资者利用自己长期的信息优势地位，引导其他投 资者跟风操作。另一方面，这一行为往往也是利用了投资者“喜欢追涨”、 “止盈不止损”的心理习惯。股价上涨时，动量交易推升股价进一步上 涨，而股价下跌时，处置效应的存在使得投资者不会大量跟风卖出。
  3. 华尔街上有一种说法:总是试图在最低谷买入或者在最高峰卖出的人, 往往失大于得.
  4. 注意不要追高, 注意不要冲动追高, 不要追高
  5. 牛市中趁低买入, 熊市中趁高卖出
  6. 止损增利. 新手常见的错误之一就是放任损失放大, 而在利润只有几个点的时候就草草平仓.
  7. 找火的版块, 找火的股票, 找上行的股票, 集中资金, 做 T.
  8. 股票龙虎榜跟音乐排行榜很像, 一次上榜后, 后边很容易继续上榜.
  9. 不要在盘中看到股票了就买, 遵循前边的选择操作.
* 股票趋势技术分析圣经(book)
  1. 没有任何技术图形的预测是百分百可靠的, 所以一定要止损.
  2. 通常来说, 一般交易者最好交易 4 中股票, 每种 25 股, 而不是交易 100 股一种股票, 更好的做法是这四只股票分别选自 4 个不同的行业.
  3. 内部人士获利通过两种方式实现: 内部人从公众手中买入股票, 再高价卖出; 或者内部人将股票卖给公众, 再低价买回.
  4. 研究市场情况, 分析内部人的交易路线; 发现内部人在市场中正在进行的操作, 并紧随其后.
  5. 分析公众投资者的未来交易动向. 分析内部人的未来交易动向.
  6. 公众投资者的买入与卖出对技术图形有非常大的决定作用, 但是必须意识到, 最有力最重要的信号来自内部人有组织的买卖交易.
  7. 一只股票或整个市场常往与公众预期相反的方向运动.公众的预测一般都是错误的, 否则价格按谁都知道的方向移动, 那么没有人能够获利.
** 重要反转形态-1
7. 不要忽略对形态所处主要趋势的分析. 顶部反转形态只出现在上涨运动后, 底部反转形态只出现在下跌运动后, 突破一般需要较大的成交量来确认.
8. 不要"操之过急", 等决定性突破后再操作.
9. 应该再长期图表中检验头肩形态. 长期图表中的形态也可以帮助长线交易者或投资者确认周期性变化的发生. 可以利用周线图和月线图来检验形态预测的准确度和可靠性, 有时也可以帮助交易者抓住主要趋势, 防止进行反方向操作. 用日线图来获取有利可图的买入或卖出时机, 若发现周线图预测的趋势与日线图相反, 也不要紧张.
** 重要反转形态-2
1. 绝大多数反转形态都伴随着原本占据优势的多头力量被空头力量逐渐压倒, 或者原本占据优势的空头力量被多头力量逐渐压倒.
2. 有两种形态比较难区别: 圆形顶和头肩顶. 但是这两种形态都预示着之前趋势的反转, 而且预测准确性也相近. 如果圆形顶的高峰和左右两个中锋更尖锐, 更突出一点, 而不是缓慢过渡, 那么这个形态就是头肩顶.
3. 圆形底形态比圆形顶形态更常见.
4. 圆形反转较少出现在交易活跃的顶部, 而较多出现在相对冷清的底部.
5. 圆形反转的图形, 成交量总是在价格越过底部最低点, 进入新趋势后开始快速上升, 这种交易活动的明显增加是普通或圆形反转中不变的特征, 也是买入卖出信号的重要确认.
6. 三角形态是不可靠的反转形态. 三角形态可能是调整形态, 也可能是反转形态. 但是三角形态是一个非常重要, 非常有用的图表形态.
7. 在达到三角形态端点之后, 进入后续运动的过程被称为"突破", 突破通常指明接下来大规模, 有利可图的价格运动方向. 有时候, 三角形态端点后会出现"虚假移动", 即出现一次暂时背离后来主要趋势的价格移动.
8. 三角形态作为调整形态出现更为常见也更重要. 如果其他条件相同, 三角形态预示之前趋势的持续更经常出现. 我们在三角形态形成过程中,  假设它是调整形态, 或者中间形态, 直到实际情况证明是相反的结论.
9. 如果之前的运动比较长, 开始显现出技术力量的竭尽, 那么三角形态是反转形态的可能性更大.
10. 当三角形态使原趋势由涨转跌时, 我们将其称作三角顶. 当三角形态使原趋势由跌转涨时, 我们将其称作三角底. 在价格向顶点运动过程中, 每周成交量也在逐渐"萎缩". 如果股价真的突破进入新趋势, 则几乎一定会出现成交量的迅速, 明显增加.
11. 价格突破反转或突破调整时成交量出现明显上升, 在几乎所有重要的技术形态中都适用.
12. 端点之后的波浪运动. 对称三角形形成了一个良好的端点, 单价格一直没有出现突破或者剧烈的后续运动, 反而保持相对不活跃, 价格线只比端点处少宽, 这种不明确的波浪运动可能会持续一周或者更长的时间.
13. 直角三角形态: 下降三角形(预示着下跌趋势的到来); 上升三角形(预示着上涨趋势将出现)
14. 市场整体趋势对对单个股票的趋势产生"抑制"也经常发生, 因整体趋势的上升可能会影响单个股票延迟向下突破, 相反也一样.
15. 向上与向下楔形的反转: 有经验的交易者会在出现向上楔形的顶部 *立即* 进行交易, 而在出现向下楔形的底部则保守地 *等待一段时间*, 知道价格与成交量的彪悍表明新的上涨趋势真正开始.
16. 楔形形态必须严格符合定义: 只有严格符合定义时, 才是可靠的反转形态. 楔形的边线必须清晰明确, 且覆盖多个价格端点, 楔形尖端必须清晰地指向上方或者下方. 若尖端几乎水平, 则形态更倾向于三角形态.
17. 三角反转形态的总结:
    - 对称三角形可能预示之前趋势的反转, 也可能说明趋势的持续, 后者比前者更常见. 对称三角形本身并不能告诉我们后续运动的方向. 对称三角形本身不能告诉我们后续运动的方向.
    - 直角三角形态更多的出现在中期或调整形态中, 较少成为反转形态. 他可以在突破发生前给出后续运动方向的可靠预测.
    - 直角三角形的弦指向斜上方为上升三角形, 上涨信号; 指向斜下方为下降三角形, 是下跌信号.
    - 楔形形态使明确界定的价格汇聚趋势, 一般指向上方或者下方, 他们表明之前的股价运动趋势将出现反转.
    - 这些形态的共同点: 随着股价汇聚至定点, 成交量逐渐下降, 直至股价突破形态时, 成交量急剧上升, 之后开始新的趋势.
18. 对称三角形不一定意味着认为操纵或者内部人串谋. 直角三角形确实反映出一定程度上的内部人串谋. 下降三角形描绘出增加的股票供给遇到某一特定价格水平上的有组织的买入; 上升三角形表明增加的股票需求遇到某一特定价格水平上的有组织的卖出.
** 重要反转形态-3
1. 双重顶, 双重底
   这两种形态在预测主要趋势的反转时, 没有评论家说的那么可靠(可能只有三分之一的反转将发生).
   两个高度相近但相距很近的顶峰之后, 往往不会出现反转.
2. 典型的双重顶如何形成
   在活跃的市场中, 股价常常在高成交量的伴随下, 快速涨至峰顶, 然后再没有建立任何明显的反转形态时, 股价下跌几点, 然后再稍低的价格上不太活跃的保持几周. 接着又出现一轮伴随上升成交量的价格上涨, 使股价打到与之前的峰顶想进的水平, 使股价再次下跌, 同事成交量也下降. 这两轮快速上涨都在相同的水平上遇到大量卖出, 使多头力量逐渐耗尽, 股价回落到顶峰之前的水平, 并保持一段时间, 然后进入新的下降趋势, 同时成交量增加.
3. 多重顶往往比双重顶的顶部相距较近, 但是预示意义与双重形态相同.
4. 伪双重顶的解释
   有的时候形态的间隔段的持续时间, 两峰之间的下跌幅度等都不符合双重顶的要求, 只是看起来像双重顶.
5. 总体来看, 均价图中出现的双重形态确实比个股具有更强大和更重要的反转预测能力.
6. 可靠的复合形态, 可划分为两种具体的头肩形态: 多头双肩形态和多肩单头形态.
   最重要最可靠的反转形态, 但是不太常见.
   复合形态反转的形成过程中, 成交量变化没有明确的模式(突破颈线时成交量的剧烈增加).
7. 喇叭顶
   必须满足"五次反转", 形态一旦完成, 预示着即将出现大规模, 快速的下跌.
   喇叭形态很少见, 也不是绝不出错, 但是当它起作用时, 其意义非常重要, 一般表示大牛市或者大熊市的关键转折.
** 其他反转形态
1. 扩散三角形很少见, 但扩散三角形态成为反转形态的比例远高于成为调整形态. 扩散三角形在顶点处出现较高的成交量, 之后成交量有一定下降, 但不会继续萎缩, 相反成交量变化非常不规律, 而且一般会随着形态的发展而逐渐上升.
2. 菱形形态比较可靠. 更多的出现在顶部, 很少出现在底部.
3. 矩形形态 -- 对于走势图中出现的任何一个清晰的矩形形态, 技术交易者最好都认真关注.
   矩形可能持续相当长一段时间, 也可能很细. 矩形形态既可能是反转形态, 也可能是整理形态.
   成交量与三角形态类似, 形态开始时成交量一般较高, 接着随着形态的发展, 成交量逐渐萎缩, 常常降为零, 最终突破出现时, 成交量显著增加.
4. 静止状态的突破: 没有人愿意在这个价格买入股票, 持有者宁愿继续持有, 也不愿意在这么低的水平卖出.
5. 岛形反转的描述: 缺口应该再相同的高度(图形的两个缺口之间必须有一段水平的空白部分)
** 几种重要反转形态总结
1. 头肩形
2. 普通或圆形反转
3. 三角形: 对称三角形; 直角上升/下降三角形
4. 多重顶和多重底形态
5. 复合形态
6. 楔形
7. 喇叭顶
8. 扩散三角形
9. 菱形
10. 矩形及其变化
11. 岛形
** 重要的整理形态
1. 在整理形态的情况下, 之前的主要趋势被打断, 可能因为阻力过强, 或者之前的趋势发展过快, 或者内部人操作已经进入巩固期, 抑或内部人还没有决定要继续操作还是结束操作行动, 因此在等待市场自身变化的信号. 当中期形态开始形成时, 图形可能最终成为反转形态. 等待市场本身显示出的技术信号, 然后查看图形是整理形态还是反转形态.
2. 内部人操作与整理形态: 假设内部人吸入 10000 股某股票, 使股价从 50 上升至 75, 在 75 的水平上抵抗很强硬, 压制股价无法继续上涨. 多头的内部操作者会立即停止大量买入, 将主动权交给公众投资者, 在等待股票自身技术力量显现的过程中, 他们会求稳, 将部分股票卖出获利.
   如果公众投资者的买入扔很积极, 则逐渐消化了之前强硬的抵抗力量. 但内部人希望进一步检验股票的技术力量, 因此会抛出部分股票来迎合公众投资者的买入, 同事获利.
   不久, 内部人使股价进入一个较窄的区间内波动, 但他们认为股价仍有涨到 90 的潜力. 因此他们将形态开始时抛出的部分股票再次吸入, 通过谷买峰卖来控制价格变化, 在获利的同事加强股票的技术力量.
   当公众发现股价已经停止上涨时, 尤其当内部人使股价在形态末尾, 第二轮上涨之前出现暴跌或者虚假移动时, 公众会着急抛出获利. 此时内部人再买回之前形态发展时抛出的 3000 股或 4000 股, 同时获得小幅净利. 这时, 他们不仅在 1000 股上实现了至少 25 点的利润, 而且在形态形成过程中还获得大量中期利润.
3. 对称三角形态
   如果之前的股价运动延续时间很长, 且近期没有出现停滞或干扰, 则对称三角形很可能是反转形态. 如果之前的运动既短且弱, 则对称三角形态更可能是整理形态.
4. 在下跌趋势中, 股价突破支撑线时, 成交量不一定会明显增加.
5. 三角形态及矩形形态有一个共同特点, 他们都既可以作为整理形态, 又可以作为反转形态, 因此我们不得不等到形态完成, 新趋势起步时, 才能稳妥的操作.
6. 旗形和三角旗形, 没有反转意义, 仅仅预示著之后股价趋势的持续.
   他们都是股价上涨或者下降趋势中紧凑且迅速的"修正"或"巩固"变化构成. 他们可能出现在中期或主要趋势的前期或后期, 但一般都在股价变化速度超过正常水平的时期.
   旗形形态的首要特点是一段近乎垂直的价格运动, 放心可能向上或向下. 这段运动到某天猛然刹住, 有时伴随着高成交量, 而之后几天到几周的时间里, 股价都在清晰可见的平行线间波动. 在此期间, 成交量明显的递减.
7. "头肩"整理形态与头肩反转形态的异同
   同: 头肩整理形态中的颈线与头肩反转形态中一样关键, 在颈线被明确突破之前, 形态尚未完成, 而且没有预测意义. 股价在突破颈线时成交量将出现显著增加.
   异: 需要仔细分析成交量的变化.
      头肩反转形态中, 左肩和头部的成交量相对较高, 头肩之间两端区域内成交量较低, 右肩处成交量比前面稍高, 最终股价明确突破颈线时, 成交量显著增加.
      头肩整理形态中, 头部和双肩形成时, 成交量并不高, 但是头肩中间反弹部分反倒出现较高的成交量.
** 整理形态的总结
需要一再强调"抢跑"的危害.
在某些情况中(例如扩散三角形态), 交易者更明智的做法可能是不等突破发生就平仓.
1. 既能指示反转又能指示整理的形态
   - 对称三角形态
   - 扩散三角形态--所有类型
   - 矩形形态
2. 只能指示整理的形态
   - 上升趋势中
     + 上升直角三角形
     + 旗形(一般向下倾斜, 也有例外)
     + 三角旗形(向下倾斜)
     + 头部朝下的头肩整理形态
   - 下跌趋势中
     + 下降直角三角形
     + 旗形(一般向上倾斜, 也有例外)
     + 三角旗形(向上倾斜)
     + 头部向上的头肩整理形态
3. 只能指示反转的特殊情况
   - 上涨趋势中
     下降直角三角形
   - 下跌趋势中
     上升直角三角形
** 其他中期形态及现象
  涉及形态包括:
    - 下垂底和加速顶
    - 号角形
    - 扩散号角形
    - 缺口, 线外运动, 扇形及其他重复出现的现象

1. 下垂底 - 与下降式三角形相对应的形态
    下垂底指一段倾斜向下的股价波动路径, 而且在形态末尾处, 股价到达一个倾斜点.
2. 加速顶 - 与上升式三角形相对应的形态
3. 股票下跌易, 股票上涨难.
4. 缺口的四种分类(有的不能被归类):
   - 普通缺口 :: 很快被封堵
   - 突破缺口 :: 很少能够被封堵
   - 整理缺口 :: 表明股价当前的快速运动将持续
   - 竭尽缺口 :: 表明股价在之前的趋势上"最后一搏", 接着进入修正或中期反转阶段.
** 趋势线
   需要反复试错
   1. 趋势线有两层用途.
      当他们完好时, 可以勾勒出股价运动的趋势; 当他们被破坏时, 可以通知我们可能出现的反转, 并建议我们及时舍弃旧趋势线, 开始寻找新的趋势线.
   2. 越有经验的人, 对自己当前的预测就越谨慎, 并当图中股价运动给出信号时, 越乐意及时更正原有趋势线, 尝试新的趋势线.
   3. 趋势线的合适角度
      股票趋势的正常倾角, 在股价运动开端, 主要趋势的股价运动可能非常剧烈和陡峭, 当倾角接近正常水平时, 不要沮丧, 说明趋势线的可靠性与持久性越强. 当后续股价运动使倾角变的过小, 甚至低于该股票正常水平, 那么要开始警觉, 并寻找重要趋势反转出现的信号.
   4. 是什么构成了显著的突破
      - 股价运动的幅度(最重要) :: 超出的少不算突破(比如股票在 25-50 应为一个点, 在 50 以下的小于一个点没什么意义, 大于 50 的相应的再放宽)
      - 突破当天的收盘价 :: 如果当日股价一度突破趋势线, 但最终掉头收盘于趋势线内, 那么一般不认为趋势已经被破坏.
      - 成交量 :: 成交量并不是显著突破的必要条件
   5. 慰平趋势类似圆形反转
      此趋势类似于扇叶式散开的趋势线. 这种现象看上去就是一个规模较大, 变化较缓且相当不规则的圆形反转.
   6. 利用形态帮助解读趋势线现象
      当趋势线被破坏时, 形态的预测意义对于判断突破信号是重要反转还是趋势修正往往起到很重要的辅助作用.
   7. 突破趋势线后的回撤现象: 有一种常见的回撤现象, 在股价突破趋势线后, 很快又回到趋势之内的现象.
      当趋势线的破坏伴随着突破缺口时, 回撤现象很常发生.
   8. 对数标尺的图, 在一种情况下比较有用: 长期上涨的大牛市, 尤其是在股票均价的月线图中, 或者在与市场趋势紧密相连的龙头股票走势中.
   9. 解读成交量
      + 在解读成交量的技术意义时, 最重要的考虑是两个关系
        - 成交量与前期成交量变化的关系
        - 成交量与同期股价运动的关系
      + 成交量的特点:
        - 趋势反转时的高成交量法则
        - 区域类形态形成过程中, 尤其在接近完成时, 日成交量的标志性下降
        - 股价突破区域类形态时成交量的显著增加
        - 加速或下垂形态中标志极点出现的高成交量
        - 竭尽缺口形成时的高成交量
      + 反转处典型的成交量变化, 典型的成交量变化是两次冲高.
        - 第一次伴随着股价在旧趋势中最后的推动
        - 第二次伴随着股价突破进入新趋势
      + 顶部与底部成交量变化的区别
        - 顶部的极值成交量一般高于突破成交量
        - 底部的突破成交量一般高于极值成交量
        - 大多数情况下, 底部的极值和突破成交量一般整体低于顶部的水平
      + 当股价离开某个波动区域时, 不论其形态如何, 成交量的显著增加都是趋势调整的信号.
      + 如果连续几天出现高成交量, 而股价并无明显的变化, 那么说明股价遇到了重要的阻力, 接下来会出现一定程度的修正运动, 这条基本规律在实际应用中需要极大的灵活性, 而且需要与图中其他因素结合来评估它的重要性.
      + 成交量与基本趋势的关系
        成交量运动的一个基本规律可以简单表述为: 当股价运动与基本趋势方向一致时, 成交量更高; 而方向相反时, 成交量倾向于变低(注意, 只适用于整体考虑, 而不应用于单日成交量的变化).
   10. 成交量与股价运动的关系
       存在超买现象的市场在反弹时成交稀少, 而在下跌时成交热烈; 相反, 当市场处于超卖状态, 下跌时成交稀少, 而在上涨时成交积极.
       牛市一般终结于成交量过大的时期, 而开始于相对较低的成交状态.
** 支撑与阻力水平
   了解股价将在什么水平遇到阻力, 对于实际交易非常有帮助, 它首先可以帮助我们判断买入该股票是否有利, 其次也能告诉我们何时应卖出获利.

   在实际交易中, 最重要的支持和阻力价位出现的区间, 往往是该股票历史走势中曾出现区域形态或价格原地波动的区间.

   阻力价位和支撑价位会不停的交换身份.

   建立支撑和阻力位过程的总成交量越大, 该价位对未来股价趋势的影响就越持久.

   被突破的趋势线将很快失去技术意义, 回撤现象的支撑往往只出现一次. 当股价第二次回到旧趋势线附件时, 基本不会再遇到反抗. 价格回撤与趋势线突破之间相隔越久, 这条旧趋势线的阻力与支撑效果就越弱.

   支点: 强阻力点. 当两条趋势线相交时, 支点就出现了. 股价并不总是会返回到支点, 但当这种情况出现时, 股价运动总会在该点停止并掉头, 之后, 离开支点一段距离之后, 股价可能突破其中一条或者两条趋势线.

   中期运动的半途理论: 当一次主要运动中出现了干扰性反转时, 只要反转运动最高只达到之前主要运动幅度的一半(1/3 或者 2/3), 那么我们就可以将这次反转看成一次中期运动(中期修正或回撤).
** 测量法则和形态
   股票交易者在决定买入任何一只股票之前, 需要确定三个问题:
      1. 股价运动合适开始
      2. 股价运动方向如何: 上涨, 下跌?
      3. 股价运动将持续多久之后, 才会被反转或者在某一个位置停滞不前.
   甩尾不是虚假移动: 这种现象发生在股价从一个强形态中有效突破之后, 并没有完成形态预测的运动幅度, 而是迅速掉头向相反方向运动了一段距离. 甩尾现象有时可以通过突破水平之前强有力的阻力(支撑)区域来预测.
** 交易技巧
   交易者应该跟随已经确立的主要趋势, 而不应在出现反方向的中期趋势时就盲目改变仓位.

   最重要的一点: 逐渐的建仓, 逐渐的出仓. 永远记住, 不论建仓还是出仓, 都不必追求在上涨过程中就全部完成.

   风险分散

   不要强求图表形态. 初学者在热情推动下发现原本不存在的技术形态. 图表交易时, 即使有几近完美的形态出现, 仍然可能预测失败, 如果加上经过想象美化后的图形带来的风险, 那么后果不堪设想.

   等待更理想的时机: 要抑制自己获利的欲望, 没有良好形态出现时安心呆在场外, 而不是在不好的时机带着一腔热情匆忙入场. 多数急躁的行动往往导致最终利润, 资本和信心的损失.

   永远记住一句交易员中流行的谚语: 股市赚钱的三条法则: 1. 耐心; 2. 耐心; 3. 更多的耐心.

   尽量用限价指令.

   如果股价没有按照交易者初始的分析发展, 那是市场在试图告诉交易者, 应该改变分析. 如果上周根据市场运动得到的技术预测, 但是本周的预测结果还未实现, 那么交易者改变技术分析, 并改变自己的决策, 不要采取固执的态度, 不论上周的分析多么确定多么完美, 都不以为这它永久有效.

   给市场表现的机会: 交易者应该避免固执和过分自信, 但也要注意堤防缺少耐心和过分急躁. 我们也不必仅仅因为上周的分析还没有实现就立即改变方向, 延迟, 拖沓或者交易冷清都不是变换操作的原因, 只有市场在之前分析的反方向上出现真实, 确定的运动时我们才考虑改变分析.

   提前衡量风险

   不要忽略基本面因素, 但是也不要过分依靠外界建议.
** 总结和回顾
*** 回顾反转形态
    头肩形态, 圆形顶, 多重形态, 双头双肩的符合形态和喇叭顶, 楔形, 矩形和菱形形态, 岛形反转.
    三角形态可能表示反转, 也可能表示整理, 但后者出现的频率更高.
    形态要与相应的关键成交量结合分析.
*** 回顾整理形态
    对称三角形, 上升和下降三角形, 矩形, 整理头肩形态, 旗形和三角旗形是最可靠的整理形态, 下垂底, 加速顶, 号角形态和锯齿形运动, 一日线外运动, 扇形等.
*** 操盘手设计的图标欺骗
    操盘手的工作就是从与公众的博弈中赚钱.
    因此, 可以想象内部人会时不时的攻击一下图表交易者, 操作仓内股票的股价走势形成虚假形态, 诱使一些图表交易者买入或卖出, 而他们自己则可以借机充实仓位.
    用好止损.


* Other
1. 通常来说, 一般交易者最好交易 4 中股票, 每种 25 股, 而不是交易 100 股一种股票, 更好的做法是这四只股票分别选自 4 个不同的行业.
* 投资心理学
** 处置效应
   [[http://wiki.mbalib.com/wiki/%25E5%25A4%2584%25E7%25BD%25AE%25E6%2595%2588%25E5%25BA%2594][mbalib 处置效应]]
   人会采取行动去避免懊悔, 寻求自豪.
   所谓处置效应，是指投资人在处置股票时，倾向卖出赚钱的股票、继续持有赔钱的股票，也就是所谓的‘出赢保亏’效应。这意味着当投资者处于盈利状态时是风险回避者，而处于亏损状态时是风险偏好者。
 　最后,价值函数呈不对称性,投资者由于亏损导致的感觉上的不快乐程度大于相同数量的盈利所带来的快乐程度。因此投资者对损失较为敏感。
** 翻本效应, 风险回避效应
** 禀赋效应
   [[http://wiki.mbalib.com/wiki/%25E7%25A6%2580%25E8%25B5%258B%25E6%2595%2588%25E5%25BA%2594][mbalib 禀赋效应]]
   禀赋效应是指当个人一旦拥有某项物品，那么他对该物品价值的评价要比未拥有之前大大增加。
