* 老鸭头
一. 相关知识点讲解：
  1. 波浪理论
  2. 量芝麻点
      主要特征：成交量连续出现萎缩，在量能的柱状体表现为小芝麻点，称之为量芝麻点。每天的成交量低于 1%。
       造成这种情况的主要原因：庄家在完成收集筹码的过程中推高了股价，为了清洗浮动筹码，庄家开始震仓。震仓完成的标志就是该抛的都已经抛了，没抛的短期内碰不一定会抛了。这就出现了量芝麻点的情况。
     这种情况出现在一只跌幅超过 50%，底部横盘整理时间超过半年以上的股票上面。如果股票质地不是很差的话，至少是一只翻 3 倍以上的大牛股。
  3. 出水芙蓉
     要是生命线 60 日均线的运用。有效突破生命线 60 日均线意味着股票开始转势。也意味着股票进入上涨区间。
        主要特征：股价经过长期下跌，一直在 60 日均线下方运行，突然某天一根放量大阳线向上突破 60 日均线并且收盘站上 60 日均线。这一根阳线成为出水芙蓉。
        要点：1 股价长期下跌缩量在 60 日线下方整理
              2 放量中大阳线突破 60 日均线
           3 随后可以跌破，但是短期必须重新站上 60 日线。
           4 所有均线系统呈现多头排列（5、10、20、60 均线）
         买点：出水芙蓉出现后逢低买，中大阴线跌破 60 日均线止损。稳健的投资者可以等均线系统多头排列之后再买。
二. 老鸭头图形特征：
  1、首先，该股从缓慢上升突然加速上扬，同时成交量迅速放大，接下来形成了头部了，放大量，但是此时往往量还是要比在拉升中的要小一些。
  2、然后就是下跌，一般是暴跌，接连好几个，可能还会跌停，放量大跌。在 MACD 指标中，因为当时在拉升过程中，MACD 已经上穿了 O 轴，注意，一定要在前期拉升的时候上穿 O 轴，那么在此时的大跌中，MACD 必然在 O 轴以上形成死叉，注意，一定要死叉，接下来呢，跌势越来越小，终于不跌了，成交量也变得越来越小，一般在这里形成一个圆弧底。但是这里又要注意了，跌到这里跌不下去了，有几个关键地方要说明：
   ①成交量呈越来越小的趋势；
   ②这个底部要高于前期上涨的启动点，且要高于 60 日线，越高越好；
   ③有些强势股它在前期的拉升中很强，在这个跌的时段不怎么跌，或者只是缓慢下跌且跌的空间不大。
  3、接下来又会发生什么呢，那就是慢慢上涨，同时成交量慢慢放大。但是不会涨多少又跌下来了，绝对不可能涨过前期头部，量也不能很大，这把跌下来就彻底休息了，成交量是越来越小，慢慢的跌，终于看到地量出现了，同时股价的振幅也越来越窄，日 K 线越来越小（日 K 线和量柱呈现芝麻点的形态），MACD 马上下穿 O 轴了，到这个时候，老鸭头就形成了。
  4、接下来会发生什么呢，拉大阳，加速上涨，逼空走势，MACD 金叉，突破前期的头部，在突破前期头部的时候又要注意了，看成交量，如果突破时候只是适当放量而没放大量，这叫“轻松过头”，说明庄家控盘很强，没花多大力气，在突破后经常回有回抽，而后继续向上拉升。
     这里强调一下：一旦老鸭头形成，威力是很强大的，极具攻击性，在启动过程中如果出现一跟大阳直接穿过短，中，长均线时候，可靠性更好，行话叫“青龙出海”，在拉升过程中出现两阳夹一阴的 K 线组合，阴线往往是十字线最可靠，行话叫“多头大炮”，后势仍将上涨。
小结：
  （1）采用 5、10 和 60 参数的价格平均线。当 5 日、10 日均线放量上穿 60 日平均线，K 线出现出芙蓉后股价站稳生命线，形成鸭颈部。如上图
  （2）上涨到一定阶段，5 日与 10 日线出现死叉，股价从高位出现较大回落时的高点形成鸭头顶。如上图
  （3）当股价回落不久，5 日、10 日均线再次金叉，股价继续向上形成鸭嘴部。如上图
  （4）鸭鼻孔指的是 5 日均线死叉 10 日均线后两线再度金叉时所形成的孔。如上图
三. 操作要点：
         1.股价一定要在生命线上方运行，调整过程中可以试探跌破 60 日均线，但是一定要快速再次站上 60 日线。
        2.在做鸭头部位，股价快速下跌是主力的震仓行为。
          短线卖出技巧：A 5 日线和 10 日线死叉，B MACD 死叉
        3.在做鸭嘴的时候，主力震仓完成的标准：量芝麻点出现。
          买入技巧：A5 日线和 10 日线金叉，B MACD 金叉
        4.在构建鸭颈到鸭嘴阶段，MACD 指标要在 0 轴之上。且指标最好维持在 1 以下。这样上涨的空间就会很大。
        5.分清老鸭头是在上涨的那个波段非常重要。在 1 升浪还是 3 升浪关系到未来上涨的空间的大小。
        6.在构建鸭头阶段要放量，调整构建鸭嘴部分要缩量，最好就是量芝麻点出现。意味着上涨空间不可限量。
