#+OPTIONS: ^:nil

* 列模式
http://blog.sina.com.cn/s/blog_6bc5571a0101ijgh.html
** 先选中,在第一个标记点和最后一个标记点之间(行,列都包括)
然后用下边命令
C-x r d        delete-rectangle
删除矩形区域，不留空白，后面的字符前移
C-x r f        frame-configuration-to-register
C-x r g        insert-register
C-x r i        insert-register
将某个寄存器的内容插入某处
C-x r j        jump-to-register
C-x r k        kill-rectangle
就是剪切某个选定的矩形区域，用C-x r y可以贴上
C-x r l        bookmark-bmenu-list
C-x r m        bookmark-set
C-x r n        number-to-register
C-x r o        open-rectangle
在选定的矩形区域插入空白
C-x r r        copy-rectangle-to-register
将选定的矩形区域复制到某个寄存器
C-x r s        copy-to-register
C-x r w        window-configuration-to-register
C-x r x        copy-to-register
C-x r y        yank-rectangle
类似于矩形区域的粘贴，就是将刚用C-x r k剪切的矩形区域粘贴过来
C-x r C-SPC    point-to-register
*** C-x r t        string-rectangle 在选定区域所有列前(注意起始和结束的列的位置)插入同样的字符

* org模式
http://www.cnblogs.com/holbrook/archive/2012/04/12/2444992.html

** 时间戳
C-c .	插入时间戳；如果连续插入两个时间戳，则插入一个时间范围
C-u C-c .	更加精确的时间戳，在日程表中以时间线显示
C-c !	插入时间戳，不在日程表中显示
C-c <	直接插入时间戳（当前日期）
C-c C-o	访问当前时间戳的日程表
S-left|S-right	以天为单位调整时间戳时间
* command
** 点击(类似与鼠标左键快捷键)打开网页
   C-c C-o
* dired 操作
<<<<<<< HEAD
* emacs 显示行号
(require 'linum)
(global-linum-mode t)
* emacs 自绑定快捷键
** python 快速跳入跳出方法 
(global-set-key (kbd "C-c .") 'jedi:goto-definition)
(global-set-key (kbd "C-c ,") 'jedi:goto-definition-pop-marker)
(global-set-key (kbd "C-c ?") 'jedi:show-doc)
=======
* emacs 快速启动
** emacs -q
不加载任何配置启动
** 用 emacsclient 来连接 emacs server
1. 这个方法首先要有一个启动好了的 Emacs ，并且要已经启动了 server 模式， 你可以用 M-x server-start 来启动 server 模式，或者在自己的 ~/.emacs 里 面加入 (server-start) 来自动启动 server 。
2. 可以通过 emacsclient filename 来快速使用 Emacs 打开文件了！ 事实上，文件是在作为 server 的那个 Emacs 里面打开的，而 emacsclient 将 等待 server 编辑文件。这个时候你可以转到 server 那里去编辑文件
3. 编辑好 之后用 C-x # 来关闭文件并通知 emacsclient 文件已经编辑完成。
4. 你就 可以把自己的 EDITOR 变量设置成 emacsclient 而不用怕启动速度慢了：
  EDITOR="emacsclient +%d %s"
* emacs快捷键
  - M+m j k :: 类似于ide中shift+enter 快捷键，下一行并且缩进 (evil-goto-next-line-and-indent)
  - SPC t f :: 添加80线

* eww mode (h find help)  
You can open a URL or search the web with the command M-x eww. If the input doesn’t look like a URL or domain name the web will be searched via eww-search-prefix. The default search engine is DuckDuckGo. If you want to open a file either prefix the file name with file:// or use the command M-x eww-open-file.

If loading the URL was successful the buffer *eww* is opened and the web page is rendered in it. You can leave EWW by pressing q or exit the browser by calling eww-quit. To reload the web page hit g (eww-reload). Pressing w (eww-copy-page-url) will copy the current URL to the kill ring.

A URL under the point can be downloaded with d (eww-download). The file will be written to the directory specified in eww-download-directory (Default: ~/Downloads/).

EWW remembers the URLs you have visited to allow you to go back and forth between them. By pressing l (eww-back-url) you go to the previous URL. You can go forward again with r (eww-forward-url). If you want an overview of your browsing history press H (eww-list-histories) to open the history buffer *eww history*. The history is lost when EWW is quit. If you want to remember websites you can use bookmarks.

EWW allows you to bookmark URLs. Simply hit b (eww-add-bookmark) to store a bookmark for the current website. You can view stored bookmarks with B (eww-list-bookmarks). This will open the bookmark buffer *eww bookmarks*.

  - SPC t n :: 显示行号

  - SPC c l :: 注释/取消注释一行
  - SPC c p :: 注释/取消注释一段
       
  - SPC s s :: 搜索， 立即进入
  - SPC s b :: 高亮搜索
  - SPC s p :: smart search
  - SPC s j :: jump in buffer
  - SPC x u :: downcase-region
  - SPC n . :: 进入查看模式， "."向下翻页， ","向上翻页。
** jedi补全 及快捷键
(setq jedi:setup-keys t)
(add-hook 'python-mode-hook 'jedi:setup)
(add-hook 'python-mode-hook 'jedi:ac-setup)
(setq jedi:complete-on-dot t)

(define-key python-mode-map (kbd "M-.") 'jedi:goto-definition)
(define-key python-mode-map (kbd "M-,") 'jedi:goto-definition-pop-marker)
(define-key python-mode-map (kbd "M-?") 'jedi:show-doc)
(define-key python-mode-map (kbd "<C-tab>") 'jedi:complete)

如果不能用跳入，跳出方法等快捷键， 可以 M+x jedi: setup
* emacs 正则
** 正则去掉空行
flush-lines命令
用正则^$

